"use client";
import {useState} from "react";
type Offer={listingId:string;itemId:string;title:string;currentPrice:number;offerPrice:number;discountPct:number;watchers:number|null;ageDays:number|null;units30:number;knownUnitCost:number|null;estimatedGrossMarginPct:number|null;ready:boolean;blockers:string[]};
type Refresh={listingId:string;itemId:string;title:string;currentPrice:number;ageDays:number|null;views30:number|null;watchers:number|null;units30:number;score:number;confidence:number;ready:boolean;blockers:string[]};
type Plan={generatedAt:string;version:string;offerCandidates:Offer[];refreshCandidates:Refresh[];counts:{offersReady:number;offersReview:number;refreshReady:number}};
type Result={plan:Plan;offerResults:any[];refreshResults:any[];refreshStopped:boolean};
const APPROVAL="I APPROVE SALES VELOCITY AUTOPILOT V1";
const usd=(v:number|null|undefined)=>v==null?"—":new Intl.NumberFormat("en-US",{style:"currency",currency:"USD"}).format(v);
export default function VelocityAutopilotPage(){
 const[plan,setPlan]=useState<Plan|null>(null),[result,setResult]=useState<Result|null>(null),[error,setError]=useState<string|null>(null),[busy,setBusy]=useState<"plan"|"execute"|null>(null);
 async function load(){setBusy("plan");setError(null);try{const r=await fetch("/api/sales-velocity-autopilot/plan",{method:"POST",cache:"no-store"}),b=await r.json();if(!r.ok)throw new Error(b.error??"Plan failed");setPlan(b);}catch(e){setError(e instanceof Error?e.message:"Plan failed");}finally{setBusy(null);}}
 async function execute(){setBusy("execute");setError(null);setResult(null);try{const r=await fetch("/api/sales-velocity-autopilot/execute",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({approvalText:APPROVAL})}),b=await r.json();if(!r.ok)throw new Error(b.error??"Execution failed");setResult(b);setPlan(b.plan);}catch(e){setError(e instanceof Error?e.message:"Execution failed");}finally{setBusy(null);}}
 return <main className="page" style={{maxWidth:1500}}>
  <section className="health-hero"><div><div className="eyebrow">Sell · velocity automation</div><h1>Sales Velocity Autopilot</h1><p className="health-intro">Prioritizes buyer-intent offers first, then high-confidence stale-listing refreshes. Every live action is revalidated against eBay immediately before execution.</p></div><div className="health-score"><strong>{plan?(plan.counts.offersReady+plan.counts.refreshReady):0}</strong><span> ready</span><small>Profit-guarded actions</small></div></section>
  {error&&<section className="panel" style={{borderLeft:"4px solid var(--danger)"}}><strong>Autopilot stopped</strong><p>{error}</p></section>}
  <section className="panel" style={{marginBottom:18}}><div className="eyebrow">Run controls</div><h2>Offer first, refresh second</h2><p>Offers are 8% max and only auto-send when complete known costs still preserve at least a 20% known-cost margin. Refreshes require 90+ days, ≤5 views in 30 days, zero watchers, zero 30-day sales, price under $100, no buyer-offer eligibility, and no active intervention.</p><div style={{display:"flex",gap:10,flexWrap:"wrap"}}><button onClick={load} disabled={busy!==null}>{busy==="plan"?"Refreshing plan…":"Refresh live plan"}</button><button onClick={execute} disabled={busy!==null||!plan||(plan.counts.offersReady===0&&plan.counts.refreshReady===0)}>{busy==="execute"?"Executing guarded batch…":"Run approved velocity batch"}</button></div></section>
  {plan&&<><section className="metric-grid"><Metric label="Offers ready" value={plan.counts.offersReady}/><Metric label="Offers review" value={plan.counts.offersReview}/><Metric label="Refresh ready" value={plan.counts.refreshReady}/><Metric label="Offer cap / run" value={25}/><Metric label="Refresh cap / run" value={10}/></section>
  <section className="panel" style={{marginTop:18,overflowX:"auto"}}><div className="eyebrow">Buyer intent</div><h2>Seller-offer queue</h2><table style={{width:"100%",borderCollapse:"collapse",fontSize:13}}><thead><tr><th>Status</th><th>Item</th><th>Title</th><th>Price</th><th>Offer</th><th>Watchers</th><th>Margin</th><th>Blockers</th></tr></thead><tbody>{plan.offerCandidates.slice(0,100).map(row=><tr key={row.itemId}><td><strong>{row.ready?"READY":"REVIEW"}</strong></td><td>{row.itemId}</td><td>{row.title}</td><td>{usd(row.currentPrice)}</td><td>{usd(row.offerPrice)} ({row.discountPct.toFixed(1)}%)</td><td>{row.watchers??"—"}</td><td>{row.estimatedGrossMarginPct==null?"Unknown":row.estimatedGrossMarginPct.toFixed(1)+"%"}</td><td>{row.blockers.join("; ")||"—"}</td></tr>)}</tbody></table></section>
  <section className="panel" style={{marginTop:18,overflowX:"auto"}}><div className="eyebrow">Stale inventory</div><h2>Refresh queue</h2><table style={{width:"100%",borderCollapse:"collapse",fontSize:13}}><thead><tr><th>Status</th><th>Item</th><th>Title</th><th>Age</th><th>Views 30d</th><th>Watchers</th><th>Price</th><th>Blockers</th></tr></thead><tbody>{plan.refreshCandidates.slice(0,100).map(row=><tr key={row.itemId}><td><strong>{row.ready?"READY":"BLOCKED"}</strong></td><td>{row.itemId}</td><td>{row.title}</td><td>{row.ageDays??"—"}</td><td>{row.views30??"—"}</td><td>{row.watchers??"—"}</td><td>{usd(row.currentPrice)}</td><td>{row.blockers.join("; ")||"—"}</td></tr>)}</tbody></table></section></>}
  {result&&<section className="panel" style={{marginTop:18}}><div className="eyebrow">Execution result</div><h2>Velocity batch completed</h2><p>Offer results: {result.offerResults.length} · Refresh results: {result.refreshResults.length} · Refresh stopped: {String(result.refreshStopped)}</p><details open><summary>Provider-verified result ledger</summary><pre style={{whiteSpace:"pre-wrap"}}>{JSON.stringify({offerResults:result.offerResults,refreshResults:result.refreshResults},null,2)}</pre></details></section>}
 </main>;
}
function Metric({label,value}:{label:string;value:number}){return <div className="metric"><div className="metric-label">{label}</div><div className="metric-value">{value.toLocaleString()}</div></div>}