import test from "node:test";
import assert from "node:assert/strict";
import { actionConsequence, actionEffort, buildActionBrief } from "../lib/action-presentation.ts";
import { calculateInventoryHealth, type InventoryHealthInput } from "../lib/inventory-health.ts";
import { evaluateInventoryDecisionDoctrine } from "../lib/inventory-decision-doctrine.ts";

const base:InventoryHealthInput={id:"listing",title:"2024 Topps Shohei Ohtani #1",ageDays:150,daysSinceSale:null,views:20,views30:20,trafficObservationDays:30,watchers:0,quantity:1,currentPrice:100,units7:0,units30:0,units90:0,salesDollars30:0,knownUnitCost:null,knownCapital:null,costComplete:null,supportedPriceAction:null,suggestedPrice:null,marketValue:null,compConfidence:null};
function row(overrides:Partial<InventoryHealthInput>,itemSpecifics:unknown={Year:["2024"],"Player/Athlete":["Shohei Ohtani"],Set:["Topps"],"Card Number":["1"]}){const health=calculateInventoryHealth({...base,...overrides});const doctrine=evaluateInventoryDecisionDoctrine({title:health.title,ageDays:health.ageDays,views:health.viewsForDecision,trafficEvidence:health.trafficEvidence,trafficObservationDays:health.trafficObservationDays,watchers:health.watchers,units30:health.units30,units90:health.units90,quantity:health.quantity,currentPrice:health.currentPrice,knownUnitCost:health.knownUnitCost,supportedPriceAction:health.supportedPriceAction,suggestedPrice:health.suggestedPrice,compConfidence:health.compConfidence,itemSpecifics,authoritativeListingDetails:true,listingFormat:"FixedPriceItem",categoryId:"261328",saleLikelihood:health.saleLikelihood});return{...health,doctrine};}
test("operator consequences exclude automatic marketplace execution",()=>{assert.match(actionConsequence("LOWER_PRICE"),/does not change the eBay price/);assert.match(actionConsequence("OFFER_CONVERSION"),/does not send an offer/);assert.match(actionConsequence("END_SELL_SIMILAR"),/does not edit, end, relist, or delete/);});
test("effort labels remain action specific",()=>{assert.equal(actionEffort("OPTIMIZE_TITLE"),"About 5 minutes");assert.equal(actionEffort("ENTER_COST"),"About 2 minutes");});
test("supported pricing presents exact target and manual boundary",()=>{const brief=buildActionBrief(row({currentPrice:125,supportedPriceAction:"lower-price",suggestedPrice:75,marketValue:75,compConfidence:94}));assert.match(brief.recommendation,/from \$125\.00 to \$75\.00/);assert.match(brief.approvalMeaning,/apply.*manually/);});
test("missing evidence does not manufacture an edit",()=>{const brief=buildActionBrief(row({views30:1,title:"Card"},null));assert.match(brief.recommendation,/Do not intervene/);assert.match(brief.approvalMeaning,/defer intervention/);});
