import test from "node:test";
import assert from "node:assert/strict";
import { allocateSellerProceeds, calculateKnownCapital, calculateKnownCostEconomics, summarizeKnownCost } from "../lib/profitability.ts";

test("known costs preserve partial-component disclosure",()=>{const value=summarizeKnownCost({acquisition:10,grading:null,supplies:1,postage:null,other:0});assert.equal(value.knownUnitCost,11);assert.equal(value.complete,false);assert.deepEqual(value.missingComponents,["grading","postage"])});
test("seller proceeds allocate once by line share",()=>{assert.equal(allocateSellerProceeds({orderSellerProceeds:80,orderGross:100,lineGross:25}),20);assert.equal(allocateSellerProceeds({orderSellerProceeds:null,orderGross:100,lineGross:25}),null)});
test("known margin handles quantity refunds and defensible ROI",()=>{const value=calculateKnownCostEconomics({quantity:2,lineGross:60,allocatedSellerProceeds:50,refundAmount:10,costs:{acquisition:10,grading:2,supplies:1,postage:1,other:0}});assert.equal(value.knownCost,28);assert.equal(value.netBasis,40);assert.equal(value.knownCostMargin,12);assert.equal(value.knownCostMarginPct,30);assert.equal(value.roi,50)});
test("gross fallback is labeled and zero investment suppresses ROI",()=>{const value=calculateKnownCostEconomics({quantity:1,lineGross:20,allocatedSellerProceeds:null,costs:{acquisition:0,grading:0,supplies:2,postage:null,other:null}});assert.equal(value.basis,"gross-sale");assert.equal(value.knownCostMargin,18);assert.equal(value.roi,null)});
test("cancelled sales and missing costs never fabricate margin",()=>{assert.equal(calculateKnownCostEconomics({quantity:1,lineGross:20,allocatedSellerProceeds:15,cancelled:true,costs:{acquisition:5,grading:null,supplies:null,postage:null,other:null}}).knownCostMargin,null);assert.equal(calculateKnownCostEconomics({quantity:1,lineGross:20,allocatedSellerProceeds:15,costs:{acquisition:null,grading:null,supplies:null,postage:null,other:null}}).knownCostMargin,null)});
test("known capital respects quantity and aging bands",()=>{const value=calculateKnownCapital({quantity:3,costs:{acquisition:10,grading:2,supplies:1,postage:1,other:0},listedAt:new Date("2026-01-01"),now:new Date("2026-08-01")});assert.equal(value.knownCapital,42);assert.equal(value.ageBand,"180+")});
