import test from "node:test";import assert from "node:assert/strict";
import {evaluateSalesVelocityDoctrine,type SalesVelocityDecisionInput} from "../lib/inventory-decision-doctrine.ts";
import {getTrafficReport} from "../lib/ebay-analytics.ts";
const base:any={interventionSelected:"LEAVE_ALONE",actionConfidence:{score:70,band:"moderate"},whyThisActionOutranksAlternatives:"observe",observationWindowDays:30};
const input=(overrides:Partial<SalesVelocityDecisionInput>={}):SalesVelocityDecisionInput=>({base,impressions:null,views:null,clickThroughRate:null,conversionRate:null,transactions:null,watchers:null,watcherQuality:"missing",offerEligible:null,advertisingEligible:null,currentAdRate:null,knownUnitCost:null,costComplete:false,currentPrice:100,supportedPriceAction:null,suggestedPrice:null,compConfidence:null,trafficFresh:false,...overrides});
test("low exposure recommends only a margin-supported advertising test",()=>{const safe=evaluateSalesVelocityDoctrine(input({impressions:20,clickThroughRate:.7,conversionRate:0,transactions:0,trafficFresh:true,advertisingEligible:true,knownUnitCost:50,costComplete:true}));assert.equal(safe.action,"INCREASE ADS");assert.equal(safe.suggestedAdjustmentPct,3);const unsafe=evaluateSalesVelocityDoctrine(input({impressions:20,trafficFresh:true,advertisingEligible:true,knownUnitCost:90,costComplete:true}));assert.equal(unsafe.action,"MANUAL REVIEW")});
test("send offer requires eBay eligibility and preserves economics",()=>{const decision=evaluateSalesVelocityDoctrine(input({impressions:100,clickThroughRate:2,transactions:0,watchers:2,watcherQuality:"authoritative",offerEligible:true,knownUnitCost:50,costComplete:true,trafficFresh:true}));assert.equal(decision.action,"SEND OFFER");assert.equal(decision.suggestedAdjustmentPct,-5);assert.notEqual(evaluateSalesVelocityDoctrine(input({impressions:100,watchers:2,offerEligible:null,knownUnitCost:50,costComplete:true,trafficFresh:true})).action,"SEND OFFER")});
test("healthy conversion protects margin",()=>assert.equal(evaluateSalesVelocityDoctrine(input({impressions:100,transactions:1,trafficFresh:true})).action,"HOLD / PROTECT MARGIN"));
test("traffic adapter is GET-only and maps metrics",async()=>{let method="";const fetcher:any=async(_url:string,init:any)=>{method=init.method;return new Response(JSON.stringify({records:[{dimensionValues:[{value:"123"}],metricValues:[{metricName:"LISTING_IMPRESSION_TOTAL",value:"42"},{metricName:"CLICK_THROUGH_RATE",value:"1.5"}]}]}),{status:200,headers:{"content-type":"application/json"}})};const result=await getTrafficReport({accessToken:"redacted",listingIds:["123"],start:new Date("2026-01-01"),end:new Date("2026-01-31"),fetcher});assert.equal(method,"GET");assert.equal(result.get("123")?.impressions,42);assert.equal(result.get("123")?.clickThroughRate,1.5)});
