import test from "node:test";
import assert from "node:assert/strict";
import { acquisitionConfidence, acquisitionEconomics, acquisitionRecommendation } from "../lib/seller-single-valuation-domain.ts";
import { buildEvidenceSearchPlan, EVIDENCE_SEARCH_STRATEGY_VERSION } from "../lib/comp-validation/evidence-search-planner.ts";
import { parseCardIdentity } from "../lib/comp-validation/identity.ts";
import type { ValuationResult } from "../lib/comp-validation/types.ts";
import { buildActiveSearchQuery } from "../lib/seller-active-market.ts";
import { scoreManualResearch } from "../lib/seller-research-queue.ts";
import { evaluateCompAgainstIdentity } from "../lib/comp-validation/engine.ts";
import { manualEvidenceToComp } from "../lib/comp-validation/valuation-service.ts";

test("single acquisition economics uses approved assumptions",()=>{assert.deepEqual(acquisitionEconomics(10,30),{currentLandedCost:11.85,projectedGrossProfit:18.15,projectedRoi:153.16,maxBid:12.92,bidCushion:2.92});});
test("low confidence cannot become BUY solely from modeled ROI",()=>{assert.equal(acquisitionRecommendation({estimatedMarketValue:100,currentLandedCost:10,confidence:"Low",acceptedSoldComps:10,exactOrNearComps:10}),"WATCH");assert.equal(acquisitionRecommendation({estimatedMarketValue:100,currentLandedCost:10,confidence:"Medium",acceptedSoldComps:2,exactOrNearComps:2}),"BUY");assert.equal(acquisitionRecommendation({estimatedMarketValue:19.99,currentLandedCost:10,confidence:"High",acceptedSoldComps:5,exactOrNearComps:5}),"PASS");});
test("seller confidence cannot upgrade canonical evidence confidence",()=>{const result={confidenceBand:"insufficient",confidenceScore:99,exactMatchCount:20,nearExactMatchCount:20} as ValuationResult;assert.equal(acquisitionConfidence(result),"Low");result.confidenceBand="moderate";assert.equal(acquisitionConfidence(result),"Medium");});
test("evidence search plan is exact-first and preserves normalized identity discriminators",()=>{const identity=parseCardIdentity("2026 Topps Resurgence Jane Doe Activators Red Auto #A-1 12/25 PSA 10");const plan=buildEvidenceSearchPlan(identity);assert.equal(EVIDENCE_SEARCH_STRATEGY_VERSION,"exact-first-v2");assert.equal(plan[0].tier,"exact");assert.match(plan[0].query,/2026/);assert.match(plan[0].query,/"jane doe"/);assert.match(plan[0].query,/#a-1/);assert.match(plan[0].query,/\/25/);assert.match(plan[0].query,/auto/);assert.match(plan[0].query,/PSA/);assert.deepEqual(plan.map(row=>row.tier),["exact","near","proxy"]);});
test("recent insert and product names normalize centrally",()=>{const update=parseCardIdentity("Victor Wembanyama 2025-26 Topps Chrome Update Series Activators");assert.equal(update.setName,"topps chrome update series");assert.equal(update.variation,"subset:activators");assert.equal(parseCardIdentity("Tom Brady 2026 Topps Resurgence Conductors").variation,"subset:conductors");assert.equal(parseCardIdentity("Jaxson Dart 2026 Topps Resurgence Voltaic Refractor").variation,"subset:voltaic");});
test("active-market queries preserve discriminating identity and exclude lots",()=>{const query=buildActiveSearchQuery("2026 Topps Resurgence Jane Doe Conductors Gold #C-1 /50");assert.match(query,/jane doe/);assert.match(query,/conductors/);assert.match(query,/#c-1/);assert.match(query,/\/50/);assert.match(query,/-lot/);});
test("manual sold evidence must pass the canonical matcher",()=>{const target=parseCardIdentity("2026 Topps Resurgence Jane Doe Conductors Gold #C-1 /50");const accepted=manualEvidenceToComp({id:"1",soldTitle:"2026 Topps Resurgence Jane Doe Conductors Gold #C-1 12/50",soldPrice:40,shipping:1,soldDate:"2026-08-20T00:00:00Z",sourceUrl:null,sourceItemId:"x",designation:"exact"});const rejected=manualEvidenceToComp({id:"2",soldTitle:"2026 Topps Resurgence Jane Doe Voltaic Gold #V-1 12/50",soldPrice:40,shipping:1,soldDate:"2026-08-20T00:00:00Z",sourceUrl:null,sourceItemId:"y",designation:"exact"});assert.equal(evaluateCompAgainstIdentity(accepted,target).tier,"exact");assert.equal(evaluateCompAgainstIdentity(rejected,target).tier,null);});
test("manual research prioritizes scarce ending-soon cards without authorizing value",()=>{const active={observedAt:new Date().toISOString(),query:"query",exactActiveCount:2,nearActiveCount:0,exactAuctionCount:1,exactFixedPriceCount:1,auctionCurrentPrices:[10],fixedPriceAskLow:40,fixedPriceAskMedian:40,fixedPriceAskHigh:40,useful:true};const result=scoreManualResearch({title:"2026 Topps Resurgence Jane Doe Gold #1 /25 RC Auto",currentBid:5,endTime:new Date("2026-08-21T05:00:00Z"),estimatedMarketValue:null,confidence:"Low",active,now:new Date("2026-08-21T00:00:00Z")});assert.ok(result.score>=80);assert.match(result.reasons.join(" "),/no automatic market value/);});
