import assert from "node:assert/strict";
import test from "node:test";
import { canCancelScheduledBid,executeBidAttempt,normalizeSnipeOffset,recoveryStatus,scheduledSubmissionAt,SELLER_BID_STATUSES,type BidExecutionProvider } from "../lib/seller-bid-domain.ts";
const end="2026-08-22T02:00:00.000Z",now=new Date("2026-08-22T01:00:00.000Z");
const input={browseItemId:"v1|sandbox|0",legacyItemId:"123",title:"Sandbox card",buyerUserId:"TESTUSER_buyer",auctionEndAt:end,operatorMaxBid:20,currency:"USD",status:"ARMED" as const,alreadySubmitted:false,now};
function provider(overrides:Record<string,unknown>={},failure=false):BidExecutionProvider{return{getAuction:async()=>({browseItemId:input.browseItemId,legacyItemId:"123",title:input.title,active:true,auctionEndAt:end,currentRequiredBid:12,buyerUserId:input.buyerUserId,...overrides}),placeProxyBid:async(_id,max)=>{assert.equal(max,20);if(failure)throw new Error("Offer rejected");return{offerId:"sandbox-offer",raw:{status:"accepted"}};}};}
test("status lifecycle is complete",()=>assert.deepEqual(SELLER_BID_STATUSES,["DRAFT","SCHEDULED","ARMED","SUBMITTING","SUBMITTED","WON","LOST","CANCELLED","SKIPPED","FAILED"]));
test("scheduling math is UTC, defaults to seven seconds, and enforces the V1 minimum",()=>{assert.equal(scheduledSubmissionAt(end,7),"2026-08-22T01:59:53.000Z");assert.equal(normalizeSnipeOffset(Number.NaN),7);assert.equal(normalizeSnipeOffset(3),5);});
test("cancellation is restricted to pre-submission states",()=>{assert.equal(canCancelScheduledBid("SCHEDULED"),true);assert.equal(canCancelScheduledBid("ARMED"),true);assert.equal(canCancelScheduledBid("SUBMITTING"),false);assert.equal(canCancelScheduledBid("SUBMITTED"),false);});
test("restart recovery rearms only expired, unsubmitted work",()=>{assert.equal(recoveryStatus("ARMED",true,false),"SCHEDULED");assert.equal(recoveryStatus("SUBMITTING",true,false),"SCHEDULED");assert.equal(recoveryStatus("SUBMITTING",false,false),"SUBMITTING");assert.equal(recoveryStatus("SUBMITTED",true,true),"SUBMITTED");});
test("preflight skips unsafe and duplicate executions",async()=>{assert.equal((await executeBidAttempt(input,provider({currentRequiredBid:21}))).status,"SKIPPED");assert.equal((await executeBidAttempt(input,provider({active:false}))).status,"SKIPPED");assert.equal((await executeBidAttempt(input,provider({auctionEndAt:"2026-08-22T02:00:03.000Z"}))).status,"SKIPPED");assert.equal((await executeBidAttempt(input,provider({buyerUserId:"other"}))).status,"SKIPPED");assert.equal((await executeBidAttempt({...input,alreadySubmitted:true},provider())).status,"SKIPPED");});
test("Offer API failure is failed",async()=>assert.equal((await executeBidAttempt(input,provider({},true))).status,"FAILED"));
test("successful proxy bid submits immutable operator maximum",async()=>assert.equal((await executeBidAttempt(input,provider())).status,"SUBMITTED"));
