import test from "node:test";import assert from "node:assert/strict";import {assessSoldInventory,type SoldInventoryActive,type SoldInventorySale} from "../lib/sold-inventory-integrity.ts";
const active=(o:Partial<SoldInventoryActive>={}):SoldInventoryActive=>({id:"a",ebayItemId:"200",title:"2024 Topps Chrome Shohei Ohtani #1",price:20,quantity:1,startTime:new Date("2026-02-01T00:00:00Z"),sku:null,itemSpecifics:{},quantitySold:0,maxObservedQuantity:1,authoritativeObservedAt:new Date(),...o});
const sale=(o:Partial<SoldInventorySale>={}):SoldInventorySale=>({id:"s",ebayItemId:"100",title:"2024 Topps Chrome Shohei Ohtani #1",quantity:1,soldAt:new Date("2026-01-01T00:00:00Z"),price:18,cancelled:false,...o});
test("same Item ID reappearance is high confidence",()=>{const out=assessSoldInventory({active:[active({ebayItemId:"100"})],sales:[sale()],historicalTitles:[]});assert.equal(out.metrics.highConfidence,1);assert.equal(out.metrics.sameItemIdReappearances,1)});
test("strong new Item ID identity is high confidence",()=>{const out=assessSoldInventory({active:[active()],sales:[sale()],historicalTitles:[]});assert.equal(out.metrics.highConfidence,1);assert.equal(out.results[0]?.matchType,"NEW_ITEM_ID_IDENTITY")});
test("listing created before sale is safe",()=>{const out=assessSoldInventory({active:[active({startTime:new Date("2025-12-01T00:00:00Z")})],sales:[sale()],historicalTitles:[]});assert.equal(out.metrics.safe,1)});
test("multi quantity and migration provenance are excluded",()=>{const out=assessSoldInventory({active:[active({quantity:2}),active({id:"b",sku:"MIG-123"})],sales:[sale()],historicalTitles:[]});assert.equal(out.metrics.safe,1);assert.equal(out.metrics.migratedExclusions,1);assert.equal(out.results.length,1)});
test("legacy punctuation duplicate family is explained",()=>{const row=active({title:"2024 Topps Chrome Shohei Ohtani #1..."});const out=assessSoldInventory({active:[row],sales:[sale()],historicalTitles:[row.title,"2024 Topps Chrome Shohei Ohtani #1."]});assert.equal(out.metrics.safe,1);assert.equal(out.metrics.legacyDuplicateFamilyExclusions,1)});
test("different grade does not match",()=>{const out=assessSoldInventory({active:[active({title:"2024 Topps Chrome Shohei Ohtani #1 PSA 10"})],sales:[sale({title:"2024 Topps Chrome Shohei Ohtani #1 SGC 9"})],historicalTitles:[]});assert.equal(out.metrics.safe,1)});
