import Link from "next/link";
import { prisma } from "@/lib/prisma";
import { operatorDecisionLabel, type OperatorDecisionValue } from "@/lib/operator-decisions";

export const dynamic="force-dynamic";
const money=(value:unknown)=>value==null?"Not available":new Intl.NumberFormat("en-US",{style:"currency",currency:"USD"}).format(Number(value));
type Evidence={healthScore?:number;stateLabel?:string;saleLikelihood?:string;listedExposure?:number;knownCapital?:number|null;doctrine?:{doctrineVersion?:string;interventionSelected?:string;diagnosticFunnelStage?:string;problemConfidence?:{score:number};actionConfidence?:{score:number};compConfidence?:number|null;whyThisActionOutranksAlternatives?:string;evaluateNextIfInterventionFails?:string}};

export default async function ActionHistoryPage(){
  const decisions=await prisma.operatorDecision.findMany({orderBy:{decidedAt:"desc"},take:100,include:{listing:{select:{title:true}},outcomes:{orderBy:{windowDays:"asc"}}}});
  const observed=decisions.flatMap(item=>item.outcomes);const sold=observed.filter(item=>item.saleOccurred).length;
  return <main className="page-shell"><div className="eyebrow">Closed-loop learning</div><h1>Action History</h1><p>What you decided, under which doctrine, and what authoritative evidence showed afterward. “After” does not mean the action caused the result.</p>
    <div className="metric-grid"><div className="metric"><div className="metric-label">Decisions recorded</div><div className="metric-value">{decisions.length}</div></div><div className="metric"><div className="metric-label">Observation windows complete</div><div className="metric-value">{observed.length}</div></div><div className="metric"><div className="metric-label">Sales observed afterward</div><div className="metric-value">{observed.length?sold:"—"}</div><div className="metric-detail">Descriptive association only</div></div></div>
    <div className="action-list" style={{marginTop:18}}>{decisions.map(item=>{const evidence=item.evidenceSnapshot as Evidence;const doctrine=evidence.doctrine;return <article className="action-card" key={item.id}><div><div className="action-score">{item.observationWindowDays}</div><div className="action-category">day window</div></div><div><div className="action-category">{item.decidedAt.toLocaleString()} · {item.operatorId} · {item.doctrineVersion}</div><strong>{operatorDecisionLabel(item.decision as OperatorDecisionValue,item.recommendedAction)}</strong><h3>{item.listing.title}</h3>{doctrine?<><p><strong>{doctrine.interventionSelected?.replaceAll("_"," ")}</strong> · {doctrine.diagnosticFunnelStage} stage</p><p>{doctrine.whyThisActionOutranksAlternatives}</p><div className="metric-detail">Problem Confidence {doctrine.problemConfidence?.score??"unknown"} · Action Confidence {doctrine.actionConfidence?.score??"unknown"} · Comp Confidence {doctrine.compConfidence??"unavailable"} · Sale Likelihood {evidence.saleLikelihood??"unknown"}</div><p><strong>If it failed:</strong> {doctrine.evaluateNextIfInterventionFails}</p></>:<p>Legacy evidence snapshot · health {evidence.healthScore??"unknown"} · {money(evidence.listedExposure)} exposure.</p>}
      {item.outcomes.length===0?<p><strong>What happened?</strong> History is accumulating through the {item.observationWindowDays}-day window.</p>:item.outcomes.map(outcome=><p key={outcome.id}><strong>What happened afterward?</strong> {outcome.saleOccurred?`An authoritative sale was observed${outcome.timeToSaleDays!=null?` ${outcome.timeToSaleDays} days later`:""}${outcome.salePrice!=null?` at ${money(outcome.salePrice)}`:""}.`:`No authoritative sale was observed in the ${outcome.windowDays}-day window.`}</p>)}</div></article>})}</div>
    {decisions.length===0&&<div className="empty-state">No decisions yet. <Link href="/review-session">Start today’s focused review →</Link></div>}
  </main>;
}
