"use client";
import { useState } from "react";
import { parseCsv, type CostImportRow } from "@/lib/cost-basis-import";

type Preview = { rows: Array<CostImportRow & { listingId?: string; listingTitle?: string; status: string; errors: string[] }>; summary: Record<string, number> };
export default function CostBasisCsvImport() {
  const [rows, setRows] = useState<CostImportRow[]>([]); const [fileName,setFileName]=useState(""); const [replaceConflicts,setReplaceConflicts]=useState(false); const [preview, setPreview] = useState<Preview | null>(null); const [state, setState] = useState("idle");
  async function request(mode: "preview" | "apply") { setState(mode === "apply" ? "applying" : "previewing"); const response = await fetch("/api/cost-basis/import", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ mode, rows, sourceFileName:fileName, overwritePolicy:replaceConflicts?"replace":"preserve" }) }); const body = await response.json(); if (response.ok) { setPreview(body); setState(mode === "apply" ? `applied:${body.applied}` : "ready"); } else setState("error"); }
  return <div><input type="file" accept=".csv,text/csv" onChange={async (event) => { const file = event.target.files?.[0]; if (!file) return; setFileName(file.name);setRows(parseCsv(await file.text())); setPreview(null); setState("loaded"); }}/><p>{rows.length} CSV rows loaded. Required identity: listing_id, ebay_item_id, or sku.</p><button className="btn-secondary" onClick={() => request("preview")} disabled={!rows.length || state === "previewing"}>Preview import</button>{preview && <><p>Ready {preview.summary.matched ?? 0} · Conflicts {preview.summary.conflict ?? 0} · Unmatched {preview.summary.unmatched ?? 0} · Ambiguous {preview.summary.ambiguous ?? 0} · Invalid {preview.summary.invalid ?? 0} · Duplicates {preview.summary.duplicate ?? 0}</p>{(preview.summary.conflict??0)>0&&<label className="card-warning" style={{display:"flex",gap:10,alignItems:"center",margin:"12px 0"}}><input type="checkbox" checked={replaceConflicts} onChange={event=>setReplaceConflicts(event.target.checked)}/>Explicitly replace {preview.summary.conflict} existing cost record{preview.summary.conflict===1?"":"s"}</label>}<button className="btn-primary" onClick={() => request("apply")} disabled={(!preview.summary.matched&&!replaceConflicts) || state === "applying"}>Apply {(preview.summary.matched??0)+(replaceConflicts?(preview.summary.conflict??0):0)} verified rows</button><div style={{ maxHeight: 500, overflow: "auto" }}><table style={{ width: "100%" }}><thead><tr><th>Row</th><th>Identity</th><th>Listing</th><th>Status</th><th>Details</th></tr></thead><tbody>{preview.rows.map((row) => <tr key={row.rowNumber}><td>{row.rowNumber}</td><td>{row.listing_id || row.ebay_item_id || row.sku}</td><td>{row.listingTitle ?? "—"}</td><td>{row.status}</td><td>{row.errors.join("; ")}</td></tr>)}</tbody></table></div></>}{state.startsWith("applied:") && <strong>{state.split(":")[1]} cost records applied with import provenance.</strong>}{state === "error" && <strong style={{ color: "var(--danger)" }}>Import failed.</strong>}</div>;
}
