"use client";
import { useState, type MouseEvent } from "react";

type SearchRow = { id: string; title: string; ebayItemId: string; sku: string | null; currentPrice: string; listingStatus: string };
export default function ReconciliationActions({ id, storeId, hasCandidate }: { id: string; storeId: string; hasCandidate: boolean }) {
  const [state, setState] = useState("idle"); const [query, setQuery] = useState(""); const [results, setResults] = useState<SearchRow[]>([]);
  async function act(action: "accept" | "reject", listingId?: string) { setState("saving"); const response = await fetch(`/api/reconciliation/${id}`, { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ action, listingId }) }); setState(response.ok ? "saved" : "error"); if (response.ok) location.reload(); }
  async function search() { setState("searching"); const response = await fetch(`/api/reconciliation/search?storeId=${encodeURIComponent(storeId)}&q=${encodeURIComponent(query)}`); const body = await response.json(); setResults(body.listings ?? []); setState("idle"); }
  function skip(event: MouseEvent<HTMLButtonElement>) { const row = event.currentTarget.closest("tr"); const next = row?.nextElementSibling?.querySelector("button") as HTMLButtonElement | null; row?.remove(); next?.focus(); }
  return <div style={{ display: "grid", gap: 8 }}>{hasCandidate&&<button className="btn-primary" accessKey="a" title="Alt+A" onClick={() => act("accept")}>Yes — match this sale</button>}<details><summary>{hasCandidate?"Show other possibilities":"Search for listing"}</summary><div style={{ display: "flex", gap: 4, marginTop:6 }}><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Card title, item ID, or SKU"/><button onClick={search} disabled={!query || state === "searching"}>Search</button></div>{results.map((row) => <button key={row.id} onClick={() => act("accept", row.id)} style={{ textAlign: "left",marginTop:4 }}>{row.title} · ${Number(row.currentPrice).toFixed(2)} · {row.listingStatus}<br/>Item {row.ebayItemId} · SKU {row.sku ?? "—"}</button>)}</details><button className="btn-tertiary" accessKey="s" title="Alt+S" onClick={skip}>{hasCandidate?"I don’t know — leave for later":"Leave unresolved"}</button>{hasCandidate&&<details><summary>Candidate is wrong</summary><button accessKey="r" title="Alt+R" onClick={() => act("reject")}>This is not the listing</button></details>}{state === "error" && <span style={{ color: "var(--danger)" }}>The match was not saved. Please try again.</span>}</div>;
}
