"use client";
import Image from "next/image";
import { useDeferredValue,useMemo,useState } from "react";
import { opportunitiesForView,searchOpportunitiesForView,type SellerOpportunityView } from "@/lib/seller-opportunity-view";
import { normalizeSnipeOffset,scheduledSubmissionAt,validateBidDraft } from "@/lib/seller-bid-domain";

export type OpportunityReviewRow={id:string;ebayItemId:string;kind:"single"|"lot";title:string;searchText:string;listingUrl:string;imageUrl:string|null;currentBid:number;currency:string;bidCount:number;endTime:string;estimatedCards:number|null;classificationReason:string;isSandbox:boolean;valuation:{status:string;estimatedMarketValue:number|null;projectedGrossProfit:number|null;maxBid:number|null;confidence:string|null}|null;review:{status:"approved"|"passed"|null;maxBid:number|null}};
export type OpportunityView=SellerOpportunityView;
type SortKey="end-asc"|"title-asc"|"title-desc"|"price-asc"|"price-desc"|"bids-asc"|"bids-desc"|"profit-desc";
const usd=(value:number|null,currency="USD")=>value==null?"—":new Intl.NumberFormat("en-US",{style:"currency",currency}).format(value);
function remaining(end:string,now:number){const ms=new Date(end).getTime()-now;if(ms<=0)return"Ended";const minutes=Math.floor(ms/60000),hours=Math.floor(minutes/60),days=Math.floor(hours/24);return days?`${days}d ${hours%24}h`:hours?`${hours}h ${minutes%60}m`:`${minutes}m`;}

export default function SellerOpportunityReview({initialRows,view,defaultSnipeOffsetSeconds=7}:{initialRows:OpportunityReviewRow[];view:OpportunityView;defaultSnipeOffsetSeconds?:number}){
  const initialViewRows=opportunitiesForView(initialRows,view);
  const defaultSort:SortKey=view==="singles"&&initialViewRows.some(row=>row.valuation?.projectedGrossProfit!=null)?"profit-desc":"end-asc";
  const [rows,setRows]=useState(initialRows),[status,setStatus]=useState("all"),[bidFilter,setBidFilter]=useState("all"),[sort,setSort]=useState<SortKey>(defaultSort),[query,setQuery]=useState(""),[now]=useState(()=>Date.now());
  const [maxBids,setMaxBids]=useState<Record<string,string>>(()=>Object.fromEntries(initialRows.map(row=>[row.id,String(row.review.maxBid??(row.kind==="single"?row.valuation?.maxBid:null)??"")]))),[snipeOffsets,setSnipeOffsets]=useState<Record<string,string>>({});
  const deferredQuery=useDeferredValue(query.trim().toLocaleLowerCase());
  const viewRows=useMemo(()=>opportunitiesForView(rows,view),[rows,view]);
  const visible=useMemo(()=>searchOpportunitiesForView(rows,view,deferredQuery).filter(row=>(status==="all"||(status==="valued"?row.valuation?.estimatedMarketValue!=null:row.valuation?.estimatedMarketValue==null))&&(bidFilter==="all"||(bidFilter==="zero"?row.bidCount===0:row.bidCount>=1))).sort((a,b)=>{const ending=new Date(a.endTime).getTime()-new Date(b.endTime).getTime();switch(sort){case"title-asc":return a.title.localeCompare(b.title)||ending;case"title-desc":return b.title.localeCompare(a.title)||ending;case"price-asc":return a.currentBid-b.currentBid||ending;case"price-desc":return b.currentBid-a.currentBid||ending;case"bids-asc":return a.bidCount-b.bidCount||ending;case"bids-desc":return b.bidCount-a.bidCount||ending;case"profit-desc":return(b.valuation?.projectedGrossProfit??-Infinity)-(a.valuation?.projectedGrossProfit??-Infinity)||ending;default:return ending;}}),[rows,view,status,bidFilter,sort,deferredQuery]);
  async function review(row:OpportunityReviewRow,decision:"approved"|"passed"){const input=document.getElementById(`max-${row.id}`) as HTMLInputElement|null,maxBid=input?.value?Number(input.value):null;const response=await fetch(`/api/seller-opportunities/${row.id}/review`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({decision,maxBid})});if(!response.ok){alert("Review could not be saved.");return;}setRows(current=>current.map(item=>item.id===row.id?{...item,review:{status:decision,maxBid}}:item));}
  async function schedule(row:OpportunityReviewRow,maxBid:number|null,offset:number){if(!maxBid||!confirm(`Schedule Sandbox proxy bid with a maximum of ${usd(maxBid,row.currency)}?`))return;const response=await fetch(`/api/seller-opportunities/${row.id}/schedule`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({operatorMaxBid:maxBid,snipeOffsetSeconds:offset})});const body=await response.json();if(!response.ok){alert(body.error??"Bid could not be scheduled");return;}window.location.href="/scheduled-bids";}
  const showSingles=view!=="lots",showType=view==="all";
  const viewLabel=view==="singles"?"Singles":view==="lots"?"Lots":"All";
  const sortButton=(label:string,asc:SortKey,desc:SortKey)=><button type="button" className="column-sort" aria-label={`Sort ${label}`} aria-pressed={sort===asc||sort===desc} onClick={()=>setSort(current=>current===asc?desc:asc)}>{label}<span aria-hidden="true">{sort===asc?" ↑":sort===desc?" ↓":" ↕"}</span></button>;
  return <><div className="opportunity-controls search-controls"><label className="opportunity-search"><span>Search {viewLabel}</span><input type="search" value={query} onChange={event=>setQuery(event.target.value)} placeholder="Player, year, set, parallel, card number…" autoComplete="off"/></label><button type="button" className="btn-secondary search-clear" onClick={()=>setQuery("")} disabled={!query}>Clear</button><strong className="match-count">{visible.length} of {viewRows.length} {viewLabel}</strong>{showSingles?<label>Comp status<select value={status} onChange={event=>setStatus(event.target.value)}><option value="all">All</option><option value="valued">Valued</option><option value="research">Needs Research</option></select></label>:null}<label>Bid count<select value={bidFilter} onChange={event=>setBidFilter(event.target.value)}><option value="all">All</option><option value="zero">0 bids</option><option value="one-plus">1+ bids</option></select></label><label>Sort<select value={sort} onChange={event=>setSort(event.target.value as SortKey)}><option value="end-asc">Ending soonest</option><option value="title-asc">Title A → Z</option><option value="title-desc">Title Z → A</option><option value="price-asc">Price low → high</option><option value="price-desc">Price high → low</option><option value="bids-asc">Bids low → high</option><option value="bids-desc">Bids high → low</option>{showSingles?<option value="profit-desc">Projected profit</option>:null}</select></label></div>
  <div className={`review-list review-list-${view}`} role="table" aria-label={`${viewLabel} seller opportunities`}>
    <div className="review-column-header" role="row"><div role="columnheader">{sortButton("Listing","title-asc","title-desc")}</div><div role="columnheader">{sortButton("Price","price-asc","price-desc")}</div><div role="columnheader">{sortButton("Bids","bids-asc","bids-desc")}</div><div role="columnheader">Ends</div>{showType?<div role="columnheader">Type</div>:null}<div role="columnheader">{showSingles?"Comp / economics":"Lot opportunity"}</div><div role="columnheader">Bid plan</div><div role="columnheader">Actions</div></div>
    <div className="review-listing-rows" role="rowgroup">{visible.map(row=>{const maxBidText=maxBids[row.id]??"",maxBid=maxBidText===""?null:Number(maxBidText),offsetText=snipeOffsets[row.id]??String(defaultSnipeOffsetSeconds),offset=normalizeSnipeOffset(Number(offsetText),defaultSnipeOffsetSeconds),scheduledAt=scheduledSubmissionAt(row.endTime,offset),draft=validateBidDraft({maxBid,auctionEndAt:row.endTime,now:new Date(now)}),executionBlocked="eBay Offer API production access is not enabled for this application";return <div role="row" key={row.id} className={`review-listing-row ${row.review.status?`review-${row.review.status}`:""}`}>
      <div className="review-cell"><div className="listing-identity">{row.imageUrl?<Image src={row.imageUrl} alt="" width={72} height={72} sizes="72px" className="listing-thumb"/>:<div className="listing-thumb placeholder">No image</div>}<div><a href={row.listingUrl} target="_blank" rel="noreferrer" className="listing-title">{row.title}</a><div className="listing-meta">eBay {row.ebayItemId} · <a href={row.listingUrl} target="_blank" rel="noreferrer">View listing ↗</a></div>{row.kind==="lot"?<div className="listing-meta">{row.estimatedCards?`Estimated quantity: ~${row.estimatedCards} cards`:"Estimated quantity unavailable"}</div>:null}</div></div></div>
      <div className="review-cell numeric-cell"><strong>{usd(row.currentBid,row.currency)}</strong></div>
      <div className="review-cell numeric-cell"><strong>{row.bidCount}</strong></div>
      <div className="review-cell end-cell"><strong>{new Intl.DateTimeFormat("en-US",{month:"short",day:"numeric",hour:"numeric",minute:"2-digit",second:"2-digit",timeZone:"America/Chicago",timeZoneName:"short"}).format(new Date(row.endTime))}</strong><span>{remaining(row.endTime,now)}</span></div>
      {showType?<div className="review-cell"><span className={`badge ${row.kind==="lot"?"badge-info":"badge-neutral"}`}>{row.kind.toUpperCase()}</span>{row.kind==="lot"?<div className="listing-meta">{row.estimatedCards?`~${row.estimatedCards} cards`:"Qty unknown"}</div>:null}</div>:null}
      {showSingles?<div className="review-cell">{row.kind==="lot"?<div className="lot-opportunity-placeholder"><strong>Lot review</strong><span>Opportunity score pending</span><span>Why interesting pending</span></div>:row.valuation?.estimatedMarketValue!=null?<><span className="badge badge-success">{row.valuation.status}</span><div className="economics-grid"><span>Value <b>{usd(row.valuation.estimatedMarketValue)}</b></span><span>Profit <b>{usd(row.valuation.projectedGrossProfit)}</b></span><span>Recommended Max Bid <b>{usd(row.valuation.maxBid)}</b></span></div></>:<><span className="badge badge-warning">Needs Research</span><div className="listing-meta">No defensible sold valuation</div></>}</div>:<div className="review-cell"><div className="lot-opportunity-placeholder"><strong>Lot Opportunity Score</strong><span>Pending</span><strong>Why Interesting</strong><span>Lot scoring logic not yet enabled</span></div></div>}
      <div className="review-cell bid-plan"><label className="max-bid"><span>Your Max Bid</span><input id={`max-${row.id}`} type="number" min="0" step="0.01" value={maxBidText} onChange={event=>setMaxBids(current=>({...current,[row.id]:event.target.value}))} placeholder="0.00"/></label><label className="max-bid"><span>Snipe offset (seconds)</span><input type="number" min="1" max="300" step="1" value={offsetText} onChange={event=>setSnipeOffsets(current=>({...current,[row.id]:event.target.value}))}/></label><div className="bid-timing"><span>Ends {new Date(row.endTime).toLocaleString("en-US",{timeZone:"America/Chicago",timeZoneName:"short"})}</span><span>Submit {scheduledAt?new Date(scheduledAt).toLocaleString("en-US",{timeZone:"America/Chicago",timeZoneName:"short"}):"—"}</span><span>Status <b>{row.review.status==="passed"?"Cancelled":"Draft"}</b></span></div></div>
      <div className="review-cell"><div className="review-buttons bid-action-buttons"><button type="button" className="approve-button" disabled={!row.isSandbox||!draft.ok} title={row.isSandbox?undefined:executionBlocked} onClick={()=>schedule(row,maxBid,offset)}>Approve &amp; Schedule</button><button type="button" className="pass-button" aria-pressed={row.review.status==="passed"} onClick={()=>review(row,"passed")}>Pass</button></div><div className="listing-meta bid-blocked">{row.isSandbox?(draft.ok?"Sandbox schedule ready":draft.reason):"BLOCKED — Sandbox items only"}</div>{row.review.status?<div className="listing-meta review-saved">Saved: {row.review.status}</div>:null}</div>
    </div>})}</div>
  </div></>;
}
