import type { InventoryHealth } from "@/lib/inventory-health";
import type { DoctrineDecision } from "@/lib/inventory-decision-doctrine";

export type ActionBrief={diagnosis:string;recommendation:string;steps:string[];evidence:string[];approvalMeaning:string;guardrail:string};
const money=(value:number)=>new Intl.NumberFormat("en-US",{style:"currency",currency:"USD"}).format(value);
export function actionEffort(action:string){if(/PRICE|OFFER/.test(action))return"About 2 minutes";if(/TITLE|DISCOVERABILITY|SELL_SIMILAR/.test(action))return"About 5 minutes";if(/COST/.test(action))return"About 2 minutes";return"About 3 minutes";}
export function actionConsequence(action:string){if(/OFFER/.test(action))return"Legends records your plan. It does not send an offer or change the listing.";if(/PRICE/.test(action))return"Legends records your plan; it does not change the eBay price.";if(/TITLE|SELL_SIMILAR|EXIT/.test(action))return"Legends records your plan; it does not edit, end, relist, or delete the eBay listing.";if(/RESTOCK/.test(action))return"Legends records a sourcing review; it does not purchase inventory.";if(/COST/.test(action))return"Legends records the decision; enter only costs you actually know.";return"Legends records the decision and observes authoritative outcomes without changing eBay.";}

export function buildActionBrief(row:InventoryHealth&{doctrine:DoctrineDecision}):ActionBrief{
  const d=row.doctrine;const common={diagnosis:d.whyThisActionOutranksAlternatives,evidence:d.signalsEvaluated.map(signal=>`${signal.signal}: ${signal.value??"unavailable"} (${signal.quality})`),guardrail:actionConsequence(d.interventionSelected)};
  switch(d.interventionSelected){
    case"LOWER_PRICE":case"RAISE_PRICE":return{...common,recommendation:`Change the eBay Buy It Now price from ${money(row.currentPrice)} to ${money(row.suggestedPrice!)}.`,steps:["Open the live eBay listing.",`Change only the Buy It Now price to ${money(row.suggestedPrice!)}.`,"Leave other fields unchanged and let Legends observe the defined window."],approvalMeaning:`You intend to apply the doctrine-supported ${d.interventionSelected==="LOWER_PRICE"?"lower":"higher"} price manually.`};
    case"OPTIMIZE_TITLE":return{...common,recommendation:d.proposedTitle?`Change the title from “${row.title}” to “${d.proposedTitle}”.`:`Verified title defects exist, but Legends cannot produce a safe 80-character replacement without removing information.`,steps:d.proposedTitle?["Open the live listing.",`Replace the title exactly with: ${d.proposedTitle}`,"Leave category, specifics, price, and all other fields unchanged."]:["Open the live listing.",`Review only these authoritative omissions: ${d.verifiedTitleDefects.join("; ")}.`,"Do not approve a title edit until an exact non-destructive replacement is available."],approvalMeaning:d.proposedTitle?"You intend to apply this exact verified title replacement manually.":"You acknowledge the defect, but no title change is approved."};
    case"OFFER_CONVERSION":return{...common,recommendation:"Use eBay’s eligible-buyer offer workflow only after confirming known margin supports your chosen amount.",steps:["Open the live listing and check offer eligibility.","Verify real cost, fees, and postage before choosing an amount.","Do not send an offer if the floor is unknown."],approvalMeaning:"You intend to review a manual conversion offer; no amount or offer is approved by Legends."};
    case"END_SELL_SIMILAR":return{...common,recommendation:"End the stale listing and create one Sell Similar replacement after verifying every carried-forward fact.",steps:["Open the live listing and verify there are no active bids or other constraints.","Use End, then Sell Similar manually.","Recheck category, condition, title, item specifics, photos, shipping, and price before publishing."],approvalMeaning:"You intend to perform one manual End & Sell Similar refresh; Legends will not execute it."};
    case"EXIT_REVIEW":return{...common,recommendation:"Stop repeated relisting and perform a manual exit/disposition review.",steps:["Verify the prior intervention history and current evidence.","Choose keep, lot, consign, or other disposition using real economics.","Do not write off or dispose of inventory based on this recommendation alone."],approvalMeaning:"You intend to review disposition; no deletion, write-off, or marketplace action is approved."};
    case"RESTOCK_REVIEW":return{...common,recommendation:"Investigate replenishment only if a real acquisition cost supports known margin.",steps:["Check actual replacement availability and cost.","Compare real cost with authoritative velocity and known margin.","Do not buy when cost or margin is unknown."],approvalMeaning:"You intend to investigate replenishment; no purchase is approved."};
    case"ENTER_COST":return{...common,recommendation:"Enter the real per-unit cost components you can document.",steps:["Open Cost Basis.","Enter only components supported by your records.","Leave every unknown component blank."],approvalMeaning:"You intend to enter documented costs; Legends infers none."};
    case"LEARNING":return{...common,recommendation:"Leave the listing unchanged through the learning gate.",steps:["Make no marketplace change from this recommendation.","Allow the defined observation period to complete.","Reassess discovery afterward."],approvalMeaning:"You agree to observe without changing the listing."};
    case"LEAVE_ALONE":return{...common,recommendation:"Leave the listing unchanged and continue observing.",steps:["Make no marketplace change.","Reassess only when new funnel evidence arrives."],approvalMeaning:"You agree that no intervention is currently justified."};
    case"MORE_EVIDENCE":return{...common,recommendation:"Do not intervene until the missing evidence identified by the doctrine is available.",steps:["Review the unavailable signals and problems below.","Collect only authoritative or verified evidence.","Run the doctrine again before changing price, title, or listing state."],approvalMeaning:"You agree to defer intervention rather than manufacture a recommendation."};
  }
}
