import {Prisma,type EbayActionExecution} from "@prisma/client";
import {prisma} from "./prisma.ts";
import {findEligibleItems,sendOfferToInterestedBuyers,type SellerOfferResponse} from "./ebay-negotiation.ts";
import {getItem,getValidAccessToken,type EbayListingItem} from "./ebay.ts";
import {summarizeKnownCost} from "./profitability.ts";

export const SELLER_OFFER_POLICY_VERSION="seller-offer-canary-v1.0.0";
export const SELLER_OFFER_DISCOUNT_PCT=5;
export const SELLER_OFFER_FRESHNESS_MS=24*60*60*1000;
const ACTIVE_EXECUTION_STATUSES=["approved","executing","partial_failure","manual_reconciliation_required"];
const json=(value:unknown)=>JSON.parse(JSON.stringify(value)) as Prisma.InputJsonValue;
const cents=(value:number)=>Math.round(value*100)/100;
const livePrice=(item:EbayListingItem)=>{const value=item.SellingStatus?.CurrentPrice;if(typeof value==="number")return value;if(typeof value==="string")return Number(value);if(value&&typeof value==="object")return Number(value["#text"]);return NaN;};
const isActive=(item:EbayListingItem)=>String(item.SellingStatus?.ListingStatus??"").toLowerCase()==="active";

export function calculateSellerOffer(listedPrice:number,discountPct=SELLER_OFFER_DISCOUNT_PCT){if(!Number.isFinite(listedPrice)||listedPrice<=0||!Number.isFinite(discountPct)||discountPct<=0||discountPct>SELLER_OFFER_DISCOUNT_PCT)throw new Error("Seller offer exceeds the governed discount policy");const proposedPrice=Math.ceil(listedPrice*(1-discountPct/100)*100-1e-9)/100;return{listedPrice:cents(listedPrice),proposedPrice,discountPct:cents((listedPrice-proposedPrice)/listedPrice*100),concession:cents(listedPrice-proposedPrice)};}
export function validateSellerOfferApproval(input:{listedPrice:number;proposedPrice:number;knownUnitCost:number|null;costComplete:boolean;overrideAcknowledged:boolean}){const blockers:string[]=[];const discount=(input.listedPrice-input.proposedPrice)/input.listedPrice*100;if(!Number.isFinite(discount)||discount<=0||discount>SELLER_OFFER_DISCOUNT_PCT+.0001)blockers.push("Offer discount exceeds the governed five-percent policy");if(input.costComplete&&input.knownUnitCost!=null&&input.proposedPrice<input.knownUnitCost*1.2)blockers.push("Offer fails the existing 20% known-cost margin guardrail");if((!input.costComplete||input.knownUnitCost==null)&&!input.overrideAcknowledged)blockers.push("Explicit COST BASIS UNKNOWN operator acknowledgement is required");return blockers;}
function costSummary(cost:null|{unitAcquisitionCost:Prisma.Decimal|null;unitGradingCost:Prisma.Decimal|null;unitSuppliesCost:Prisma.Decimal|null;unitOutboundPostageCost:Prisma.Decimal|null;unitOtherCost:Prisma.Decimal|null}){return summarizeKnownCost({acquisition:cost?.unitAcquisitionCost==null?null:Number(cost.unitAcquisitionCost),grading:cost?.unitGradingCost==null?null:Number(cost.unitGradingCost),supplies:cost?.unitSuppliesCost==null?null:Number(cost.unitSuppliesCost),postage:cost?.unitOutboundPostageCost==null?null:Number(cost.unitOutboundPostageCost),other:cost?.unitOtherCost==null?null:Number(cost.unitOtherCost)});}
export type GovernedSellerOfferProposal={listingId:string;ebayItemId:string;title:string;currentPrice:number;proposedPrice:number;discountPct:number;concession:number;eligibilityObservedAt:string;knownUnitCost:number|null;costComplete:boolean;estimatedGrossSpread:number|null;estimatedGrossMarginPct:number|null;overrideRequired:boolean;ready:boolean;blockers:string[]};

export async function buildGovernedSellerOfferProposal(listingId:string,now=new Date()):Promise<GovernedSellerOfferProposal|null>{
  const listing=await prisma.listing.findUnique({where:{id:listingId},include:{store:true,costBasis:true,ebayActionExecutions:{where:{status:{in:ACTIVE_EXECUTION_STATUSES}},select:{id:true,action:true,status:true}}}});if(!listing)return null;
  const blockers:string[]=[];if(listing.listingStatus!=="active")blockers.push("Listing is not active in authoritative inventory");if(!/^\d+$/.test(listing.ebayItemId))blockers.push("Authoritative numeric eBay Item ID is unavailable");if(listing.ebayActionExecutions.length)blockers.push("Another governed action is active for this listing");
  const {accessToken}=await getValidAccessToken(listing.store);const [eligible,live]=await Promise.all([findEligibleItems(accessToken),getItem(accessToken,listing.ebayItemId)]);const eligibility=eligible.get(listing.ebayItemId);if(!eligibility)blockers.push("eBay no longer reports this listing as Negotiation eligible");if(!isActive(live))blockers.push("Live provider listing is not active");const currentPrice=livePrice(live);if(!Number.isFinite(currentPrice)||currentPrice<=0)blockers.push("Live provider price is unavailable");
  const offer=calculateSellerOffer(currentPrice);const costs=costSummary(listing.costBasis);const economicsKnown=costs.complete&&costs.knownUnitCost!=null;const spread=economicsKnown?cents(offer.proposedPrice-costs.knownUnitCost!):null;const margin=economicsKnown&&offer.proposedPrice>0?cents(spread!/offer.proposedPrice*100):null;if(economicsKnown&&offer.proposedPrice<costs.knownUnitCost!*1.2)blockers.push("The offer fails the existing 20% known-cost margin guardrail");
  return{listingId:listing.id,ebayItemId:listing.ebayItemId,title:live.Title,currentPrice:offer.listedPrice,proposedPrice:offer.proposedPrice,discountPct:offer.discountPct,concession:offer.concession,eligibilityObservedAt:eligibility?.observedAt??now.toISOString(),knownUnitCost:costs.knownUnitCost,costComplete:costs.complete,estimatedGrossSpread:spread,estimatedGrossMarginPct:margin,overrideRequired:!economicsKnown,ready:blockers.length===0,blockers};
}

async function appendEvent(executionId:string,type:string,snapshot:unknown){const latest=await prisma.ebayActionExecutionEvent.findFirst({where:{executionId},orderBy:{sequence:"desc"},select:{sequence:true}});return prisma.ebayActionExecutionEvent.create({data:{executionId,sequence:(latest?.sequence??0)+1,type,snapshot:json(snapshot)}});}
export async function createGovernedSellerOfferExecution(input:{listingId:string;operatorId:string;reviewedPrice:number;costBasisOverrideAcknowledged:boolean}){const proposal=await buildGovernedSellerOfferProposal(input.listingId);if(!proposal?.ready)throw new Error(proposal?.blockers.join("; ")||"Seller offer is not approval-ready");if(Math.abs(proposal.proposedPrice-input.reviewedPrice)>0.005)throw new Error("The reviewed offer amount changed; review the refreshed proposal");const policyBlockers=validateSellerOfferApproval({listedPrice:proposal.currentPrice,proposedPrice:proposal.proposedPrice,knownUnitCost:proposal.knownUnitCost,costComplete:proposal.costComplete,overrideAcknowledged:input.costBasisOverrideAcknowledged});if(policyBlockers.length)throw new Error(policyBlockers.join("; "));const decision=await prisma.operatorDecision.create({data:{listingId:proposal.listingId,operatorId:input.operatorId,recommendedAction:"SEND_OFFER",doctrineVersion:SELLER_OFFER_POLICY_VERSION,decision:"follow_recommendation",operatorAdjustedValue:proposal.proposedPrice,beforeState:json({title:proposal.title,price:proposal.currentPrice,listingStatus:"active",ebayItemId:proposal.ebayItemId}),evidenceSnapshot:json({source:"ebay-negotiation",proposal,costBasisOverrideAcknowledged:input.costBasisOverrideAcknowledged,capturedAt:new Date().toISOString()}),observationWindowDays:7}});const listing=await prisma.listing.findUniqueOrThrow({where:{id:proposal.listingId},select:{storeId:true}});const execution=await prisma.ebayActionExecution.create({data:{listingId:proposal.listingId,storeId:listing.storeId,decisionId:decision.id,operatorId:input.operatorId,action:"SEND_OFFER",doctrineVersion:SELLER_OFFER_POLICY_VERSION,idempotencyKey:`${decision.id}:${SELLER_OFFER_POLICY_VERSION}:SEND_OFFER`,oldEbayItemId:proposal.ebayItemId,beforeState:json({title:proposal.title,price:proposal.currentPrice,listingStatus:"active",ebayItemId:proposal.ebayItemId}),proposedState:json({offerPrice:proposal.proposedPrice,discountPct:proposal.discountPct,quantity:1}),evidenceSnapshot:json({source:"ebay-negotiation",proposal,costBasisOverrideAcknowledged:input.costBasisOverrideAcknowledged})}});await appendEvent(execution.id,"approved",{operatorId:input.operatorId,proposal,costBasisOverrideAcknowledged:input.costBasisOverrideAcknowledged});return execution;}

export type SellerOfferExecutionProvider={getItem(accessToken:string,itemId:string):Promise<EbayListingItem>;findEligible(accessToken:string):ReturnType<typeof findEligibleItems>;send(accessToken:string,input:{listingId:string;price:number;currency?:string;message?:string}):Promise<SellerOfferResponse>};
export const sellerOfferProvider:SellerOfferExecutionProvider={getItem,findEligible:findEligibleItems,send:sendOfferToInterestedBuyers};
export async function executeGovernedSellerOffer(executionId:string,operatorId:string,provider:SellerOfferExecutionProvider=sellerOfferProvider,options:{writesEnabled?:boolean}={}){let execution=await prisma.ebayActionExecution.findUniqueOrThrow({where:{id:executionId},include:{store:true}});if(execution.action!=="SEND_OFFER"||execution.operatorId!==operatorId)throw new Error("A matching seller-offer approval is required");if(execution.status==="verified")return execution;if(execution.status==="executing"||execution.status==="manual_reconciliation_required")throw new Error("Offer execution is indeterminate and must not be retried automatically");if(execution.status!=="approved")throw new Error("Seller offer is not in an executable state");
  const proposed=execution.proposedState as Record<string,unknown>,before=execution.beforeState as Record<string,unknown>,offer=calculateSellerOffer(Number(before.price));if(Math.abs(offer.proposedPrice-Number(proposed.offerPrice))>0.005||Number(proposed.discountPct)>SELLER_OFFER_DISCOUNT_PCT)throw new Error("Approved offer exceeds or no longer matches policy");const {accessToken}=await getValidAccessToken(execution.store);const live=await provider.getItem(accessToken,execution.oldEbayItemId);if(!isActive(live))throw new Error("Live listing is no longer active");if(live.Title!==String(before.title)||Math.abs(livePrice(live)-Number(before.price))>0.005)throw new Error("Live listing title or price changed after approval");const eligible=await provider.findEligible(accessToken);if(!eligible.has(execution.oldEbayItemId))throw new Error("eBay no longer reports this listing as Negotiation eligible");const [conflicting,currentCost]=await Promise.all([prisma.ebayActionExecution.count({where:{listingId:execution.listingId,id:{not:execution.id},status:{in:ACTIVE_EXECUTION_STATUSES}}}),prisma.listingCostBasis.findUnique({where:{listingId:execution.listingId}})]);if(conflicting)throw new Error("Another governed action is active for this listing");const costs=costSummary(currentCost);if(costs.complete&&costs.knownUnitCost!=null&&Number(proposed.offerPrice)<costs.knownUnitCost*1.2)throw new Error("Current known economics fail the existing 20% known-cost margin guardrail");await appendEvent(execution.id,"server_revalidated",{itemId:live.ItemID,title:live.Title,price:livePrice(live),eligibilityObservedAt:eligible.get(execution.oldEbayItemId)?.observedAt,discountPct:proposed.discountPct,knownUnitCost:costs.complete?costs.knownUnitCost:null,overrideAcknowledged:Boolean((execution.evidenceSnapshot as Record<string,unknown>).costBasisOverrideAcknowledged)});
  if(!(options.writesEnabled??process.env.EBAY_SELLER_OFFER_WRITES_ENABLED==="explicitly-approved-canary")){await appendEvent(execution.id,"production_write_blocked",{reason:"Seller-offer canary write approval is not enabled"});throw new Error("Seller-offer writes remain locked pending separate canary approval");}
  execution=await prisma.ebayActionExecution.update({where:{id:execution.id},data:{status:"executing"},include:{store:true}});await appendEvent(execution.id,"execution_started",{action:"SEND_OFFER",offerPrice:proposed.offerPrice});try{const response=await provider.send(accessToken,{listingId:execution.oldEbayItemId,price:Number(proposed.offerPrice)});const offers=response.offers??[];if(!offers.length||offers.some(item=>!item.offerId||item.offerStatus!=="PENDING"||!item.offeredItems?.some(offered=>offered.listingId===execution.oldEbayItemId)))throw new Error("Provider response did not reconcile to a pending offer for the approved listing");await appendEvent(execution.id,"provider_accepted",response);await appendEvent(execution.id,"provider_verified",{listingId:execution.oldEbayItemId,offerPrice:proposed.offerPrice,offerCount:offers.length,offers:offers.map(item=>({offerId:item.offerId,status:item.offerStatus,creationDate:item.creationDate,revision:item.revision}))});return prisma.ebayActionExecution.update({where:{id:execution.id},data:{status:"verified",providerVerifiedAt:new Date()}});}catch(error){await appendEvent(execution.id,"manual_reconciliation_required",{message:error instanceof Error?error.message:"Provider offer result is unknown",automaticRetry:false});await prisma.ebayActionExecution.update({where:{id:execution.id},data:{status:"manual_reconciliation_required"}});throw error;}}

export async function recordSellerOfferSkip(listingId:string,operatorId:string){const proposal=await buildGovernedSellerOfferProposal(listingId);if(!proposal)throw new Error("Seller offer is unavailable");return prisma.operatorDecision.create({data:{listingId,operatorId,recommendedAction:"SEND_OFFER",doctrineVersion:SELLER_OFFER_POLICY_VERSION,decision:"skip",beforeState:json({title:proposal.title,price:proposal.currentPrice,ebayItemId:proposal.ebayItemId}),evidenceSnapshot:json({source:"ebay-negotiation",proposal,capturedAt:new Date().toISOString()}),observationWindowDays:7}});}
