import { Prisma } from "@prisma/client";
import { prisma } from "@/lib/prisma";
import { buildInventoryPortfolio, calculateInventoryHealth } from "@/lib/inventory-health";
import { evaluateInventoryDecisionDoctrine, type DoctrineAction } from "@/lib/inventory-decision-doctrine";
import { summarizeKnownCost } from "@/lib/profitability";

const DAY = 86_400_000;
type SaleRollup={listingId:string;units7:bigint;units30:bigint;units90:bigint;sales30:Prisma.Decimal;lastSale:Date|null};
type TrafficBaseline={listingId:string;views:number;capturedAt:Date};
const doctrineActions = new Set<DoctrineAction>(["LEARNING","OPTIMIZE_TITLE","LOWER_PRICE","RAISE_PRICE","OFFER_CONVERSION","END_SELL_SIMILAR","EXIT_REVIEW","MORE_EVIDENCE","LEAVE_ALONE","RESTOCK_REVIEW","ENTER_COST"]);

export async function loadInventoryHealth(now=new Date(),listingId?:string){
  const since7=new Date(now.getTime()-7*DAY),since30=new Date(now.getTime()-30*DAY),since90=new Date(now.getTime()-90*DAY);
  const [listings,sales,trafficBaselines]=await Promise.all([
    prisma.listing.findMany({where:{listingStatus:"active",...(listingId?{id:listingId}:{})},select:{id:true,title:true,ebayItemId:true,itemSpecifics:true,authoritativeSource:true,authoritativeObservedAt:true,categoryId:true,listingFormat:true,currentPrice:true,quantity:true,views:true,watchers:true,startTime:true,costBasis:true,operatorDecisions:{orderBy:{decidedAt:"desc"},take:5,select:{recommendedAction:true,evidenceSnapshot:true}},recommendations:{where:{status:"pending",type:{in:["raise-price","lower-price"]},suggestedPrice:{not:null},confidence:{gte:60}},orderBy:{generatedAt:"desc"},take:1,select:{type:true,suggestedPrice:true,confidence:true}}}}),
    prisma.$queryRaw<SaleRollup[]>(Prisma.sql`SELECT "listingId",COALESCE(SUM(quantity) FILTER(WHERE "soldAt">=${since7}),0)::bigint AS "units7",COALESCE(SUM(quantity) FILTER(WHERE "soldAt">=${since30}),0)::bigint AS "units30",COALESCE(SUM(quantity) FILTER(WHERE "soldAt">=${since90}),0)::bigint AS "units90",COALESCE(SUM(price*quantity) FILTER(WHERE "soldAt">=${since30}),0) AS "sales30",MAX("soldAt") AS "lastSale" FROM "SaleEvent" WHERE "listingId" IS NOT NULL AND provider='ebay-fulfillment' AND status<>'cancelled' ${listingId?Prisma.sql`AND "listingId"=${listingId}`:Prisma.empty} GROUP BY "listingId"`),
    prisma.$queryRaw<TrafficBaseline[]>(Prisma.sql`SELECT DISTINCT ON ("listingId") "listingId",views,"capturedAt" FROM "ListingSnapshot" WHERE "capturedAt">=${since30} ${listingId?Prisma.sql`AND "listingId"=${listingId}`:Prisma.empty} ORDER BY "listingId","capturedAt" ASC`),
  ]);
  const salesById=new Map(sales.map(row=>[row.listingId,row]));const trafficById=new Map(trafficBaselines.map(row=>[row.listingId,row]));
  const rows=listings.map(listing=>{
    const sale=salesById.get(listing.id),traffic=trafficById.get(listing.id);const observationDays=traffic?Math.max(0,Math.floor((now.getTime()-traffic.capturedAt.getTime())/DAY)):null;const views30=traffic?Math.max(0,listing.views-traffic.views):null;
    const cost=listing.costBasis?summarizeKnownCost({acquisition:listing.costBasis.unitAcquisitionCost==null?null:Number(listing.costBasis.unitAcquisitionCost),grading:listing.costBasis.unitGradingCost==null?null:Number(listing.costBasis.unitGradingCost),supplies:listing.costBasis.unitSuppliesCost==null?null:Number(listing.costBasis.unitSuppliesCost),postage:listing.costBasis.unitOutboundPostageCost==null?null:Number(listing.costBasis.unitOutboundPostageCost),other:listing.costBasis.unitOtherCost==null?null:Number(listing.costBasis.unitOtherCost)}):null;const recommendation=listing.recommendations[0];const suggested=recommendation?.suggestedPrice==null?null:Number(recommendation.suggestedPrice);
    const health=calculateInventoryHealth({id:listing.id,title:listing.title,ebayItemId:listing.ebayItemId,ageDays:listing.startTime?Math.max(0,Math.floor((now.getTime()-listing.startTime.getTime())/DAY)):null,daysSinceSale:sale?.lastSale?Math.max(0,Math.floor((now.getTime()-sale.lastSale.getTime())/DAY)):null,views:listing.views,views30,trafficObservationDays:observationDays,watchers:listing.watchers,quantity:listing.quantity,currentPrice:Number(listing.currentPrice),units7:Number(sale?.units7??0),units30:Number(sale?.units30??0),units90:Number(sale?.units90??0),salesDollars30:Number(sale?.sales30??0),knownUnitCost:cost?.knownUnitCost??null,knownCapital:cost?.knownUnitCost==null?null:cost.knownUnitCost*listing.quantity,costComplete:cost?.complete??null,supportedPriceAction:recommendation?.type==="raise-price"||recommendation?.type==="lower-price"?recommendation.type:null,suggestedPrice:suggested,marketValue:suggested,compConfidence:recommendation?.confidence??null});
    const priorInterventions=listing.operatorDecisions.flatMap(decision=>{const snapshot=decision.evidenceSnapshot as Record<string,unknown>;const doctrine=snapshot?.doctrine as Record<string,unknown>|undefined;const value=String(doctrine?.interventionSelected??decision.recommendedAction);return doctrineActions.has(value as DoctrineAction)?[value as DoctrineAction]:[];});
    const doctrine=evaluateInventoryDecisionDoctrine({title:health.title,ageDays:health.ageDays,views:health.viewsForDecision,trafficEvidence:health.trafficEvidence,trafficObservationDays:health.trafficObservationDays,watchers:health.watchers,units30:health.units30,units90:health.units90,quantity:health.quantity,currentPrice:health.currentPrice,knownUnitCost:health.knownUnitCost,supportedPriceAction:health.supportedPriceAction,suggestedPrice:health.suggestedPrice,compConfidence:health.compConfidence,itemSpecifics:listing.itemSpecifics,authoritativeListingDetails:listing.authoritativeSource==="ebay-trading-get-item"&&listing.authoritativeObservedAt!=null,categoryId:listing.categoryId,listingFormat:listing.listingFormat,priorInterventions,saleLikelihood:health.saleLikelihood});
    return{...health,doctrine};
  });
  return{generatedAt:now,rows,portfolio:buildInventoryPortfolio(rows)};
}
