import { parseCardIdentity } from "./comp-validation/identity.ts";

export const INVENTORY_DECISION_DOCTRINE_VERSION = "inventory-doctrine-v1.1.1";

export type DoctrineAction = "LEARNING" | "OPTIMIZE_TITLE" | "LOWER_PRICE" | "RAISE_PRICE" | "OFFER_CONVERSION" | "END_SELL_SIMILAR" | "EXIT_REVIEW" | "MORE_EVIDENCE" | "LEAVE_ALONE" | "RESTOCK_REVIEW" | "ENTER_COST";
export type FunnelStage = "learning" | "discovery" | "engagement" | "intent" | "pricing" | "listing_quality" | "refresh" | "exit" | "velocity" | "evidence" | "healthy";
export type Confidence = { score: number; band: "high" | "moderate" | "low" };
export type EvidenceGapCode = "IMPRESSION_DATA_UNAVAILABLE" | "TRAFFIC_HISTORY_INSUFFICIENT" | "ITEM_SPECIFICS_MISSING" | "CARD_IDENTITY_INCOMPLETE" | "PRICING_EVIDENCE_MISSING" | "LISTING_DETAILS_UNVERIFIED" | "LISTING_TYPE_UNKNOWN" | "CATEGORY_UNKNOWN" | "OFFER_ECONOMICS_UNKNOWN" | "SAFE_TITLE_PROPOSAL_UNAVAILABLE";
export type EvidenceGap = { code:EvidenceGapCode; stage:FunnelStage; blocks:string[]; recoverableFrom:"ebay-get-item"|"ebay-traffic"|"sold-comps"|"documented-cost"|"observation"; automatic:boolean };
export type DoctrineInput = { ageDays:number|null; views:number|null; trafficEvidence:"recent-window"|"lifetime-total"|"unavailable"; trafficObservationDays:number|null; watchers:number|null; units30:number; units90:number; quantity:number; currentPrice:number; knownUnitCost:number|null; supportedPriceAction:"raise-price"|"lower-price"|null; suggestedPrice:number|null; compConfidence:number|null; itemSpecifics:unknown; authoritativeListingDetails?:boolean; listingFormat?:string|null; categoryId?:string|null; priorInterventions?:DoctrineAction[] };
export type DoctrineDecision = { doctrineVersion:string; signalsEvaluated:Array<{signal:string;value:string|number|null;quality:"authoritative"|"supported"|"verified"|"unavailable"}>; evidenceGaps:EvidenceGap[]; primaryEvidenceGap:EvidenceGapCode|null; diagnosticFunnelStage:FunnelStage; problemsDetected:string[]; candidateInterventionsConsidered:Array<{intervention:DoctrineAction;disposition:"selected"|"rejected"|"deferred";reason:string}>; interventionSelected:DoctrineAction; alternativesRejectedOrDeferred:string[]; problemConfidence:Confidence; actionConfidence:Confidence; compConfidence:number|null; saleLikelihood:"high"|"moderate"|"low"|"unknown"; whyThisActionOutranksAlternatives:string; evaluateNextIfInterventionFails:string; observationWindowDays:number; verifiedTitleDefects:string[]; proposedTitle:string|null };

const HIGH_VALUE_SPECIFICS = /^(year|player\/athlete|player|athlete|set|card name|card number|parallel\/variety|features|professional grader|grade)$/i;
const meaningful=(value:string)=>Boolean(value.trim())&&!/^(n\/a|na|none|does not apply|unknown|unspecified|\[?base(?: set)?\]?)$/i.test(value.trim());
const confidence=(score:number):Confidence=>({score,band:score>=80?"high":score>=60?"moderate":"low"});
const norm=(value:string)=>value.toLowerCase().replace(/[^a-z0-9]+/g," ").trim();
function titleContainsVerifiedValue(title:string,value:string){const normalized=norm(title),target=norm(value);if(target&&normalized.includes(target))return true;const aliases:Record<string,RegExp>={"short print":/\bsp\b/i,"super short print":/\bssp\b/i,"rookie":/\brc\b/i,"rookie card":/\brc\b/i,"autograph":/\bauto\b/i,"autographed":/\bauto\b/i};return aliases[target]?.test(title)??false;}
function safeMissingCoreAttribute(name:string,value:string,missing:Set<string>){
  const trimmed=value.trim();
  if(/^year$/i.test(name))return missing.has("year")&&/^(19|20)\d{2}$/.test(trimmed);
  if(/^(player\/athlete|player|athlete)$/i.test(name))return missing.has("player")&&/^[A-Za-z][A-Za-z .'-]{2,59}$/.test(trimmed)&&trimmed.split(/\s+/).length>=2;
  if(/^card number$/i.test(name))return missing.has("cardNumber")&&/^#?[A-Za-z0-9][A-Za-z0-9-]{0,19}$/.test(trimmed);
  return false;
}
export function verifiedTitleDefects(title:string,itemSpecifics:unknown){const parsed=parseCardIdentity(title);const structurallyComplete=parsed.identityCompleteness>=80;if(!itemSpecifics||typeof itemSpecifics!=="object"||Array.isArray(itemSpecifics))return{defects:[] as string[],verifiedAttributes:0,complete:false,structurallyComplete};const defects:string[]=[];let verifiedAttributes=0;const missing=new Set(parsed.missingAttributes);for(const[name,raw]of Object.entries(itemSpecifics as Record<string,unknown>)){if(!HIGH_VALUE_SPECIFICS.test(name))continue;const values=(Array.isArray(raw)?raw:[raw]).filter((value):value is string=>typeof value==="string"&&meaningful(value));for(const value of values){verifiedAttributes++;if(!titleContainsVerifiedValue(title,value)&&safeMissingCoreAttribute(name,value,missing))defects.push(`${name}: ${value}`);}}return{defects:Array.from(new Set(defects)),verifiedAttributes,complete:verifiedAttributes>=3&&defects.length===0,structurallyComplete};}
export function buildVerifiedTitleProposal(currentTitle:string,defects:string[]):string|null{const additions=defects.map(defect=>{const value=defect.slice(defect.indexOf(":")+1).trim();return defect.startsWith("Card Number:")&&!value.startsWith("#")?`#${value}`:value;}).filter(Boolean);const proposal=[currentTitle.trim(),...additions].join(" ").replace(/\s+/g," ");return additions.length&&proposal.length<=80?proposal:null;}

export function evaluateInventoryDecisionDoctrine(input:DoctrineInput & {title:string;saleLikelihood:"high"|"moderate"|"low"|"unknown"}):DoctrineDecision{
  const title=verifiedTitleDefects(input.title,input.itemSpecifics);const titleProposal=buildVerifiedTitleProposal(input.title,title.defects);const stale=(input.ageDays??0)>=90&&input.units90===0;const mature=(input.ageDays??0)>=14;const lowTraffic=mature&&input.views!=null&&input.views<5;const intent=(input.watchers??0)>=3&&input.units90===0;const priceGap=input.suggestedPrice!=null&&input.suggestedPrice>0?(input.currentPrice-input.suggestedPrice)/input.suggestedPrice*100:null;const supported=input.supportedPriceAction!=null&&input.suggestedPrice!=null&&input.compConfidence!=null&&input.compConfidence>=60;const strongPrice=supported&&(input.compConfidence??0)>=90&&priceGap!=null&&Math.abs(priceGap)>=20;const materialPrice=supported&&priceGap!=null&&Math.abs(priceGap)>=12;const authoritative=Boolean(input.authoritativeListingDetails);const refreshEligible=stale&&authoritative&&title.complete&&Boolean(input.listingFormat)&&Boolean(input.categoryId)&&supported;const prior=new Set(input.priorInterventions??[]);let action:DoctrineAction="MORE_EVIDENCE",stage:FunnelStage="evidence",problem=55,actionScore=50,why="Available evidence does not support a specific intervention.",next="Reassess when additional authoritative traffic, intent, sales, or verified listing evidence is available.",window=30;const problems:string[]=[];
  if(input.ageDays==null||input.ageDays<14){action="LEARNING";stage="learning";problem=90;actionScore=95;why="The listing is not mature enough to diagnose; intervening now would confound the learning period.";next="Evaluate discovery after the listing reaches 14 days with observed traffic evidence.";window=Math.max(7,14-(input.ageDays??0));}
  else if(strongPrice){action=input.supportedPriceAction==="lower-price"?"LOWER_PRICE":"RAISE_PRICE";stage="pricing";problem=input.compConfidence!;actionScore=Math.min(98,input.compConfidence!);problems.push(`Price is ${Math.round(Math.abs(priceGap!))}% ${priceGap!>0?"above":"below"} supported market evidence`);why=`${input.compConfidence}% Comp Confidence and a material ${Math.round(Math.abs(priceGap!))}% mismatch override the normal funnel sequence.`;next="Reassess conversion and velocity after 30 days at the supported price.";window=30;}
  else if(lowTraffic){stage="discovery";problems.push("Mature listing has fewer than 5 observed views");if(authoritative&&title.defects.length&&titleProposal){action="OPTIMIZE_TITLE";problem=90;actionScore=88;why=`Traffic is too weak to judge conversion, and ${title.defects.length} authoritative searchable attribute${title.defects.length===1?" is":"s are"} missing from the title. An exact non-destructive replacement fits eBay's title limit, so fixing discovery outranks price or refresh.`;next="Reassess traffic after 30 days; if discovery remains weak with a verified-complete title, consider End & Sell Similar.";window=30;}else if(refreshEligible){action="END_SELL_SIMILAR";stage="refresh";problem=78;actionScore=72;why="The listing is stale with weak traffic; authoritative details verify its title, category, and format are refresh-ready, with no stronger supported pricing defect.";next="Reassess discovery after 30 days; if repeated refreshes fail, consider an exit review.";window=30;}else{action="MORE_EVIDENCE";problem=76;actionScore=68;why=authoritative&&title.defects.length?"Verified title defects exist, but no exact non-destructive replacement fits the title limit; approving an ambiguous edit would be unsafe.":"Discovery is weak, but authoritative listing completeness and refresh eligibility are not established; price or refresh would be speculative.";next=authoritative&&title.defects.length?"Prepare and verify an exact title replacement that preserves existing information.":"Recover authoritative listing details and item specifics, then reassess listing quality before refresh.";window=30;}}
  else if(intent){stage="intent";problems.push(`${input.watchers} watchers without an authoritative sale in 90 days`);if(materialPrice){action=input.supportedPriceAction==="lower-price"?"LOWER_PRICE":"RAISE_PRICE";stage="pricing";problem=input.compConfidence!;actionScore=Math.min(94,input.compConfidence!);why="Buyer intent exists and supported sold evidence shows a material price mismatch, so correcting price outranks a generic offer.";next="Reassess conversion after 30 days at the supported price.";}else if(supported){action="OFFER_CONVERSION";problem=85;actionScore=78;why="Traffic and buyer intent exist while supported pricing is not materially mismatched; a conversion intervention outranks discovery or repricing.";next="Reassess authoritative sales after 30 days; if intent still does not convert, inspect listing quality and refreshed comps.";}else{action="MORE_EVIDENCE";problem=82;actionScore=62;why="Buyer intent exists, but no trustworthy price conclusion or known offer economics supports a specific conversion amount.";next="Obtain supported comps and known costs before selecting a price or offer intervention.";}window=30;}
  else if(materialPrice){action=input.supportedPriceAction==="lower-price"?"LOWER_PRICE":"RAISE_PRICE";stage="pricing";problem=input.compConfidence!;actionScore=Math.min(90,input.compConfidence!);why="Trustworthy sold evidence shows a material price mismatch and no earlier funnel defect has stronger evidence.";next="Reassess traffic, conversion, and velocity after 30 days at the supported price.";window=30;}
  else if(refreshEligible){action=prior.has("END_SELL_SIMILAR")&&input.ageDays!>=365?"EXIT_REVIEW":"END_SELL_SIMILAR";stage=action==="EXIT_REVIEW"?"exit":"refresh";problem=78;actionScore=action==="EXIT_REVIEW"?74:70;why=action==="EXIT_REVIEW"?"The listing remains stale after a recorded refresh intervention; another relist is weaker than a manual exit review.":"The listing is stale and authoritative details verify its title, category, and format are refresh-ready; no stronger discovery, intent, or pricing defect is supported.";next=action==="EXIT_REVIEW"?"Document the chosen disposition and stop repeated low-value intervention.":"Reassess discovery and sales after 30 days; repeated failure can elevate an exit review.";window=30;}
  else if(input.units30>0&&input.quantity<=2){action="RESTOCK_REVIEW";stage="velocity";problem=82;actionScore=76;why="Authoritative recent sales and low remaining quantity make replenishment review higher leverage than changing the live listing.";next="Reassess availability only after a real acquisition cost and known margin are available.";window=30;}
  else if(input.knownUnitCost==null&&input.units30>0){action="ENTER_COST";stage="evidence";problem=95;actionScore=90;why="Recent sales exist, but missing cost blocks defensible margin, ROI, and offer decisions.";next="Reassess profitability and intervention economics after documented costs are entered.";window=30;}
  else if(input.units30>0||input.saleLikelihood==="high"){action="LEAVE_ALONE";stage="healthy";problem=85;actionScore=88;why="Authoritative velocity is healthy and no stronger supported defect warrants intervention.";next="Continue observing velocity and only intervene if the funnel degrades.";window=30;}
  else if(stale){action="MORE_EVIDENCE";stage="evidence";problem=72;actionScore=60;why="The listing is stale, but verified listing completeness and a trustworthy pricing conclusion are unavailable; refresh or exit would be speculative.";next="Obtain verified listing-quality or sold-comp evidence before selecting refresh or exit.";window=30;}
  else{action="LEAVE_ALONE";stage="healthy";problem=68;actionScore=72;why="No sufficiently supported defect outranks continued observation.";next="Reassess when the listing matures further or new funnel evidence arrives.";window=30;}
  const alternatives:Array<{intervention:DoctrineAction;disposition:"selected"|"rejected"|"deferred";reason:string}>=[{intervention:action,disposition:"selected",reason:why}];for(const candidate of ["OPTIMIZE_TITLE","LOWER_PRICE","RAISE_PRICE","OFFER_CONVERSION","END_SELL_SIMILAR","EXIT_REVIEW"] as DoctrineAction[]){if(candidate===action)continue;alternatives.push({intervention:candidate,disposition:supported||candidate==="OPTIMIZE_TITLE"&&title.defects.length?"deferred":"rejected",reason:candidate==="OPTIMIZE_TITLE"?(title.defects.length?"Verified defect exists but a stronger intervention outranks it.":"No deterministic verified title defect."):candidate==="LOWER_PRICE"||candidate==="RAISE_PRICE"?(supported?"Supported pricing exists but does not outrank the selected action.":"No trustworthy material sold-comp mismatch."):candidate==="OFFER_CONVERSION"?(intent?"Intent exists but another intervention has stronger evidence.":"Insufficient buyer intent."):candidate==="END_SELL_SIMILAR"?(refreshEligible?"Refresh is eligible but a stronger intervention comes first.":"Staleness and authoritative title, category, and format readiness are not all established."):"No recorded failed refresh supports exit."});}
  const evidenceGaps:EvidenceGap[]=[];const gap=(code:EvidenceGapCode,stage:FunnelStage,blocks:string[],recoverableFrom:EvidenceGap["recoverableFrom"],automatic:boolean)=>evidenceGaps.push({code,stage,blocks,recoverableFrom,automatic});
  if(input.trafficEvidence==="unavailable")gap("IMPRESSION_DATA_UNAVAILABLE","discovery",["discovery diagnosis"],"ebay-traffic",true);
  if((input.trafficObservationDays??0)<14)gap("TRAFFIC_HISTORY_INSUFFICIENT","learning",["traffic trend diagnosis"],"observation",true);
  if(!input.itemSpecifics||title.verifiedAttributes===0)gap("ITEM_SPECIFICS_MISSING","listing_quality",["deterministic title optimization","refresh eligibility"],"ebay-get-item",true);
  if(!title.structurallyComplete)gap("CARD_IDENTITY_INCOMPLETE","listing_quality",["listing quality diagnosis"],"ebay-get-item",true);
  if(!supported)gap("PRICING_EVIDENCE_MISSING","pricing",["price intervention"],"sold-comps",true);
  if(!authoritative)gap("LISTING_DETAILS_UNVERIFIED","listing_quality",["title optimization","refresh eligibility"],"ebay-get-item",true);
  if(!input.listingFormat)gap("LISTING_TYPE_UNKNOWN","refresh",["refresh eligibility"],"ebay-get-item",true);
  if(!input.categoryId)gap("CATEGORY_UNKNOWN","discovery",["category/searchability diagnosis","refresh eligibility"],"ebay-get-item",true);
  if(intent&&input.knownUnitCost==null)gap("OFFER_ECONOMICS_UNKNOWN","intent",["defensible offer amount"],"documented-cost",false);
  if(authoritative&&title.defects.length&&!titleProposal)gap("SAFE_TITLE_PROPOSAL_UNAVAILABLE","listing_quality",["executable title optimization"],"observation",false);
  return{doctrineVersion:INVENTORY_DECISION_DOCTRINE_VERSION,signalsEvaluated:[{signal:"listing age days",value:input.ageDays,quality:input.ageDays==null?"unavailable":"authoritative"},{signal:"observed views",value:input.views,quality:input.views==null?"unavailable":"authoritative"},{signal:"impressions",value:null,quality:"unavailable"},{signal:"watchers",value:input.watchers,quality:input.watchers==null?"unavailable":"authoritative"},{signal:"authoritative units sold 30/90",value:`${input.units30}/${input.units90}`,quality:"authoritative"},{signal:"verified title attributes",value:title.verifiedAttributes,quality:title.verifiedAttributes?"verified":"unavailable"},{signal:"supported price target",value:input.suggestedPrice,quality:supported?"supported":"unavailable"}],evidenceGaps,primaryEvidenceGap:action==="MORE_EVIDENCE"?(evidenceGaps[0]?.code??null):null,diagnosticFunnelStage:stage,problemsDetected:problems.length?problems:[why],candidateInterventionsConsidered:alternatives,interventionSelected:action,alternativesRejectedOrDeferred:alternatives.slice(1).map(item=>`${item.intervention}: ${item.reason}`),problemConfidence:confidence(problem),actionConfidence:confidence(actionScore),compConfidence:input.compConfidence,saleLikelihood:input.saleLikelihood,whyThisActionOutranksAlternatives:why,evaluateNextIfInterventionFails:next,observationWindowDays:window,verifiedTitleDefects:title.defects,proposedTitle:action==="OPTIMIZE_TITLE"?titleProposal:null};
}

export type SalesVelocityAction="SEND OFFER"|"INCREASE ADS"|"HOLD / PROTECT MARGIN"|"TITLE / LISTING REVIEW"|"REPRICE"|"MANUAL REVIEW";
export type SalesVelocityFunnel="Exposure"|"Engagement"|"Conversion"|"Healthy";
export type SalesVelocityDecisionInput={base:DoctrineDecision;impressions:number|null;views:number|null;clickThroughRate:number|null;conversionRate:number|null;transactions:number|null;watchers:number|null;watcherQuality:"authoritative"|"stale"|"missing";offerEligible:boolean|null;advertisingEligible:boolean|null;currentAdRate:number|null;knownUnitCost:number|null;costComplete:boolean;currentPrice:number;supportedPriceAction:"raise-price"|"lower-price"|null;suggestedPrice:number|null;compConfidence:number|null;trafficFresh:boolean};
export type SalesVelocityDecision={action:SalesVelocityAction;funnel:SalesVelocityFunnel;confidence:Confidence;why:string;missingEvidence:string[];observationWindowDays:number;suggestedAdjustmentPct:number|null};
export function evaluateSalesVelocityDoctrine(input:SalesVelocityDecisionInput):SalesVelocityDecision{
  const missing:string[]=[];if(input.impressions==null)missing.push("Analytics impressions");if(input.clickThroughRate==null)missing.push("Analytics click-through rate");if(input.conversionRate==null)missing.push("Analytics conversion rate");if(input.watcherQuality!=="authoritative")missing.push(input.watcherQuality==="stale"?"Fresh authoritative watcher count":"Authoritative watcher count");if(input.offerEligible==null)missing.push("Negotiation offer eligibility");if(input.advertisingEligible==null)missing.push("Advertising eligibility");if(input.knownUnitCost==null||!input.costComplete)missing.push("Complete cost basis");
  const exposureKnown=input.impressions!=null&&input.trafficFresh;const lowExposure=exposureKnown&&input.impressions!<50;const adequateExposure=exposureKnown&&input.impressions!>=50;const weakEngagement=adequateExposure&&input.clickThroughRate!=null&&input.clickThroughRate<0.5;const buyerInterest=(input.watchers??0)>0||input.offerEligible===true;const weakConversion=adequateExposure&&buyerInterest&&(input.transactions??0)===0;const healthy=(input.transactions??0)>0||(input.conversionRate??0)>=1;
  const offerPrice=input.currentPrice*.95;const adMarginSafe=input.knownUnitCost!=null&&input.costComplete&&input.currentPrice>=input.knownUnitCost*1.25;const offerMarginSafe=input.knownUnitCost!=null&&input.costComplete&&offerPrice>=input.knownUnitCost*1.2;
  if(healthy)return{action:"HOLD / PROTECT MARGIN",funnel:"Healthy",confidence:confidence(exposureKnown?86:70),why:"Observed conversion is healthy; protecting price and margin outranks intervention.",missingEvidence:missing,observationWindowDays:30,suggestedAdjustmentPct:null};
  if(lowExposure&&input.advertisingEligible===true&&adMarginSafe)return{action:"INCREASE ADS",funnel:"Exposure",confidence:confidence(82),why:"Authoritative traffic shows low exposure and known economics leave testing room; a +3 point ad-rate test outranks an unsupported price reduction.",missingEvidence:missing,observationWindowDays:14,suggestedAdjustmentPct:3};
  if(weakEngagement)return{action:"TITLE / LISTING REVIEW",funnel:"Engagement",confidence:confidence(80),why:"Exposure is adequate but engagement is weak, so listing quality and demand diagnosis outrank price or advertising changes.",missingEvidence:missing,observationWindowDays:14,suggestedAdjustmentPct:null};
  if(weakConversion&&input.offerEligible===true&&offerMarginSafe)return{action:"SEND OFFER",funnel:"Conversion",confidence:confidence(input.watcherQuality==="authoritative"?85:72),why:"eBay confirms offer eligibility and buyer interest while a conceptual 5% offer preserves the known margin guardrail.",missingEvidence:missing,observationWindowDays:7,suggestedAdjustmentPct:-5};
  const supportedReprice=input.supportedPriceAction!=null&&input.suggestedPrice!=null&&(input.compConfidence??0)>=60;
  if(weakConversion&&supportedReprice&&input.knownUnitCost!=null&&input.costComplete){const pct=(input.suggestedPrice!/input.currentPrice-1)*100;if(pct>=-8)return{action:"REPRICE",funnel:"Conversion",confidence:confidence(Math.min(90,input.compConfidence!)),why:"Adequate exposure and weak conversion coincide with supported pricing evidence; the proposed first-stage change stays within the 8% ceiling.",missingEvidence:missing,observationWindowDays:14,suggestedAdjustmentPct:Math.round(pct*10)/10};}
  if(lowExposure)return{action:"MANUAL REVIEW",funnel:"Exposure",confidence:confidence(60),why:"Exposure is low, but advertising eligibility or complete margin economics do not support an automatic advertising recommendation.",missingEvidence:missing,observationWindowDays:14,suggestedAdjustmentPct:null};
  if(buyerInterest)return{action:"MANUAL REVIEW",funnel:"Conversion",confidence:confidence(58),why:"Buyer interest exists, but offer eligibility or margin evidence is insufficient for a defensible conversion action.",missingEvidence:missing,observationWindowDays:7,suggestedAdjustmentPct:null};
  if(input.base.interventionSelected==="OPTIMIZE_TITLE")return{action:"TITLE / LISTING REVIEW",funnel:"Engagement",confidence:input.base.actionConfidence,why:input.base.whyThisActionOutranksAlternatives,missingEvidence:missing,observationWindowDays:input.base.observationWindowDays,suggestedAdjustmentPct:null};
  return{action:"MANUAL REVIEW",funnel:exposureKnown?"Engagement":"Exposure",confidence:confidence(45),why:"The current evidence cannot distinguish exposure, engagement, and conversion strongly enough to recommend an economic intervention.",missingEvidence:missing,observationWindowDays:14,suggestedAdjustmentPct:null};
}
