export const LISTING_IMAGE_QUALITY_RULE_VERSION = "listing-image-quality-v1.0.0";
export type ImageListingType = "RAW SINGLE" | "GRADED" | "SEALED" | "LOT" | "MEMORABILIA" | "OTHER";
export type ImagePriority = "HIGH PRIORITY" | "REVIEW" | "HEALTHY";
export type ImageActionability = "AUTO-CORRECTABLE" | "OPERATOR ACTION REQUIRED" | "REVIEW" | "NO ACTION";
export type ListingImageQualityInput = {listingId:string;ebayItemId:string;title:string;currentPrice:number;categoryId:string|null;categoryName?:string|null;condition:string|null;quantity:number;imageUrls:string[];itemSpecifics:unknown;authoritativeObservedAt:Date|null;now?:Date};
export type ListingImageQualityAssessment = {listingId:string;ebayItemId:string;title:string;currentPrice:number;categoryId:string|null;listingType:ImageListingType;imageCount:number;expectedStandard:string;priority:ImagePriority;actionability:ImageActionability;confidence:number;issues:string[];evidence:string[];recovery:string;thumbnails:string[];duplicateImageCount:number;stale:boolean;ruleVersion:string};
const DAY=86_400_000;
const normalizedUrl=(value:string)=>value.trim().replace(/^http:/i,"https:").replace(/[?#].*$/,"").toLowerCase();
function aspectText(value:unknown){if(!value||typeof value!=="object")return "";return Object.entries(value as Record<string,unknown>).flatMap(([key,raw])=>[key,...(Array.isArray(raw)?raw:[raw]).filter(item=>typeof item==="string")]).join(" ");}
export function classifyImageListing(title:string,categoryName:string|null|undefined,itemSpecifics:unknown):ImageListingType{const text=`${title} ${categoryName??""} ${aspectText(itemSpecifics)}`.toLowerCase();if(/\b(psa|bgs|sgc|cgc|hga|graded|gem mint)\b/.test(text)&&/\b(10|9\.5|9|8\.5|8|7\.5|7|6|5|4|3|2|1)\b/.test(text))return"GRADED";if(/\b(lot|collection|cards? lot|\d+\s*cards?)\b/.test(text)&&!/\b#\s*\d+\b/.test(title.toLowerCase()))return"LOT";if(/\b(sealed|unopened|factory set|hobby box|blaster|booster|pack|mega box)\b/.test(text))return"SEALED";if(/\b(helmet|jersey|photo|baseball|football|basketball|memorabilia|bobblehead)\b/.test(text)&&!/\bcard\b/.test(text))return"MEMORABILIA";if(/\b(card|rookie|rc|refractor|prizm|topps|panini|bowman|upper deck|donruss|select|mosaic)\b/.test(text))return"RAW SINGLE";return"OTHER";}
function standardFor(type:ImageListingType){if(type==="RAW SINGLE")return"Front and back images";if(type==="GRADED")return"Slab front and back; label readable";if(type==="LOT")return"Representative group plus useful detail images";if(type==="SEALED")return"Front plus condition/seal details";if(type==="MEMORABILIA")return"Multiple angles and condition/authentication details";return"Primary image plus category-appropriate detail image(s)";}
export function assessListingImageQuality(input:ListingImageQualityInput):ListingImageQualityAssessment{const now=input.now??new Date(),urls=input.imageUrls.map(url=>url.trim()).filter(Boolean),unique=new Set(urls.map(normalizedUrl)),duplicateImageCount=Math.max(0,urls.length-unique.size),listingType=classifyImageListing(input.title,input.categoryName,input.itemSpecifics),stale=!input.authoritativeObservedAt||now.getTime()-input.authoritativeObservedAt.getTime()>7*DAY,issues:string[]=[],evidence=[`${urls.length} persisted image URL${urls.length===1?"":"s"}`,input.authoritativeObservedAt?`Provider observation ${input.authoritativeObservedAt.toISOString()}`:"Provider observation timestamp unavailable"];
if(!urls.length)issues.push("No image evidence is persisted; live listing image quality is unknown");if(duplicateImageCount)issues.push(`${duplicateImageCount} duplicate image URL${duplicateImageCount===1?"":"s"}`);if(listingType==="RAW SINGLE"&&urls.length===1)issues.push("Raw single has no usable secondary/back image");if(listingType==="GRADED"&&urls.length===1)issues.push("Graded listing has only one image; slab back/label coverage is incomplete");if(["SEALED","LOT","MEMORABILIA"].includes(listingType)&&urls.length===1)issues.push(`${listingType.toLowerCase()} listing has only one image`);if(stale)issues.push("Persisted provider image state is stale or undated");
let priority:ImagePriority="HEALTHY",actionability:ImageActionability="NO ACTION",confidence=96;if(!urls.length){priority="REVIEW";actionability="REVIEW";confidence=40;}else if(issues.some(issue=>/only one image|secondary\/back/.test(issue))){priority="REVIEW";actionability="OPERATOR ACTION REQUIRED";confidence=stale?76:94;}if(duplicateImageCount){priority="REVIEW";actionability="REVIEW";confidence=Math.min(confidence,92);}if(stale&&priority==="HEALTHY"){priority="REVIEW";actionability="REVIEW";confidence=65;}
return{listingId:input.listingId,ebayItemId:input.ebayItemId,title:input.title,currentPrice:input.currentPrice,categoryId:input.categoryId,listingType,imageCount:urls.length,expectedStandard:standardFor(listingType),priority,actionability,confidence,issues,evidence,recovery:actionability==="OPERATOR ACTION REQUIRED"?"Capture the missing view(s) of this exact physical item; no cross-listing image reuse is approved.":actionability==="REVIEW"?"Review exact-listing provider evidence before any correction.":"No correction proposed.",thumbnails:Array.from(unique).map(key=>urls.find(url=>normalizedUrl(url)===key)!).slice(0,4),duplicateImageCount,stale,ruleVersion:LISTING_IMAGE_QUALITY_RULE_VERSION};}
