export const LISTING_IDENTITY_INTEGRITY_VERSION="listing-identity-integrity-v1.0.0";
export type IntegrityClassification="HIGH PRIORITY — LIKELY INCORRECT"|"REVIEW"|"HEALTHY";
export type IntegrityInput={listingId:string;ebayItemId:string;title:string;currentPrice:number;itemSpecifics:unknown;authoritativeSource:string|null;authoritativeObservedAt:Date|null;now?:Date};
export type IntegrityFinding={family:"SIGNED BY"|"TITLE / PLAYER"|"TEAM"|"CARD NUMBER"|"PARALLEL / SERIAL"|"GRADING";classification:Exclude<IntegrityClassification,"HEALTHY">;conflict:string;evidence:string[];confidence:number;recommendedCorrection:string};
export type IdentityIntegrityAssessment={listingId:string;ebayItemId:string;title:string;currentPrice:number;classification:IntegrityClassification;confidence:number;findings:IntegrityFinding[];specifics:{player:string[];signedBy:string[];autographed:string[];team:string[];cardNumber:string[];parallel:string[];serial:string[];graded:string[];grader:string[];grade:string[]};authoritative:boolean;observedAt:string|null;ruleVersion:string};
const DAY=86_400_000;
const norm=(value:string)=>value.toLowerCase().normalize("NFKD").replace(/[^a-z0-9]+/g," ").trim();
const compact=(value:string)=>norm(value).replace(/\s+/g,"");
function mapSpecifics(value:unknown){const result=new Map<string,string[]>();if(!value||typeof value!=="object"||Array.isArray(value))return result;for(const [key,raw] of Object.entries(value as Record<string,unknown>)){const values=(Array.isArray(raw)?raw:[raw]).filter((item):item is string=>typeof item==="string"&&Boolean(item.trim())).map(item=>item.trim());if(values.length)result.set(norm(key),values);}return result;}
function pick(map:Map<string,string[]>,...names:string[]){const values=names.flatMap(name=>map.get(norm(name))??[]),seen=new Set<string>();return values.filter(value=>{const key=norm(value);if(!key||seen.has(key))return false;seen.add(key);return true;});}
const affirmative=(values:string[])=>values.some(value=>/^(yes|true|1|autographed)$/i.test(value.trim()));
const negative=(values:string[])=>values.some(value=>/^(no|false|0|not autographed)$/i.test(value.trim()));
const titleContains=(title:string,value:string)=>{const target=norm(value);return target.length>=3&&` ${norm(title)} `.includes(` ${target} `);};
const explicitCardNumbers=(title:string)=>Array.from(title.matchAll(/(?:^|\s)#([A-Za-z0-9]+(?:-[A-Za-z0-9]+)*)(?=\s|$|[,.])/g),match=>compact(match[1])).filter(value=>!/^\d+\/\d+$/.test(value));
const printRuns=(title:string)=>Array.from(title.matchAll(/\/(\d{1,5})(?=\s|$|[,.])/g),match=>Number(match[1])).filter(value=>value>1);
const graders=["PSA","BGS","SGC","CGC","CSG","HGA"];
const titleGrader=(title:string)=>graders.find(grader=>new RegExp(`\\b${grader}\\b`,"i").test(title))??null;
const titleGrade=(title:string,grader:string|null)=>grader?title.match(new RegExp(`\\b${grader}\\s+(AUTHENTIC|10|9\\.5|9|8\\.5|8|7\\.5|7|6|5|4|3|2|1)\\b`,"i"))?.[1]??null:null;
function finding(family:IntegrityFinding["family"],classification:IntegrityFinding["classification"],conflict:string,evidence:string[],confidence:number,recommendedCorrection:string):IntegrityFinding{return{family,classification,conflict,evidence,confidence,recommendedCorrection};}
export function assessListingIdentityIntegrity(input:IntegrityInput):IdentityIntegrityAssessment{const map=mapSpecifics(input.itemSpecifics),specifics={player:pick(map,"Player/Athlete","Player","Athlete"),signedBy:pick(map,"Signed By"),autographed:pick(map,"Autographed"),team:pick(map,"Team"),cardNumber:pick(map,"Card Number"),parallel:pick(map,"Parallel/Variety","Parallel","Variation"),serial:pick(map,"Serial Number","Print Run","Serial Numbered"),graded:pick(map,"Graded"),grader:pick(map,"Professional Grader","Grader"),grade:pick(map,"Grade")},findings:IntegrityFinding[]=[],now=input.now??new Date(),fresh=Boolean(input.authoritativeObservedAt&&now.getTime()-input.authoritativeObservedAt.getTime()<=7*DAY),authoritative=Boolean(input.authoritativeSource&&input.itemSpecifics&&fresh);
if(specifics.signedBy.length&&negative(specifics.autographed))findings.push(finding("SIGNED BY","HIGH PRIORITY — LIKELY INCORRECT","Signed By is populated while Autographed is No",[`Signed By: ${specifics.signedBy.join("; ")}`,`Autographed: ${specifics.autographed.join("; ")}`],99,"Review the physical card, then remove the incorrect signer or correct the Autographed value in a full preserved ItemSpecifics payload."));
if(specifics.signedBy.length&&specifics.player.length){const signerMatchesPlayer=specifics.signedBy.some(signer=>specifics.player.some(player=>norm(signer)===norm(player))),multi=/\b(dual|triple|quad|multi|co-signed|cut signature)\b/i.test(input.title)||specifics.signedBy.length>1||specifics.player.length>1;if(!signerMatchesPlayer){const signerInTitle=specifics.signedBy.some(value=>titleContains(input.title,value)),playerInTitle=specifics.player.some(value=>titleContains(input.title,value));findings.push(finding("SIGNED BY",!multi&&playerInTitle&&!signerInTitle?"HIGH PRIORITY — LIKELY INCORRECT":"REVIEW",`Signed By (${specifics.signedBy.join("; ")}) differs from Player/Athlete (${specifics.player.join("; ")})`,[`Title: ${input.title}`,`Player/Athlete: ${specifics.player.join("; ")}`,`Signed By: ${specifics.signedBy.join("; ")}`,multi?"Possible multi-signer exception":"No multi-signer indicator found"],!multi&&playerInTitle&&!signerInTitle?97:72,"Verify the signer from the exact card image/provider record before changing Signed By."));}}
if(specifics.player.length&&!specifics.player.some(value=>titleContains(input.title,value)))findings.push(finding("TITLE / PLAYER","REVIEW",`Player/Athlete is not represented verbatim in the title`,[`Title: ${input.title}`,`Player/Athlete: ${specifics.player.join("; ")}`],65,"Confirm aliases, multi-player identity, and the physical card before editing structured identity."));
const titleNumbers=explicitCardNumbers(input.title),specificNumbers=specifics.cardNumber.map(compact).filter(Boolean);if(titleNumbers.length&&specificNumbers.length&&!titleNumbers.some(value=>specificNumbers.includes(value)))findings.push(finding("CARD NUMBER","HIGH PRIORITY — LIKELY INCORRECT",`Explicit title card number conflicts with Card Number`,[`Title number: ${titleNumbers.join("; ")}`,`Card Number: ${specifics.cardNumber.join("; ")}`],99,"Replace only the incorrect Card Number after exact-card verification, preserving the complete ItemSpecifics collection."));
const titleRun=printRuns(input.title).at(-1),specificRun=specifics.serial.map(value=>Number(value.match(/\d+/)?.[0])).find(value=>Number.isFinite(value)&&value>1);if(titleRun&&specificRun&&titleRun!==specificRun)findings.push(finding("PARALLEL / SERIAL","HIGH PRIORITY — LIKELY INCORRECT",`Title print run /${titleRun} conflicts with structured print run /${specificRun}`,[`Title: ${input.title}`,`Serial/Print Run: ${specifics.serial.join("; ")}`],98,"Verify the stamped serial denominator and correct only the conflicting exact aspect."));
const graderInTitle=titleGrader(input.title),gradeInTitle=titleGrade(input.title,graderInTitle);if(negative(specifics.graded)&&(specifics.grader.length||specifics.grade.length||graderInTitle))findings.push(finding("GRADING","HIGH PRIORITY — LIKELY INCORRECT","Graded is No while grading evidence is populated",[`Graded: ${specifics.graded.join("; ")}`,`Professional Grader: ${specifics.grader.join("; ")||"none"}`,`Grade: ${specifics.grade.join("; ")||"none"}`,`Title grader: ${graderInTitle??"none"}`],99,"Verify the slab and reconcile Graded, Professional Grader, and Grade together."));
if(graderInTitle&&specifics.grader.length&&!specifics.grader.some(value=>norm(value).includes(norm(graderInTitle))))findings.push(finding("GRADING","HIGH PRIORITY — LIKELY INCORRECT",`Title grader ${graderInTitle} conflicts with Professional Grader ${specifics.grader.join("; ")}`,[`Title: ${input.title}`,`Professional Grader: ${specifics.grader.join("; ")}`],99,"Verify the slab label and correct Professional Grader only through a complete preserved ItemSpecifics payload."));
if(gradeInTitle&&specifics.grade.length&&!specifics.grade.some(value=>norm(value)===norm(gradeInTitle)))findings.push(finding("GRADING","HIGH PRIORITY — LIKELY INCORRECT",`Title grade ${gradeInTitle} conflicts with Grade ${specifics.grade.join("; ")}`,[`Title: ${input.title}`,`Grade: ${specifics.grade.join("; ")}`],99,"Verify the slab label and correct Grade together with its grader identity."));
if(!authoritative&&findings.length)for(const row of findings){row.classification="REVIEW";row.confidence=Math.min(row.confidence,70);row.evidence.push("Provider item-specific state is stale or not authoritative");}
const high=findings.filter(row=>row.classification==="HIGH PRIORITY — LIKELY INCORRECT"),review=findings.filter(row=>row.classification==="REVIEW"),classification:IntegrityClassification=high.length?"HIGH PRIORITY — LIKELY INCORRECT":review.length?"REVIEW":"HEALTHY",confidence=high.length?Math.max(...high.map(row=>row.confidence)):review.length?Math.max(...review.map(row=>row.confidence)):authoritative?95:60;return{listingId:input.listingId,ebayItemId:input.ebayItemId,title:input.title,currentPrice:input.currentPrice,classification,confidence,findings,specifics,authoritative,observedAt:input.authoritativeObservedAt?.toISOString()??null,ruleVersion:LISTING_IDENTITY_INTEGRITY_VERSION};}
