import {parseCardIdentity} from "./comp-validation/identity.ts";
import type {EbayCategoryAspect} from "./ebay-taxonomy.ts";
export const LISTING_COMPLETENESS_RULE_VERSION="listing-completeness-v1.1.0";
export type CompletenessDisposition="COMPLETE"|"AUTO-FIX"|"REVIEW"|"DO-NOT-TOUCH";
export type FieldProposal={field:string;targetAspect:string|null;semanticFamily:string|null;before:string[]|null;proposed:string;confidence:number;disposition:"AUTO-FIX"|"REVIEW"|"DO-NOT-TOUCH";reason:string;evidence:Array<{source:"seller-title"|"seller-item-specific"|"ebay-category-aspect"|"deterministic-parser";value:string;observedAt:string|null}>};
export type ListingCompletenessAssessment={listingId:string;ebayItemId:string;title:string;categoryId:string|null;score:number;disposition:CompletenessDisposition;beforeState:Record<string,string[]>;proposedPatch:FieldProposal[];missingFields:string[];malformedFields:string[];conflicts:string[];categoryRequirements:{available:boolean;required:string[];recommended:string[]};authoritative:boolean;ruleVersion:string;parserVersion:string;assessedAt:string;reason:string};
const aliases={sport:/^sport$/i,player:/^(player|player\/athlete|athlete)$/i,year:/^year$/i,manufacturer:/^(manufacturer|brand)$/i,set:/^(set|product)$/i,cardNumber:/^card\s*number$/i,team:/^team$/i,graded:/^graded$/i,gradingCompany:/^(professional grader|grading company)$/i,grade:/^(grade|professional grade)$/i,parallel:/^(parallel\/variety|parallel|variety)$/i} as const;
const priorityAliasKeys:Record<string,keyof typeof aliases>={Sport:"sport","Player/Athlete":"player",Manufacturer:"manufacturer",Set:"set","Card Number":"cardNumber",Team:"team",Graded:"graded","Professional Grader":"gradingCompany",Grade:"grade"};
const exactTargetAspect:Record<string,string>={Sport:"Sport","Player/Athlete":"Player/Athlete",Manufacturer:"Manufacturer",Set:"Set","Card Number":"Card Number",Team:"Team",Graded:"Graded","Professional Grader":"Professional Grader",Grade:"Grade","Parallel/Variety":"Parallel/Variety"};
const YEAR_ASPECTS=["Year","Season","Year Manufactured","Release Year","Production Year","Publication Year","Model Year"] as const;
const exactName=(left:string,right:string)=>left.localeCompare(right,undefined,{sensitivity:"accent"})===0;
const object=(value:unknown)=>value&&typeof value==="object"&&!Array.isArray(value)?value as Record<string,unknown>:{};
function normalizedSpecifics(value:unknown){const result:Record<string,string[]>={};for(const[name,raw]of Object.entries(object(value))){const values=(Array.isArray(raw)?raw:[raw]).filter((item):item is string=>typeof item==="string"&&item.trim().length>0).map(item=>item.trim());if(values.length)result[name]=Array.from(new Set(values));}return result;}
function existing(before:Record<string,string[]>,key:keyof typeof aliases){return Object.entries(before).find(([name])=>aliases[key].test(name))?.[1]??null;}
function explicitSport(title:string){const match=title.match(/\b(baseball|football|basketball|hockey|soccer|golf|wrestling|tennis)\b/i);return match?match[1].replace(/^./,c=>c.toUpperCase()):null;}
function proposal(field:string,before:string[]|null,value:string|null,confidence:number,reason:string,assessedAt:string,sensitive=false):FieldProposal|null{
  if(!value||before?.some(item=>item.localeCompare(value,undefined,{sensitivity:"accent"})===0))return null;
  const targetAspect=exactTargetAspect[field]??null;
  if(before)return{field,targetAspect,semanticFamily:null,before,proposed:value,confidence,disposition:"DO-NOT-TOUCH",reason:`Existing seller value conflicts with inferred ${field}; never overwrite automatically.`,evidence:[{source:"seller-item-specific",value:before.join(" | "),observedAt:assessedAt},{source:"deterministic-parser",value,observedAt:assessedAt}]};
  return{field,targetAspect,semanticFamily:null,before:null,proposed:value,confidence,disposition:sensitive||confidence<98?"REVIEW":"AUTO-FIX",reason,evidence:[{source:"seller-title",value,observedAt:assessedAt},{source:"deterministic-parser",value,observedAt:assessedAt}]};
}
function yearProposal(before:Record<string,string[]>,value:string|null,aspects:EbayCategoryAspect[],assessedAt:string):FieldProposal|null{
  if(!value)return null;
  const liveEquivalent=Object.entries(before).filter(([name])=>YEAR_ASPECTS.some(candidate=>exactName(candidate,name)));
  if(liveEquivalent.some(([,values])=>values.some(item=>exactName(item,value))))return null;
  if(liveEquivalent.length)return{field:"Year",targetAspect:null,semanticFamily:"year",before:liveEquivalent.flatMap(([,values])=>values),proposed:value,confidence:99,disposition:"DO-NOT-TOUCH",reason:"An authoritative year-family aspect contains a different value; no automatic year-family write is permitted.",evidence:[...liveEquivalent.map(([name,values])=>({source:"seller-item-specific" as const,value:`${name}: ${values.join(" | ")}`,observedAt:assessedAt})),{source:"deterministic-parser" as const,value,observedAt:assessedAt}]};
  const candidates=aspects.filter(aspect=>YEAR_ASPECTS.some(name=>exactName(name,aspect.name))&&(!aspect.allowedValues.length||aspect.allowedValues.some(item=>exactName(item,value))));
  const target=candidates.sort((left,right)=>Number(exactName(right.name,"Year"))-Number(exactName(left.name,"Year"))||Number(right.required)-Number(left.required)||Number(right.usage==="RECOMMENDED")-Number(left.usage==="RECOMMENDED")||YEAR_ASPECTS.findIndex(name=>exactName(name,left.name))-YEAR_ASPECTS.findIndex(name=>exactName(name,right.name)))[0];
  if(!target)return null;
  return{field:target.name,targetAspect:target.name,semanticFamily:"year",before:null,proposed:value,confidence:99,disposition:"AUTO-FIX",reason:`A single four-digit release year appears in the seller title and resolves to the exact eBay Taxonomy aspect ${target.name}.`,evidence:[{source:"seller-title",value,observedAt:assessedAt},{source:"deterministic-parser",value,observedAt:assessedAt},{source:"ebay-category-aspect",value:target.name,observedAt:assessedAt}]};
}
function enforceCategoryConformance(items:FieldProposal[],categoryId:string|null,aspects:EbayCategoryAspect[]){return items.map(item=>{
  if(item.disposition!=="AUTO-FIX")return item;
  const aspect=item.targetAspect?aspects.find(candidate=>exactName(candidate.name,item.targetAspect!)):undefined;
  const conforms=Boolean(aspect)&&(!aspect!.allowedValues.length||aspect!.allowedValues.some(value=>value.localeCompare(item.proposed,undefined,{sensitivity:"accent"})===0));
  if(categoryId&&conforms)return{...item,evidence:[...item.evidence,{source:"ebay-category-aspect" as const,value:aspect!.name,observedAt:item.evidence[0]?.observedAt??null}]};
  return{...item,disposition:"REVIEW" as const,reason:`${item.reason} ${categoryId?"The value cannot yet be validated against this category's aspect constraints.":"Category metadata is missing, so aspect conformance cannot be proven."}`};
});}
export function assessListingCompleteness(input:{listingId:string;ebayItemId:string;title:string;categoryId:string|null;itemSpecifics:unknown;authoritativeSource:string|null;authoritativeObservedAt:Date|null;aspects:EbayCategoryAspect[];now?:Date}):ListingCompletenessAssessment{
  const now=input.now??new Date(),assessedAt=now.toISOString(),before=normalizedSpecifics(input.itemSpecifics),identity=parseCardIdentity(input.title);
  const safeCardNumber=identity.cardNumber&&/\d/.test(identity.cardNumber)&&!/^(ed|d|numbered)$/i.test(identity.cardNumber)?identity.cardNumber:null;
  const raw=[proposal("Sport",existing(before,"sport"),explicitSport(input.title),99,"Explicit sport term appears in the seller title.",assessedAt),proposal("Player/Athlete",existing(before,"player"),identity.player,86,"Deterministic title parsing found a plausible player; human verification is required.",assessedAt),yearProposal(before,identity.year==null?null:String(identity.year),input.aspects,assessedAt),proposal("Manufacturer",existing(before,"manufacturer"),identity.manufacturer,99,"A recognized manufacturer token appears in the seller title.",assessedAt),proposal("Set",existing(before,"set"),identity.setName,96,"A recognized product/set phrase appears in the seller title.",assessedAt),proposal("Card Number",existing(before,"cardNumber"),safeCardNumber,99,"A single explicit hash/no. card-number token appears in the seller title.",assessedAt),proposal("Graded",existing(before,"graded"),identity.gradeCompany?"Yes":null,99,"An explicit recognized grading-company token appears in the seller title.",assessedAt,true),proposal("Professional Grader",existing(before,"gradingCompany"),identity.gradeCompany,99,"An explicit grading-company token appears in the seller title.",assessedAt,true),proposal("Grade",existing(before,"grade"),identity.gradeValue==null?null:String(identity.gradeValue),99,"An explicit grader and numeric grade appear together in the seller title.",assessedAt,true),proposal("Parallel/Variety",existing(before,"parallel"),identity.parallel,85,"Parallel identity affects economics and remains review-only.",assessedAt,true)].filter((item):item is FieldProposal=>item!=null);
  const patch=enforceCategoryConformance(raw,input.categoryId,input.aspects),required=input.aspects.filter(a=>a.required).map(a=>a.name),recommended=input.aspects.filter(a=>a.usage==="RECOMMENDED").map(a=>a.name),hasName=(name:string)=>Object.keys(before).some(key=>key.localeCompare(name,undefined,{sensitivity:"accent"})===0),priority=["Sport","Player/Athlete","Year","Manufacturer","Set","Card Number","Team","Graded","Professional Grader","Grade"];
  const hasPriority=(name:string)=>name==="Year"?Object.keys(before).some(key=>YEAR_ASPECTS.some(candidate=>exactName(candidate,key))):Object.keys(before).some(key=>priorityAliasKeys[name]?aliases[priorityAliasKeys[name]].test(key):exactName(name,key));
  const proposedPriority=(name:string)=>name==="Year"?patch.some(item=>item.semanticFamily==="year"):patch.some(item=>item.field===name);
  const missing=Array.from(new Set([...required.filter(name=>!hasName(name)),...priority.filter(name=>!hasPriority(name)&&!proposedPriority(name))])),malformed=Object.entries(before).flatMap(([name,values])=>values.some(value=>/^(unknown|n\/a|does not apply|none)$/i.test(value.trim()))?[name]:[]),conflicts=patch.filter(p=>p.disposition==="DO-NOT-TOUCH").map(p=>p.field);
  const disposition:CompletenessDisposition=conflicts.length?"DO-NOT-TOUCH":patch.some(p=>p.disposition==="REVIEW")||!input.categoryId?"REVIEW":patch.some(p=>p.disposition==="AUTO-FIX")?"AUTO-FIX":missing.length||malformed.length?"REVIEW":"COMPLETE";
  const denominator=Math.max(1,priority.length+required.length),present=priority.filter(name=>hasName(name)).length+required.filter(hasName).length,score=Math.max(0,Math.min(100,Math.round(100*present/denominator)-malformed.length*5-conflicts.length*10));
  const reason=disposition==="COMPLETE"?"No prioritized or category-required metadata gap was detected.":disposition==="AUTO-FIX"?"Only conforming, high-confidence, missing-field proposals are present; this remains read-only.":disposition==="DO-NOT-TOUCH"?"Existing seller data conflicts with inferred evidence; automatic replacement is prohibited.":!input.categoryId?"Category metadata is missing; category selection and dependent aspects require review.":"At least one ambiguous, sensitive, malformed, or unsupported field requires review.";
  return{listingId:input.listingId,ebayItemId:input.ebayItemId,title:input.title,categoryId:input.categoryId,score,disposition,beforeState:before,proposedPatch:patch,missingFields:missing,malformedFields:malformed,conflicts,categoryRequirements:{available:input.aspects.length>0,required,recommended},authoritative:input.authoritativeSource==="ebay-trading-get-item"&&input.authoritativeObservedAt!=null,ruleVersion:LISTING_COMPLETENESS_RULE_VERSION,parserVersion:"canonical-card-identity",assessedAt,reason};
}
