import { Prisma } from "@prisma/client";
import { prisma } from "./prisma.ts";
import { scoreListingRefresh } from "./listing-refresh-agent.ts";
const DAY=86_400_000;
type SaleRow={listingId:string;units30:bigint;units90:bigint};type Baseline={listingId:string;views:number;capturedAt:Date};
export async function loadListingRefreshCandidates(now=new Date()){
  const since30=new Date(now.getTime()-30*DAY),since90=new Date(now.getTime()-90*DAY),since180=new Date(now.getTime()-180*DAY);
  const [listings,sales,baselines]=await Promise.all([
    prisma.listing.findMany({where:{listingStatus:"active"},select:{id:true,ebayItemId:true,title:true,currentPrice:true,listingStatus:true,listingFormat:true,startTime:true,authoritativeObservedAt:true,authoritativeSource:true,categoryId:true,quantity:true,watchers:true,views:true,promotionStatus:true,priceChanges:{orderBy:{changedAt:"desc"},take:1,select:{changedAt:true}},ebayActionExecutions:{where:{createdAt:{gte:since180}},orderBy:{createdAt:"desc"},select:{action:true,status:true,createdAt:true,providerVerifiedAt:true}}}}),
    prisma.$queryRaw<SaleRow[]>(Prisma.sql`SELECT "listingId",COALESCE(SUM(quantity) FILTER(WHERE "soldAt">=${since30}),0)::bigint AS "units30",COALESCE(SUM(quantity) FILTER(WHERE "soldAt">=${since90}),0)::bigint AS "units90" FROM "SaleEvent" WHERE "listingId" IS NOT NULL AND provider='ebay-fulfillment' AND status<>'cancelled' GROUP BY "listingId"`),
    prisma.$queryRaw<Baseline[]>(Prisma.sql`SELECT DISTINCT ON ("listingId") "listingId",views,"capturedAt" FROM "ListingSnapshot" WHERE "capturedAt">=${since30} ORDER BY "listingId","capturedAt" ASC`),
  ]);
  const saleMap=new Map(sales.map(row=>[row.listingId,row])),baseMap=new Map(baselines.map(row=>[row.listingId,row]));
  const rows=listings.map(listing=>{const sale=saleMap.get(listing.id),base=baseMap.get(listing.id),titleExecution=listing.ebayActionExecutions.find(row=>row.action==="OPTIMIZE_TITLE"&&row.status==="verified"),refreshExecution=listing.ebayActionExecutions.find(row=>row.action==="END_SELL_SIMILAR"&&row.status==="verified"),active=listing.ebayActionExecutions.some(row=>["approved","executing","partial_failure"].includes(row.status));return scoreListingRefresh({listingId:listing.id,ebayItemId:listing.ebayItemId,title:listing.title,currentPrice:Number(listing.currentPrice),listingStatus:listing.listingStatus,listingFormat:listing.listingFormat,startTime:listing.startTime,authoritativeObservedAt:listing.authoritativeObservedAt,authoritativeSource:listing.authoritativeSource,categoryId:listing.categoryId,quantity:listing.quantity,units30:Number(sale?.units30??0),units90:Number(sale?.units90??0),views30:base?Math.max(0,listing.views-base.views):null,trafficObservedAt:base?.capturedAt??null,watchers:listing.watchers,promotionStatus:listing.promotionStatus,currentAdRate:null,negotiationEligible:null,lastPriceChangeAt:listing.priceChanges[0]?.changedAt??null,lastTitleChangeAt:titleExecution?.providerVerifiedAt??null,lastRefreshAt:refreshExecution?.providerVerifiedAt??null,activeIntervention:active,now});});
  const order={"HIGH-CONFIDENCE REFRESH":0,"REVIEW":1,"LEAVE ALONE":2,"DO NOT TOUCH":3} as const;rows.sort((a,b)=>order[a.classification]-order[b.classification]||b.score-a.score||(b.ageDays??-1)-(a.ageDays??-1)||a.ebayItemId.localeCompare(b.ebayItemId));
  const counts={"HIGH-CONFIDENCE REFRESH":0,"REVIEW":0,"LEAVE ALONE":0,"DO NOT TOUCH":0};for(const row of rows)counts[row.classification]++;
  const candidateRows=rows.filter(row=>row.classification==="HIGH-CONFIDENCE REFRESH"||row.classification==="REVIEW");const ages=(threshold:number)=>rows.filter(row=>(row.ageDays??-1)>=threshold).length,candidateAges=(threshold:number)=>candidateRows.filter(row=>(row.ageDays??-1)>=threshold).length;
  return{generatedAt:now.toISOString(),scanned:rows.length,counts,ageCounts:{days60:ages(60),days90:ages(90),days120:ages(120),days180:ages(180)},candidateAgeCounts:{days60:candidateAges(60),days90:candidateAges(90),days120:candidateAges(120),days180:candidateAges(180)},rows,top100:candidateRows.slice(0,100)};
}
