import {prisma} from "@/lib/prisma";
import {getValidAccessToken} from "@/lib/ebay";
import {EbayReadError,classifyEbayReadFailure,type EbayReadProbe} from "@/lib/ebay-readonly";
import {getTrafficReport,type TrafficMetrics} from "@/lib/ebay-analytics";
import {findEligibleItems} from "@/lib/ebay-negotiation";
import {getAdvertisingEligibility,getCampaignAdvertisingContext,type AdvertisingContext} from "@/lib/ebay-marketing";
import {loadInventoryHealth} from "@/lib/inventory-health-data";
import {evaluateSalesVelocityDoctrine,type SalesVelocityAction,type SalesVelocityDecision} from "@/lib/inventory-decision-doctrine";

const DAY=86_400_000;
export type EvidenceState="authoritative"|"supported"|"stale"|"missing";
export type SalesVelocityEvidence={listingId:string;ebayItemId:string;title:string;imageUrl:string|null;currentPrice:number;quantity:number;ageDays:number|null;knownUnitCost:number|null;costComplete:boolean;estimatedGrossSpread:number|null;marginGuardrail:string;units30:number;units90:number;traffic:TrafficMetrics|null;watchers:{value:number|null;quality:"authoritative"|"stale"|"missing";observedAt:string|null};offerEligibility:{eligible:boolean|null;observedAt:string|null};advertising:AdvertisingContext|null;valuation:{suggestedPrice:number|null;confidence:number|null;action:"raise-price"|"lower-price"|null};freshness:{overall:EvidenceState;generatedAt:string};decision:SalesVelocityDecision};
export type SalesVelocityData={generatedAt:string;rows:SalesVelocityEvidence[];probes:EbayReadProbe[];counts:Record<SalesVelocityAction,number>;completeEvidenceCount:number;watcherAudit:{authoritative:number;stale:number;missing:number}};
const failed=(provider:string,error:unknown):EbayReadProbe=>{const classified=classifyEbayReadFailure(error);return{provider,status:"failed",observedAt:new Date().toISOString(),message:`${classified.kind}: ${classified.message}`,...(error instanceof EbayReadError?{httpStatus:error.status}:{})}};
const ok=(provider:string,message:string):EbayReadProbe=>({provider,status:"succeeded",observedAt:new Date().toISOString(),message});

export async function loadSalesVelocity(now=new Date()):Promise<SalesVelocityData>{
  const [inventory,listings]=await Promise.all([loadInventoryHealth(now),prisma.listing.findMany({where:{listingStatus:"active"},select:{id:true,storeId:true,ebayItemId:true,title:true,currentPrice:true,quantity:true,imageUrls:true,authoritativeSource:true,authoritativeObservedAt:true,lastSyncedAt:true,store:{select:{id:true,oauthAccessToken:true,oauthRefreshToken:true,tokenExpiresAt:true,connectionStatus:true}}}})]);
  const healthById=new Map(inventory.rows.map(row=>[row.id,row]));const traffic=new Map<string,TrafficMetrics>(),eligible=new Set<string>(),ads=new Map<string,AdvertisingContext>();const probes:EbayReadProbe[]=[];
  const byStore=new Map<string,typeof listings>();for(const listing of listings){const rows=byStore.get(listing.storeId)??[];rows.push(listing);byStore.set(listing.storeId,rows);}
  for(const storeListings of Array.from(byStore.values())){
    const store=storeListings[0]?.store;if(!store||store.connectionStatus!=="connected"){probes.push({provider:"store-oauth",status:"not-configured",observedAt:now.toISOString(),message:"Connected seller OAuth is unavailable"});continue;}
    let accessToken:string;try{accessToken=(await getValidAccessToken(store)).accessToken;}catch(error){probes.push(failed("store-oauth",error));continue;}
    try{for(let index=0;index<storeListings.length;index+=200){const batch=storeListings.slice(index,index+200);const result=await getTrafficReport({accessToken,listingIds:batch.map((row:{ebayItemId:string})=>row.ebayItemId),start:new Date(now.getTime()-30*DAY),end:now});for(const [id,value] of Array.from(result.entries()))traffic.set(id,value);}probes.push(ok("analytics-traffic",`${traffic.size} listing traffic records returned`));}catch(error){probes.push(failed("analytics-traffic",error));}
    try{const result=await findEligibleItems(accessToken);for(const id of Array.from(result.keys()))eligible.add(id);probes.push(ok("negotiation-eligibility",`${result.size} eBay-confirmed eligible listings returned`));}catch(error){probes.push(failed("negotiation-eligibility",error));}
    try{const advertising=await getAdvertisingEligibility(accessToken);probes.push(ok("advertising-eligibility",advertising.programStatus??"No promoted-listing program status returned"));try{const result=await getCampaignAdvertisingContext(accessToken,advertising);for(const listing of storeListings)ads.set(listing.ebayItemId,result.contexts.get(listing.ebayItemId)??result.defaultContext);probes.push(ok("marketing-campaigns-ads",`${result.contexts.size} current promoted-listing ads joined`));}catch(error){probes.push(failed("marketing-campaigns-ads",error));}}catch(error){probes.push(failed("advertising-eligibility",error));probes.push({provider:"marketing-campaigns-ads",status:"not-configured",observedAt:now.toISOString(),message:"Skipped because advertising eligibility could not be established"});}
  }
  const analyticsSucceeded=probes.some(p=>p.provider==="analytics-traffic"&&p.status==="succeeded"),negotiationSucceeded=probes.some(p=>p.provider==="negotiation-eligibility"&&p.status==="succeeded"),marketingSucceeded=probes.some(p=>p.provider==="marketing-campaigns-ads"&&p.status==="succeeded");
  const rows=listings.flatMap(listing=>{const health=healthById.get(listing.id);if(!health)return[];const observedAt=listing.authoritativeObservedAt??listing.lastSyncedAt;const age=(now.getTime()-observedAt.getTime())/DAY;const watcherQuality:SalesVelocityEvidence["watchers"]["quality"]=listing.authoritativeSource==="ebay-trading-get-item"?(age<=7?"authoritative":"stale"):"missing";const t=traffic.get(listing.ebayItemId)??null;const ad=ads.get(listing.ebayItemId)??null;const cost=health.knownUnitCost;const currentPrice=Number(listing.currentPrice);const decision=evaluateSalesVelocityDoctrine({base:health.doctrine,impressions:t?.impressions??null,views:t?.views??null,clickThroughRate:t?.clickThroughRate??null,conversionRate:t?.conversionRate??null,transactions:t?.transactions??null,watchers:watcherQuality==="missing"?null:health.watchers,watcherQuality,offerEligible:negotiationSucceeded?eligible.has(listing.ebayItemId):null,advertisingEligible:marketingSucceeded?(ad?.eligible??null):null,currentAdRate:ad?.adRate??null,knownUnitCost:cost,costComplete:health.costComplete===true,currentPrice,supportedPriceAction:health.supportedPriceAction,suggestedPrice:health.suggestedPrice,compConfidence:health.compConfidence,trafficFresh:Boolean(t&&now.getTime()-new Date(t.observedAt).getTime()<DAY)});const estimatedGrossSpread=cost==null?null:Math.round((currentPrice-cost)*100)/100;const complete=Boolean(t)&&watcherQuality==="authoritative"&&negotiationSucceeded&&marketingSucceeded&&health.costComplete===true;return[{listingId:listing.id,ebayItemId:listing.ebayItemId,title:listing.title,imageUrl:listing.imageUrls[0]??null,currentPrice,quantity:listing.quantity,ageDays:health.ageDays,knownUnitCost:cost,costComplete:health.costComplete===true,estimatedGrossSpread,marginGuardrail:cost==null?"Unknown — cost basis missing":health.costComplete?`${Math.round((currentPrice-cost)*100)/100} pre-fee gross spread; preserve margin before action`:"Partial cost only — intervention blocked",units30:health.units30,units90:health.units90,traffic:t,watchers:{value:watcherQuality==="missing"?null:health.watchers,quality:watcherQuality,observedAt:observedAt.toISOString()},offerEligibility:{eligible:negotiationSucceeded?eligible.has(listing.ebayItemId):null,observedAt:negotiationSucceeded?now.toISOString():null},advertising:marketingSucceeded?ad:null,valuation:{suggestedPrice:health.suggestedPrice,confidence:health.compConfidence,action:health.supportedPriceAction},freshness:{overall:complete?"authoritative":t||watcherQuality!=="missing"?"supported":"missing",generatedAt:now.toISOString()},decision} satisfies SalesVelocityEvidence];});
  rows.sort((a,b)=>b.decision.confidence.score-a.decision.confidence.score||a.title.localeCompare(b.title));const actions=["SEND OFFER","INCREASE ADS","HOLD / PROTECT MARGIN","TITLE / LISTING REVIEW","REPRICE","MANUAL REVIEW"] as const;const counts=Object.fromEntries(actions.map(action=>[action,rows.filter(row=>row.decision.action===action).length])) as Record<SalesVelocityAction,number>;
  return{generatedAt:now.toISOString(),rows,probes,counts,completeEvidenceCount:rows.filter(row=>row.freshness.overall==="authoritative").length,watcherAudit:{authoritative:rows.filter(row=>row.watchers.quality==="authoritative").length,stale:rows.filter(row=>row.watchers.quality==="stale").length,missing:rows.filter(row=>row.watchers.quality==="missing").length}};
}
