import { Prisma,type ScheduledBid } from "@prisma/client";
import { randomUUID } from "node:crypto";
import { prisma } from "@/lib/prisma";
import { executeBidAttempt,normalizeSnipeOffset,scheduledSubmissionAt,type BidExecutionProvider } from "@/lib/seller-bid-domain";
const ACTIVE=["DRAFT","SCHEDULED","ARMED","SUBMITTING"];
const object=(value:unknown)=>value&&typeof value==="object"&&!Array.isArray(value)?value as Record<string,unknown>:{};
export async function scheduleSandboxBid(input:{opportunityId:string;operatorMaxBid:number;snipeOffsetSeconds?:number;approvedBy:string}){
  const opportunity=await prisma.sellerOpportunityAuction.findUniqueOrThrow({where:{id:input.opportunityId}}),root=object(opportunity.itemSpecifics);
  if(root.environment!=="SANDBOX")throw new Error("Only Sandbox opportunities can be scheduled");
  const buyerUserId=process.env.EBAY_SANDBOX_BUYER_USER_ID;if(!buyerUserId)throw new Error("Sandbox buyer identity is not configured");
  if(!Number.isFinite(input.operatorMaxBid)||input.operatorMaxBid<=0)throw new Error("Operator Max Bid must be positive");
  const offset=Math.max(5,normalizeSnipeOffset(input.snipeOffsetSeconds??7,7)),scheduled=scheduledSubmissionAt(opportunity.endTime.toISOString(),offset);if(!scheduled||new Date(scheduled)<=new Date())throw new Error("Scheduled execution time has passed");
  const valuation=object(root.canonicalSingleValuation),recommended=typeof valuation.maxBid==="number"?valuation.maxBid:null;
  return prisma.$transaction(async tx=>{const existing=await tx.scheduledBid.findFirst({where:{opportunityId:opportunity.id,status:{in:ACTIVE}}});if(existing)return existing;const bid=await tx.scheduledBid.create({data:{idempotencyKey:randomUUID(),opportunityId:opportunity.id,browseItemId:String(root.sandboxBrowseItemId??opportunity.ebayItemId),legacyItemId:opportunity.ebayItemId,listingTitle:opportunity.title,buyerUserId,currency:opportunity.currency,auctionEndAt:opportunity.endTime,operatorMaxBid:new Prisma.Decimal(input.operatorMaxBid.toFixed(2)),recommendedMaxBid:recommended==null?null:new Prisma.Decimal(recommended.toFixed(2)),snipeOffsetSeconds:offset,scheduledExecutionAt:new Date(scheduled),status:"SCHEDULED",approvedBy:input.approvedBy,approvedAt:new Date(),events:{create:{type:"approved_and_scheduled",status:"SCHEDULED",metadata:{operatorMaxBid:input.operatorMaxBid,recommendedMaxBid:recommended,snipeOffsetSeconds:offset} as Prisma.InputJsonValue}}}});return bid;},{isolationLevel:Prisma.TransactionIsolationLevel.Serializable});
}
export async function cancelScheduledBid(id:string,operatorId:string){return prisma.$transaction(async tx=>{const changed=await tx.scheduledBid.updateMany({where:{id,status:{in:["DRAFT","SCHEDULED","ARMED"]}},data:{status:"CANCELLED",cancelledAt:new Date(),completedAt:new Date(),leaseToken:null,leaseExpiresAt:null}});if(changed.count!==1)throw new Error("Bid can no longer be cancelled");await tx.scheduledBidEvent.create({data:{scheduledBidId:id,type:"cancelled",status:"CANCELLED",metadata:{operatorId}}});return tx.scheduledBid.findUniqueOrThrow({where:{id}});});}
export async function recoverScheduledBids(now=new Date()){return prisma.scheduledBid.updateMany({where:{status:{in:["ARMED","SUBMITTING"]},leaseExpiresAt:{lt:now},submittedAt:null},data:{status:"SCHEDULED",leaseToken:null,leaseExpiresAt:null,failureReason:"Recovered after worker lease expiry"}});}
export async function claimDueScheduledBid(now=new Date()){return prisma.$transaction(async tx=>{const row=await tx.scheduledBid.findFirst({where:{status:"SCHEDULED",scheduledExecutionAt:{lte:now}},orderBy:{scheduledExecutionAt:"asc"}});if(!row)return null;const token=randomUUID(),claimed=await tx.scheduledBid.updateMany({where:{id:row.id,status:"SCHEDULED",leaseToken:null},data:{status:"ARMED",armedAt:now,leaseToken:token,leaseExpiresAt:new Date(now.getTime()+60_000)}});return claimed.count===1?tx.scheduledBid.findUnique({where:{id:row.id}}):null;},{isolationLevel:Prisma.TransactionIsolationLevel.Serializable});}
export async function executeClaimedBid(bid:ScheduledBid,provider:BidExecutionProvider,now=new Date()){
  if(!bid.leaseToken)throw new Error("Scheduled bid is not leased");
  const locked=await prisma.scheduledBid.updateMany({where:{id:bid.id,status:"ARMED",leaseToken:bid.leaseToken,submittedAt:null},data:{status:"SUBMITTING",submittingAt:now,lastAttemptAt:now,attemptCount:{increment:1}}});if(locked.count!==1)return prisma.scheduledBid.findUniqueOrThrow({where:{id:bid.id}});
  const result=await executeBidAttempt({browseItemId:bid.browseItemId,legacyItemId:bid.legacyItemId,title:bid.listingTitle,buyerUserId:bid.buyerUserId,auctionEndAt:bid.auctionEndAt.toISOString(),operatorMaxBid:Number(bid.operatorMaxBid),currency:bid.currency,status:"SUBMITTING",alreadySubmitted:Boolean(bid.submittedAt),now},provider);
  const completed=new Date(),status=result.status,providerResult=result.status==="SUBMITTED"?result.result.raw:null,reason=result.status==="SUBMITTED"?null:result.reason;return prisma.$transaction(async tx=>{const updated=await tx.scheduledBid.update({where:{id:bid.id},data:{status,submittedAt:status==="SUBMITTED"?completed:null,completedAt:status==="FAILED"||status==="SKIPPED"?completed:null,actualLatencyMs:status==="SUBMITTED"?bid.auctionEndAt.getTime()-completed.getTime():null,failureReason:reason,providerResult:providerResult?providerResult as Prisma.InputJsonValue:Prisma.JsonNull,leaseToken:null,leaseExpiresAt:null}});await tx.scheduledBidEvent.create({data:{scheduledBidId:bid.id,type:status==="SUBMITTED"?"proxy_bid_submitted":"execution_stopped",status,metadata:(providerResult??{reason}) as Prisma.InputJsonValue}});return updated;});
}
