import {prisma} from "./prisma.ts";
import {loadTitleInspection} from "./title-inspection-data.ts";
import {loadListingRefreshCandidates} from "./listing-refresh-data.ts";
import {loadListingCompleteness} from "./listing-completeness-data.ts";
import {loadSalesVelocity} from "./sales-velocity.ts";
import {SELL_ACTION_TYPES,resolveSellActions,type SellActionCandidate as Candidate,type SellActionRow,type SellActionStatus,type SellActionType} from "./sell-action-center-domain.ts";
import {calculateSellerOffer} from "./governed-seller-offers.ts";
import {getItem,getValidAccessToken} from "./ebay.ts";
import {passesProvenTitleExecutionPolicy} from "./title-inspection-agent.ts";
export {SELL_ACTION_TYPES,resolveSellActions,type SellActionCandidate,type SellActionRow,type SellActionStatus,type SellActionType} from "./sell-action-center-domain.ts";
const band=(value:number):SellActionRow["confidenceBand"]=>value>=90?"HIGH":value>=70?"MEDIUM":"LOW";
const salesAction=(value:string):SellActionType=>value==="SEND OFFER"?"SEND OFFER":value==="INCREASE ADS"?"INCREASE ADS":value==="HOLD / PROTECT MARGIN"?"HOLD / PROTECT":value==="REPRICE"?"REVIEW PRICE":"MANUAL REVIEW";
const providerPrice=(item:Awaited<ReturnType<typeof getItem>>)=>{const value=item.SellingStatus?.CurrentPrice;if(typeof value==="number")return value;if(typeof value==="string")return Number(value);if(value&&typeof value==="object")return Number(value["#text"]);return NaN;};

export async function loadSellActionCenter(now=new Date()){
  const [titles,refresh,completeness,velocity,recent]=await Promise.all([loadTitleInspection(now),loadListingRefreshCandidates(now),loadListingCompleteness(now),loadSalesVelocity(now),prisma.ebayActionExecution.findMany({where:{status:"verified",createdAt:{gte:new Date(now.getTime()-30*86_400_000)}},orderBy:{createdAt:"desc"},take:100,include:{listing:{select:{id:true,ebayItemId:true,title:true,currentPrice:true,itemSpecifics:true}}}})]);
  const eligibleRows=velocity.rows.filter(row=>row.offerEligibility.eligible===true).sort((a,b)=>a.ebayItemId.localeCompare(b.ebayItemId));
  const [offerListings,activeOfferConflicts,recentSkips]=await Promise.all([prisma.listing.findMany({where:{id:{in:eligibleRows.map(row=>row.listingId)}},include:{store:true}}),prisma.ebayActionExecution.findMany({where:{listingId:{in:eligibleRows.map(row=>row.listingId)},status:{in:["approved","executing","partial_failure","manual_reconciliation_required"]}},select:{listingId:true}}),prisma.operatorDecision.findMany({where:{listingId:{in:eligibleRows.map(row=>row.listingId)},recommendedAction:"SEND_OFFER",decision:"skip",decidedAt:{gte:new Date(now.getTime()-24*60*60*1000)}},select:{listingId:true}})]);
  const offerListingById=new Map(offerListings.map(row=>[row.id,row])),conflictedOffers=new Set(activeOfferConflicts.map(row=>row.listingId)),skippedOffers=new Set(recentSkips.map(row=>row.listingId));const canaryIds=new Set(eligibleRows.filter(row=>!skippedOffers.has(row.listingId)).slice(0,5).map(row=>row.listingId));
  const liveOffers=new Map<string,Awaited<ReturnType<typeof getItem>>>();await Promise.all(offerListings.filter(row=>canaryIds.has(row.id)).map(async listing=>{try{const {accessToken}=await getValidAccessToken(listing.store);liveOffers.set(listing.id,await getItem(accessToken,listing.ebayItemId));}catch{}}));
  const candidates:Candidate[]=[],priceById=new Map(velocity.rows.map(row=>[row.listingId,row.currentPrice]));const sportById=new Map(completeness.assessments.map(row=>[row.listingId,row.beforeState.Sport?.[0]??"Unknown"]));
  for(const row of velocity.rows){const actionType=salesAction(row.decision.action),offer=actionType==="SEND OFFER",ads=actionType==="INCREASE ADS",price=actionType==="REVIEW PRICE";const executable=false,status:SellActionStatus=actionType==="HOLD / PROTECT"?"REVIEW":row.decision.confidence.score<60?"BLOCKED":"REVIEW";candidates.push({listingId:row.listingId,itemId:row.ebayItemId,title:row.title,currentPrice:row.currentPrice,actionType,confidence:row.decision.confidence.score,confidenceBand:band(row.decision.confidence.score),reason:row.decision.why,evidence:[`30/90-day sales ${row.units30}/${row.units90}`,`Watchers ${row.watchers.value??"unavailable"} (${row.watchers.quality})`,row.traffic?`Impressions ${row.traffic.impressions} · views ${row.traffic.views}`:"Traffic unavailable",`Offer eligible ${row.offerEligibility.eligible??"unknown"}`,`Ad rate ${row.advertising?.adRate??"unavailable"}`],warning:row.marginGuardrail,status,source:"Sales Velocity",sport:sportById.get(row.listingId)??"Unknown",freshness:row.freshness.overall,operatorAction:executable?"Approve":"Review",buyerIntent:offer?3:0,velocity:offer?3:ads?2:price?2:actionType==="HOLD / PROTECT"?1:0,risk:actionType==="HOLD / PROTECT"?3:1,freshnessScore:row.freshness.overall==="authoritative"?3:row.freshness.overall==="supported"?2:0});
    if(row.offerEligibility.eligible===true&&!skippedOffers.has(row.listingId)){const economicsKnown=row.costComplete&&row.knownUnitCost!=null,listing=offerListingById.get(row.listingId),live=liveOffers.get(row.listingId),currentPrice=live?providerPrice(live):NaN,providerFresh=Boolean(listing?.listingStatus==="active"&&live&&String(live.SellingStatus?.ListingStatus??"").toLowerCase()==="active"&&Number.isFinite(currentPrice)&&currentPrice>0),conflicted=conflictedOffers.has(row.listingId),canary=canaryIds.has(row.listingId),offer=calculateSellerOffer(providerFresh?currentPrice:row.currentPrice),spread=economicsKnown?Math.round((offer.proposedPrice-row.knownUnitCost!)*100)/100:null,margin=economicsKnown&&offer.proposedPrice>0?Math.round(spread!/offer.proposedPrice*10000)/100:null,marginSafe=!economicsKnown||offer.proposedPrice>=row.knownUnitCost!*1.2;const executable=canary&&providerFresh&&!conflicted&&marginSafe;candidates.push({listingId:row.listingId,itemId:row.ebayItemId,title:live?.Title??row.title,currentPrice:providerFresh?currentPrice:row.currentPrice,actionType:"SEND OFFER",confidence:economicsKnown?85:70,confidenceBand:"MEDIUM",reason:"eBay currently identifies this listing as eligible for a seller-initiated offer. The governed proposal is exactly 5% and requires explicit operator approval.",evidence:[`Negotiation eligible ${row.offerEligibility.observedAt}`,`Live GetItem ${providerFresh?"verified":"unavailable"}`,`30/90-day sales ${row.units30}/${row.units90}`,`Watchers ${row.watchers.value??"unavailable"} (${row.watchers.quality})`],warning:!providerFresh?"A live provider title/price read could not be verified; approval is unavailable.":conflicted?"Another governed action is active for this listing.":!marginSafe?"Known economics fail the existing 20% known-cost margin guardrail.":economicsKnown?row.marginGuardrail:"COST BASIS UNKNOWN · OPERATOR OVERRIDE REQUIRED · discount may not exceed 5%.",status:executable?"EXECUTABLE WITH APPROVAL":"BLOCKED",source:"Negotiation Eligibility",sport:sportById.get(row.listingId)??"Unknown",freshness:providerFresh?"authoritative":"stale",operatorAction:executable?"Approve exact 5% offer":"Unavailable",offer:{proposedPrice:offer.proposedPrice,discountPct:offer.discountPct,concession:offer.concession,eligibilityObservedAt:row.offerEligibility.observedAt??now.toISOString(),watchers:row.watchers.value,watcherQuality:row.watchers.quality,units30:row.units30,units90:row.units90,knownUnitCost:row.knownUnitCost,costComplete:row.costComplete,estimatedGrossSpread:spread,estimatedGrossMarginPct:margin,overrideRequired:!economicsKnown},buyerIntent:3,velocity:3,risk:executable?3:0,freshnessScore:providerFresh?3:0});}}
  for(const row of titles.recommendations){const executable=passesProvenTitleExecutionPolicy(row);candidates.push({listingId:row.listingId,itemId:row.ebayItemId,title:row.currentTitle,currentPrice:priceById.get(row.listingId)??0,actionType:"OPTIMIZE TITLE",confidence:row.confidence,confidenceBand:band(row.confidence),reason:row.reason,evidence:row.additions.map(item=>`${item.aspect}: ${item.value} (${item.confidence}%)`),warning:"Title-only governed change; provider state is revalidated before execution.",status:executable?"EXECUTABLE WITH APPROVAL":"REVIEW",source:"Title Inspection",sport:sportById.get(row.listingId)??"Unknown",freshness:"supported",operatorAction:executable?"Approve exact title":"Review title",buyerIntent:0,velocity:2,risk:executable?3:2,freshnessScore:2});}
  for(const row of refresh.rows.filter(row=>row.classification==="HIGH-CONFIDENCE REFRESH"||row.classification==="REVIEW")){candidates.push({listingId:row.listingId,itemId:row.ebayItemId,title:row.title,currentPrice:row.currentPrice,actionType:"REFRESH LISTING",confidence:row.confidence,confidenceBand:band(row.confidence),reason:row.reason,evidence:[`${row.ageDays??"Unknown"} days old`,`30/90-day sales ${row.units30}/${row.units90}`,`Views ${row.views30??"unavailable"}`,`Watchers ${row.watchers??"unavailable"}`],warning:"Execution blocked: pre-end relist verification and seller payment-terms prerequisites remain unresolved.",status:"BLOCKED",source:"Listing Refresh",sport:sportById.get(row.listingId)??"Unknown",freshness:row.trafficQuality,operatorAction:"Review candidate",buyerIntent:0,velocity:2,risk:0,freshnessScore:row.trafficQuality==="authoritative"?3:1});}
  for(const row of completeness.assessments.filter(row=>row.disposition!=="COMPLETE")){const confidence=Math.max(0,...row.proposedPatch.map(item=>item.confidence));candidates.push({listingId:row.listingId,itemId:row.ebayItemId,title:row.title,currentPrice:priceById.get(row.listingId)??0,actionType:"FIX LISTING DATA",confidence,confidenceBand:band(confidence),reason:row.reason,evidence:[`Missing: ${row.missingFields.join(", ")||"none"}`,`Malformed: ${row.malformedFields.join(", ")||"none"}`,`Conflicts: ${row.conflicts.length}`],warning:"Read-only proposal; no listing-data execution control is enabled.",status:row.disposition==="AUTO-FIX"?"REVIEW":"BLOCKED",source:"Listing Completeness",sport:sportById.get(row.listingId)??"Unknown",freshness:row.authoritative?"authoritative":"missing",operatorAction:"Review listing data",buyerIntent:0,velocity:1,risk:row.disposition==="AUTO-FIX"?2:0,freshnessScore:row.authoritative?3:0});}
  const completed:SellActionRow[]=recent.map((execution,index)=>({listingId:execution.listing.id,itemId:execution.listing.ebayItemId,title:execution.listing.title,currentPrice:Number(execution.listing.currentPrice),actionType:execution.action==="OPTIMIZE_TITLE"?"OPTIMIZE TITLE":execution.action==="END_SELL_SIMILAR"?"REFRESH LISTING":execution.action==="SEND_OFFER"?"SEND OFFER":execution.action==="LOWER_PRICE"||execution.action==="RAISE_PRICE"?"REVIEW PRICE":"MANUAL REVIEW",confidence:100,confidenceBand:"HIGH",reason:"Governed action completed and provider-verified.",evidence:[`Execution ${execution.id}`,`Verified ${execution.providerVerifiedAt?.toISOString()??"unknown"}`],warning:"Observation window is still required before judging outcome.",status:"COMPLETED",source:"Governed Execution",sport:"Unknown",freshness:"verified",priority:-index,operatorAction:"View audit",alternatives:[]}));
  const resolved=resolveSellActions(candidates,completed),counts=Object.fromEntries(SELL_ACTION_TYPES.map(type=>[type,resolved.rows.filter(row=>row.actionType===type&&row.status!=="COMPLETED").length])) as Record<SellActionType,number>;return{generatedAt:now.toISOString(),...resolved,counts,highConfidence:resolved.rows.filter(row=>(row.status==="EXECUTABLE"||row.status==="EXECUTABLE WITH APPROVAL")&&row.confidenceBand==="HIGH").length,needsReview:resolved.rows.filter(row=>row.status==="REVIEW").length,blocked:resolved.rows.filter(row=>row.status==="BLOCKED").length,recentlyCompleted:completed.length,probes:velocity.probes};
}
