import { parseCardIdentity } from "./comp-validation/identity.ts";

export const TITLE_INSPECTION_RULE_VERSION = "title-inspection-v2.0.0";
export type TitleInspectionStatus = "RECOMMEND" | "NO_CHANGE" | "REVIEW";
export type TitleInspectionClassification = "READY TO APPROVE" | "REVIEW" | "NO CHANGE NEEDED" | "DO NOT TOUCH";
export type TitleEvidence = { aspect:string; value:string; source:"ebay-item-specific"; observedAt:string };
export type TitleQuality = { searchValue:number; identityCompleteness:number; readability:number; redundancy:number; characterEfficiency:number; total:number };
export type TitleInspection = { listingId:string; ebayItemId:string; currentTitle:string; proposedTitle:string|null; status:TitleInspectionStatus; classification:TitleInspectionClassification; confidence:number; reason:string; additions:Array<{aspect:string;value:string;confidence:number}>; changes:Array<{aspect:string;value:string;confidence:number;operation:"ADD"|"MOVE"|"NORMALIZE"}>; evidence:TitleEvidence[]; conflicts:string[]; missingEvidence:string[]; currentLength:number; proposedLength:number|null; qualityBefore:TitleQuality; qualityAfter:TitleQuality|null; qualityImprovement:number; removedText:string[]; reordered:boolean; legacyDuplicateDiscriminator:boolean; ruleVersion:string; inspectedAt:string };
type Family={canonical:string;confidence:number;names:readonly string[];validate:(value:string)=>boolean;order:number};
const FAMILIES:readonly Family[]=[
 {canonical:"year",confidence:99,names:["Year","Season","Year Manufactured","Release Year"],order:10,validate:value=>/^(19|20)\d{2}(?:-(?:19|20)?\d{2})?$/.test(value)},
 {canonical:"manufacturer",confidence:97,names:["Manufacturer","Brand"],order:20,validate:value=>/^(?:Topps|Bowman|Panini|Donruss|Score|Upper Deck|Leaf)$/i.test(value.trim())},
 {canonical:"set",confidence:97,names:["Set","Product"],order:30,validate:value=>/^[A-Za-z0-9][A-Za-z0-9 &.'/#()-]{1,64}$/.test(value)},
 {canonical:"player",confidence:99,names:["Player/Athlete","Player","Athlete"],order:40,validate:value=>/^[A-Za-z][A-Za-z .'-]{2,59}$/.test(value)&&value.trim().split(/\s+/).length>=2},
 {canonical:"cardNumber",confidence:99,names:["Card Number"],order:90,validate:value=>/\d/.test(value)&&(/^#?\d{1,3}$/.test(value)||/^#?(?=[A-Za-z0-9-]{1,20}$)(?=[A-Za-z0-9-]*[A-Za-z])[A-Za-z0-9]+(?:-[A-Za-z0-9]+)*$/.test(value))},
] as const;
const exact=(a:string,b:string)=>a.localeCompare(b,undefined,{sensitivity:"accent"})===0;
const normalized=(value:string)=>value.toLocaleLowerCase().replace(/[^a-z0-9]+/g," ").trim();
const meaningful=(value:string)=>Boolean(value.trim())&&!/^(n\/?a|none|does not apply|unknown|unspecified|not applicable)$/i.test(value.trim());
const clamp=(value:number)=>Math.max(0,Math.min(100,Math.round(value)));
export const trailingPeriodSuffix=(title:string)=>title.match(/\.{1,3}\s*$/)?.[0].trim()??"";
export const legacyDuplicateTitleKey=(title:string)=>title.replace(/\.{1,3}\s*$/,"").trim().toLocaleLowerCase().replace(/\s+/g," ");
export function hasLegacyDuplicateDiscriminator(title:string,siblingTitles:string[]){const key=legacyDuplicateTitleKey(title),matching=siblingTitles.filter(candidate=>legacyDuplicateTitleKey(candidate)===key);return Boolean(trailingPeriodSuffix(title))&&new Set(matching.map(candidate=>candidate.trim())).size>1;}
export function hasUnresolvedDuplicateFamily(title:string,siblingTitles:string[]){const key=legacyDuplicateTitleKey(title);return siblingTitles.filter(candidate=>legacyDuplicateTitleKey(candidate)===key).length>1;}
function specifics(value:unknown){const result:Record<string,string[]>={};if(!value||typeof value!=="object"||Array.isArray(value))return result;for(const[name,raw]of Object.entries(value as Record<string,unknown>)){const values=(Array.isArray(raw)?raw:[raw]).filter((item):item is string=>typeof item==="string"&&meaningful(item)).map(item=>item.trim());if(values.length)result[name]=Array.from(new Set(values));}return result;}
function titleContains(title:string,value:string,canonical:string){if(canonical==="cardNumber"){const escaped=value.replace(/^#/,"").replace(/[.*+?^${}()|[\]\\]/g,"\\$&");return new RegExp(`(?:(?:#\\s*|\\bno\\.?\\s*|\\bcard\\s*(?:number|no\\.?|#)?\\s+)${escaped}(?:$|[^a-z0-9])|\\b${escaped}\\s+of\\s+\\d+\\b)`,"i").test(title);}const source=normalized(title),target=normalized(value);if(!target)return false;if(canonical==="player")return source.replace(/\s+/g,"").includes(target.replace(/\s+/g,""));if(canonical==="set"){const tokens=target.split(" ").filter(token=>!/^(?:19|20)\d{2}$/.test(token)&&token.length>1&&!['topps','bowman','panini','donruss','score'].includes(token));if(tokens.length&&tokens.every(token=>source.split(" ").includes(token)))return true;}return source.includes(target);}
const manufacturerFamily=(value:string)=>/^(topps|bowman)$/i.test(value)?"topps":/^(panini|donruss|score)$/i.test(value)?"panini":normalized(value);
function identityConflict(canonical:string,value:string,title:string){const identity=parseCardIdentity(title),target=normalized(value.replace(/^#/,""));if(canonical==="year")return identity.year!=null&&!target.startsWith(String(identity.year));if(canonical==="manufacturer")return identity.manufacturer!=null&&manufacturerFamily(identity.manufacturer)!==manufacturerFamily(value);if(canonical==="set")return identity.setName!=null&&!normalized(identity.setName).includes(target)&&!target.includes(normalized(identity.setName));if(canonical==="player"&&identity.player){const compact=(text:string)=>normalized(text).replace(/\s+/g,"");return compact(identity.player)!==compact(value);}if(canonical==="cardNumber"){if(identity.cardNumber&&normalized(identity.cardNumber)!==target)return true;const printRun=title.match(/\/\s*(\d+)\b/)?.[1];if(/^\d+$/.test(target)&&(Number(target)===identity.printRun||Number(target)===identity.year||target===printRun))return true;}return false;}
function quality(title:string,supported:Array<{canonical:string;value:string}>):TitleQuality{const words=normalized(title).split(/\s+/).filter(Boolean),unique=new Set(words),present=supported.filter(row=>titleContains(title,row.value,row.canonical)).length;const searchValue=clamp(35+present*11),identityCompleteness=clamp(supported.length?present/supported.length*100:35),readability=clamp(100-Math.max(0,words.length-14)*4-(title.includes("  ")?10:0)-(title===title.toUpperCase()?12:0)),redundancy=clamp(words.length?unique.size/words.length*100:0),characterEfficiency=clamp((present*14+20)/Math.max(1,title.length)*100);return{searchValue,identityCompleteness,readability,redundancy,characterEfficiency,total:clamp(searchValue*.28+identityCompleteness*.28+readability*.18+redundancy*.14+characterEfficiency*.12)};}
function normalizeTitle(value:string){return value.trim().replace(/\s+/g," ").replace(/\s+([,;:])/g,"$1").replace(/([,;:])(?=\S)/g,"$1 ");}
function insert(title:string,additions:Array<{canonical:string;value:string;order:number}>,preserveTrailingPeriods:boolean){const suffix=preserveTrailingPeriods?trailingPeriodSuffix(title):"";let result=normalizeTitle(suffix?title.slice(0,title.lastIndexOf(suffix)):title),reordered=false;for(const row of additions.sort((a,b)=>a.order-b.order)){if(row.order===10){result=`${row.value} ${result}`;reordered=true;continue;}if(row.order===90){result=`${result} ${row.value}`;continue;}const year=result.match(/^(?:19|20)\d{2}(?:-(?:19|20)?\d{2})?\b/)?.[0];if(year){result=`${year} ${row.value} ${result.slice(year.length).trim()}`;reordered=true;}else result=`${row.value} ${result}`;}result=normalizeTitle(result);return{title:suffix?`${result}${suffix}`:result,reordered};}
export function inspectListingTitle(input:{listingId:string;ebayItemId:string;title:string;itemSpecifics:unknown;evidenceObservedAt:Date|null;now?:Date;excludeReason?:string|null;legacyDuplicateDiscriminator?:boolean}):TitleInspection{
 const now=input.now??new Date(),inspectedAt=now.toISOString(),before=specifics(input.itemSpecifics),evidence:TitleEvidence[]=[],additions:Array<{aspect:string;value:string;confidence:number}>=[],changes:TitleInspection["changes"]=[],conflicts:string[]=[],missingEvidence:string[]=[],supported:Array<{canonical:string;value:string}>=[];
 if(input.excludeReason)missingEvidence.push(input.excludeReason);if(!Object.keys(before).length)missingEvidence.push("Authoritative eBay item specifics are unavailable");if(!input.evidenceObservedAt)missingEvidence.push("Authoritative listing observation time is unavailable");else if(now.getTime()-input.evidenceObservedAt.getTime()>7*86_400_000)missingEvidence.push("Authoritative listing evidence is older than 7 days");
 for(const family of FAMILIES){const matches=Object.entries(before).filter(([name])=>family.names.some(candidate=>exact(candidate,name))).flatMap(([aspect,values])=>values.map(value=>({aspect,value}))),valid=matches.filter(row=>family.validate(row.value)),unique=Array.from(new Set(valid.map(row=>normalized(row.value))));if(matches.length&&valid.length!==matches.length){conflicts.push(`${family.canonical}: malformed or unsupported seller value`);continue;}if(unique.length>1){conflicts.push(`${family.canonical}: multiple conflicting seller values`);continue;}const selected=valid[0];if(!selected)continue;supported.push({canonical:family.canonical,value:selected.value});if(titleContains(input.title,selected.value,family.canonical))continue;if(identityConflict(family.canonical,selected.value,input.title)){conflicts.push(`${family.canonical}: seller value conflicts with independently parsed title identity`);continue;}const value=family.canonical==="cardNumber"&&!selected.value.startsWith("#")?`#${selected.value}`:selected.value;additions.push({aspect:selected.aspect,value,confidence:family.confidence});changes.push({aspect:selected.aspect,value,confidence:family.confidence,operation:"ADD"});evidence.push({aspect:selected.aspect,value:selected.value,source:"ebay-item-specific",observedAt:input.evidenceObservedAt?.toISOString()??inspectedAt});}
 const setAddition=additions.find(row=>/^(set|product)$/i.test(row.aspect));if(setAddition)for(let i=additions.length-1;i>=0;i--){const row=additions[i];if(/^(manufacturer|brand)$/i.test(row.aspect)&&normalized(setAddition.value).includes(normalized(row.value))){additions.splice(i,1);const ci=changes.findIndex(change=>change.aspect===row.aspect);if(ci>=0)changes.splice(ci,1);}}
 const qualityBefore=quality(input.title,supported),base={listingId:input.listingId,ebayItemId:input.ebayItemId,currentTitle:input.title,evidence,conflicts,missingEvidence,currentLength:input.title.length,ruleVersion:TITLE_INSPECTION_RULE_VERSION,inspectedAt,qualityBefore,removedText:[] as string[],legacyDuplicateDiscriminator:Boolean(input.legacyDuplicateDiscriminator)};
 if(conflicts.length)return{...base,proposedTitle:null,status:"REVIEW",classification:"DO NOT TOUCH",confidence:0,reason:"Conflicting or malformed authoritative identity evidence prevents a deterministic title proposal.",additions:[],changes:[],proposedLength:null,qualityAfter:null,qualityImprovement:0,reordered:false};
 if(missingEvidence.length)return{...base,proposedTitle:null,status:"REVIEW",classification:"REVIEW",confidence:0,reason:"Fresh authoritative item-specific evidence and an unobstructed observation window are required.",additions:[],changes:[],proposedLength:null,qualityAfter:null,qualityImprovement:0,reordered:false};
 if(!additions.length)return{...base,proposedTitle:null,status:"NO_CHANGE",classification:"NO CHANGE NEEDED",confidence:99,reason:"No supported high-value identity attribute is missing from the current title.",additions:[],changes:[],evidence:[],proposedLength:null,qualityAfter:null,qualityImprovement:0,reordered:false};
 const ordered=additions.map(addition=>{const family=FAMILIES.find(item=>item.names.some(name=>exact(name,addition.aspect)))!;return{canonical:family.canonical,value:addition.value,order:family.order}}),proposal=insert(input.title,ordered,Boolean(input.legacyDuplicateDiscriminator)),proposedTitle=proposal.title,qualityAfter=quality(proposedTitle,supported),improvement=qualityAfter.total-qualityBefore.total,confidence=Math.min(...additions.map(row=>row.confidence));
 if(proposedTitle.length>80)return{...base,proposedTitle:null,status:"REVIEW",classification:"REVIEW",confidence:0,reason:"A useful deterministic rewrite does not fit eBay's 80-character limit without removing unsupported seller text.",additions,changes,proposedLength:proposedTitle.length,qualityAfter,qualityImprovement:improvement,reordered:proposal.reordered};
 if(improvement<3)return{...base,proposedTitle:null,status:"NO_CHANGE",classification:"NO CHANGE NEEDED",confidence,reason:"The supported change does not produce a meaningful title-quality improvement.",additions:[],changes:[],proposedLength:proposedTitle.length,qualityAfter,qualityImprovement:improvement,reordered:proposal.reordered};
 return{...base,proposedTitle,status:"RECOMMEND",classification:confidence>=99?"READY TO APPROVE":"REVIEW",confidence,reason:`Adds ${additions.map(row=>`${row.aspect} ${row.value}`).join(", ")} at an identity-aware position; modeled title quality improves ${improvement} points without removing unsupported seller text.${input.legacyDuplicateDiscriminator?" The legacy trailing-period duplicate discriminator is preserved.":""}`,additions,changes,proposedLength:proposedTitle.length,qualityAfter,qualityImprovement:improvement,reordered:proposal.reordered};
}
export function passesProvenTitleExecutionPolicy(row:TitleInspection){
 if(row.status!=="RECOMMEND"||!row.proposedTitle||row.confidence<97||row.qualityImprovement<8||row.proposedTitle.length>80||row.conflicts.length||row.missingEvidence.length)return false;
 if(!/^(?:19|20)\d{2}(?:-(?:19|20)?\d{2})?\b/.test(row.currentTitle))return false;
 return row.additions.length>0&&row.additions.every(addition=>addition.aspect==="Card Number"||(/^Manufacturer$/i.test(addition.aspect)&&((/^Panini$/i.test(addition.value)&&/\b(?:Prizm|Select|Mosaic|Absolute|Immaculate|Spectra|National Treasures|Gold Standard|Phoenix|Obsidian|Donruss Optic)\b/i.test(row.currentTitle))||(/^Topps$/i.test(addition.value)&&/\b(?:Stadium Club|Finest|Tokyo Series)\b/i.test(row.currentTitle)))));
}
