import Link from "next/link";
import { Prisma } from "@prisma/client";
import { loadDailyOperations, loadDataHealth } from "@/lib/daily-operations";
import { loadCommerceDashboard } from "@/lib/commerce-dashboard";
import { prisma } from "@/lib/prisma";
import { loadInventoryHealth } from "@/lib/inventory-health-data";

export const dynamic = "force-dynamic";
const usd=(value:number)=>new Intl.NumberFormat("en-US",{style:"currency",currency:"USD",maximumFractionDigits:0}).format(value);
const pct=(value:number)=>`${value.toFixed(1)}%`;

export default async function TodayPage(){
  const [ops,commerce,health,inventoryRows,activeListings,inventoryHealth]=await Promise.all([
    loadDailyOperations(),loadCommerceDashboard(),loadDataHealth(),
    prisma.$queryRaw<Array<{value:Prisma.Decimal}>>(Prisma.sql`SELECT COALESCE(SUM("currentPrice" * quantity),0) AS value FROM "Listing" WHERE "listingStatus"='active'`),
    prisma.listing.count({where:{listingStatus:"active"}}),loadInventoryHealth(),
  ]);
  const inventoryValue=Number(inventoryRows[0]?.value??0);
  const pricingCoverage=activeListings?ops.actionablePricing/activeListings*100:0;
  const staleCapital=commerce.capital.stale.reduce((sum,row)=>sum+(row.knownCapital??0),0);
  const pulse=[
    ["Active inventory value",usd(inventoryValue),`${activeListings.toLocaleString()} active listings`],
    ["Sales · 7 days",usd(commerce.summary.sales7),"Authoritative order totals"],
    ["Sales · 30 days",usd(commerce.summary.sales30),"Non-cancelled orders"],
    ["Orders · 30 days",commerce.summary.orders30.toLocaleString(),`${commerce.summary.units30.toLocaleString()} units`],
    ["Average selling price",usd(commerce.summary.averageSellingPrice),"Authoritative line revenue per unit"],
    ["Known-cost margin",commerce.summary.knownCostMargin==null?"Awaiting costs":usd(commerce.summary.knownCostMargin),commerce.summary.knownCostMarginPct==null?"Only entered costs are included":`${pct(commerce.summary.knownCostMarginPct)} of covered net basis`],
    ["Known-cost ROI",commerce.summary.aggregateRoi==null?"Awaiting invested cost":pct(commerce.summary.aggregateRoi),"Acquisition + grading investment only"],
    ["Sales cost coverage",pct(commerce.coverage.salesDollarCostCoveragePct),`${commerce.coverage.unitsWithCost.toLocaleString()} units with entered costs`],
    ["Known inventory capital",commerce.capital.totalKnownCapital==null?"Awaiting costs":usd(commerce.capital.totalKnownCapital),`${commerce.capital.listings.toLocaleString()} active listings with known costs`],
    ["Sales linkage",pct(ops.linkageHealth.recent30.percent),`${ops.linkageHealth.recent30.linked}/${ops.linkageHealth.recent30.total} lines · 30d`],
    ["Pricing coverage",pct(pricingCoverage),`${ops.actionablePricing} supported · ${ops.pricingEvidenceUnavailable} unavailable`],
  ];
  return <main className="page">
    <section style={{display:"flex",justifyContent:"space-between",gap:20,alignItems:"end",flexWrap:"wrap",marginBottom:24}}><div><div className="eyebrow">Daily command center</div><h1 style={{fontSize:"clamp(32px,5vw,54px)",margin:"7px 0 8px"}}>What deserves attention today?</h1><p style={{maxWidth:720,margin:0}}>A prioritized operating view of sales, inventory, pricing evidence, profitability, and exceptions. Legends never changes an eBay listing without approval.</p></div><div className="pill">Updated {ops.generatedAt.toLocaleString()}</div></section>
    <section className="metric-grid" aria-label="Business pulse">{pulse.map(([label,value,detail])=><div className="metric" key={label}><div className="metric-label">{label}</div><div className="metric-value">{value}</div><div className="metric-detail">{detail}</div></div>)}</section>
    <section className="panel" style={{marginTop:20}}><div className="section-heading"><div><div className="eyebrow">Overall inventory health</div><h2 style={{margin:"5px 0"}}>{Math.round(inventoryHealth.portfolio.listingWeightedHealth)} / 100 · {inventoryHealth.portfolio.listingWeightedHealth>=75?"Healthy":inventoryHealth.portfolio.listingWeightedHealth>=60?"Needs attention":"At risk"}</h2><p style={{margin:0}}>Economically weighted: {Math.round(inventoryHealth.portfolio.economicallyWeightedHealth)} / 100 using listed-value exposure.</p></div><Link href="/inventory-health">Open Inventory Health →</Link></div><div className="metric-grid" style={{marginTop:14}}>{inventoryHealth.portfolio.pareto.slice(0,4).map(row=><Link className="metric" key={row.issue} href={`/review-session?issue=${row.issue}`}><div className="metric-label">{row.label}</div><div className="metric-value">{row.listingCount.toLocaleString()}</div><div className="metric-detail">{usd(row.listedExposure)} exposure · {pct(row.cumulativeImpactPct)} cumulative impact</div></Link>)}</div></section>
    <section className="panel" style={{marginTop:18}}><div className="eyebrow">Top inventory actions</div><h2>What should I do today?</h2><p>The highest-value, most actionable inventory decisions. Legends recommends; Josh decides.</p><div className="action-list">{inventoryHealth.rows.slice().sort((a,b)=>b.priorityScore-a.priorityScore).slice(0,10).map(row=><article className="action-card" key={row.id}><div><div className="action-score">{row.priorityScore}</div><div className="action-category">priority</div></div><div><div className="action-category">{row.rootCauseLabel}</div><strong>{row.recommendedAction}: {row.title}</strong><div style={{color:"var(--text-secondary)",fontSize:12,marginTop:5}}>{row.recommendationWhy} · {usd(row.listedExposure)} listed exposure</div></div><Link href={`/review-session?issue=${row.issue}`}>Review →</Link></article>)}</div></section>
    <section className="panel" style={{marginTop:18}}><div className="eyebrow">Stale-capital intelligence</div><h2>{commerce.capital.stale.length?`${usd(staleCapital)} visible in 90+ day inventory`:"No known stale capital"}</h2><p>Capital includes only entered per-unit costs multiplied by available quantity. Missing cost components remain missing and are never estimated.</p><div className="action-list">{commerce.capital.stale.slice(0,5).map(row=><article className="action-card" key={row.id}><div><div className="action-score">{row.ageDays??"?"}</div><div className="action-category">days</div></div><div><strong>{row.title}</strong><div style={{color:"var(--text-secondary)",fontSize:12,marginTop:5}}>{usd(row.knownCapital!)} known capital · {row.quantity} available · {row.watchers} watchers · {row.soldUnits} sold</div></div><Link href="/inventory">Review →</Link></article>)}</div>{commerce.capital.stale.length===0&&<Link href="/cost-basis">Improve cost coverage →</Link>}</section>
    {ops.pricingActions.length>0&&<section className="panel" style={{marginTop:18}}><div className="eyebrow">Supported pricing actions</div><h2>Market-backed next moves</h2><div className="action-list">{ops.pricingActions.map(row=><article className="action-card" key={row.id} style={{borderLeft:`3px solid ${row.type==="raise-price"?"var(--success)":"var(--danger)"}`}}><div><div className="confidence-value">{row.confidence}</div><div className={`badge ${row.confidence>=75?"badge-success":"badge-warning"}`}>{row.confidence>=90?"Very High":row.confidence>=75?"High":"Moderate"}</div></div><div><strong>{row.type==="lower-price"?"Lower":"Raise"} to {usd(row.suggestedPrice)}</strong><div>{row.title}</div><div style={{color:"var(--text-secondary)",fontSize:12,marginTop:5}}>Current {usd(row.currentPrice)} · Market {usd(row.marketValue)} · {row.compCount} qualifying sales{row.evidenceWindowDays?` over ${row.evidenceWindowDays} days`:""}{row.medianSoldPrice!=null?` · median ${usd(row.medianSoldPrice)}`:""}</div></div><Link href={`/comp-validation?listingId=${row.listingId}`}>Explain →</Link></article>)}</div></section>}
    <section className="panel" style={{marginTop:18}}><div className="eyebrow">Data health</div><h2>Can Legends support today’s decisions?</h2><div className="metric-grid"><Health label="Live market evidence" value={health.provider.liveReady&&health.provider.mode==="live"?"Ready":"Unavailable"} detail={health.provider.liveReady?health.provider.providerName:"Pricing remains fail-closed"} good={health.provider.liveReady}/><Health label="Listing freshness" value={health.listingSyncAgeHours==null?"Unknown":`${health.listingSyncAgeHours}h ago`} detail={`${health.connectedStores}/${health.totalStores} stores connected`} good={health.listingSyncAgeHours!=null&&health.listingSyncAgeHours<=24}/><Health label="Order freshness" value={health.orderSyncAgeHours==null?"Unknown":`${health.orderSyncAgeHours}h ago`} detail={`${health.orderReadyStores}/${health.totalStores} stores order-ready`} good={health.orderSyncAgeHours!=null&&health.orderSyncAgeHours<=24}/><Health label="Cost coverage" value={pct(health.costCoveragePct)} detail={`${health.activeWithCost.toLocaleString()} of ${health.activeListings.toLocaleString()} active listings`} good={health.costCoveragePct>=50}/><Health label="Pricing coverage" value={pct(health.pricingCoveragePct)} detail={`${health.livePricing} supported decisions`} good={health.livePricing>0}/><Health label="Review backlog" value={health.openReconciliation.toLocaleString()} detail="Sales links awaiting review" good={health.openReconciliation===0}/><Health label="Job exceptions" value={(health.failedJobs+health.staleJobs).toLocaleString()} detail={`${health.failedJobs} failed · ${health.staleJobs} stale`} good={health.failedJobs+health.staleJobs===0}/></div></section>
    <div style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(300px,1fr))",gap:16,marginTop:18}}><section className="panel"><div className="eyebrow">Pricing intelligence</div><h2>{ops.actionablePricing} supported actions</h2><p>{ops.pricingEvidenceUnavailable} analyses currently fail closed because fresh validated sold evidence is insufficient.</p><Link href="/">Open pricing analysis →</Link></section><section className="panel"><div className="eyebrow">Data quality</div><h2>{ops.proposed} matches need review</h2><p>{ops.unresolved} historical sales have no useful candidate. Overall linkage remains {ops.linkageHealth.percent}%.</p><Link href="/reconciliation">Review reconciliation →</Link></section><section className="panel"><div className="eyebrow">Exceptions</div><h2>{ops.exceptions} recent exceptions</h2><p>Refunds and cancellations from the last 30 days may affect inventory and margin decisions.</p><Link href="/sales">Review sales exceptions →</Link></section></div>
  </main>;
}

function Health({label,value,detail,good}:{label:string;value:string;detail:string;good:boolean}){return <div className="metric"><div className="metric-label">{label}</div><div className="metric-value" style={{color:good?"var(--success)":"var(--warning)"}}>{value}</div><div className="metric-detail">{detail}</div></div>}
