import { prisma } from "../lib/prisma";
import { loadInventoryHealth } from "../lib/inventory-health-data";

async function main(){
  const data=await loadInventoryHealth();const groups=new Map<string,{count:number;exposure:number;ready:number;review:number;moreEvidence:number}>();
  const readyExamples:Array<{action:string;title:string;before:unknown;after:unknown;why:string}>=[];
  const evidenceGaps=new Map<string,number>();const titleProposals:Array<{itemId:string;before:string;after:string;defects:string[]}>=[];
  for(const row of data.rows){const action=row.doctrine.interventionSelected;const group=groups.get(action)??{count:0,exposure:0,ready:0,review:0,moreEvidence:0};group.count++;group.exposure+=row.listedExposure;const ready=(action==="LOWER_PRICE"||action==="RAISE_PRICE")&&row.suggestedPrice!=null&&row.compConfidence!=null||action==="OPTIMIZE_TITLE"&&row.doctrine.proposedTitle!=null||action==="END_SELL_SIMILAR"&&row.doctrine.diagnosticFunnelStage==="refresh";if(ready){group.ready++;if(readyExamples.length<10)readyExamples.push({action,title:row.title,before:action==="OPTIMIZE_TITLE"?row.title:action==="END_SELL_SIMILAR"?row.ebayItemId:row.currentPrice,after:action==="OPTIMIZE_TITLE"?row.doctrine.proposedTitle:action==="END_SELL_SIMILAR"?"new provider ItemID after verified relist":row.suggestedPrice,why:row.doctrine.whyThisActionOutranksAlternatives});}else if(action==="MORE_EVIDENCE"||action==="LEARNING")group.moreEvidence++;else group.review++;groups.set(action,group);if(action==="MORE_EVIDENCE")for(const gap of row.doctrine.evidenceGaps)evidenceGaps.set(gap.code,(evidenceGaps.get(gap.code)??0)+1);if(action==="OPTIMIZE_TITLE"&&row.doctrine.proposedTitle)titleProposals.push({itemId:String(row.ebayItemId??""),before:row.title,after:row.doctrine.proposedTitle,defects:row.doctrine.verifiedTitleDefects});}
  const assessable=data.rows.filter(row=>!["MORE_EVIDENCE","LEARNING"].includes(row.doctrine.interventionSelected));const noAction=assessable.filter(row=>row.doctrine.interventionSelected==="LEAVE_ALONE").length;
  const [endedCleanup,executions]=await Promise.all([prisma.listing.aggregate({where:{listingStatus:"ended",listingFormat:{contains:"Fixed",mode:"insensitive"},relistedToEbayItemId:null,endTime:{lte:new Date(Date.now()-30*86_400_000)},ebayActionExecutions:{none:{action:"ENDED_BIN_CLEANUP",status:"verified"}}},_count:{id:true},_sum:{currentPrice:true}}),prisma.ebayActionExecution.groupBy({by:["status"],_count:{_all:true}})]);
  console.log(JSON.stringify({primaryInventoryHealthPct:assessable.length?Number((noAction/assessable.length*100).toFixed(1)):0,assessable:assessable.length,noAction,inventoryPerformanceScore:Math.round(data.portfolio.listingWeightedHealth),pareto:Array.from(groups,([action,value])=>({action,...value,inventoryPct:Number((value.count/data.rows.length*100).toFixed(1))})).sort((a,b)=>b.count-a.count),evidenceGapPareto:Array.from(evidenceGaps,([code,count])=>({code,count})).sort((a,b)=>b.count-a.count),titleProposals,endedBinCleanup:{count:endedCleanup._count.id,listedExposure:Number(endedCleanup._sum.currentPrice??0)},executions,readyExamples},null,2));
}
main().finally(()=>prisma.$disconnect());
