import { loadEnvConfig } from "@next/env";
loadEnvConfig(process.cwd(),true);
import {prisma} from "../lib/prisma.ts";
import {getItem,getValidAccessToken} from "../lib/ebay.ts";
import {loadTitleInspection} from "../lib/title-inspection-data.ts";
import {passesProvenTitleExecutionPolicy} from "../lib/title-inspection-agent.ts";
import {createGovernedTitleExecution,ebayWriteProvider,executeGovernedAction,unrelatedProviderState} from "../lib/governed-ebay-actions.ts";
const ARG="--execute-approved-title-v2-scale",OPERATOR_ID="operator-approved-title-v2-scale-2026-08-23";
const stable=(value:unknown)=>JSON.stringify(value);
async function main(){if(!process.argv.includes(ARG))throw new Error(`Explicit ${ARG} is required`);const benchmark=await loadTitleInspection(),candidates=benchmark.recommendations.filter(passesProvenTitleExecutionPolicy),results:Array<Record<string,unknown>>=[];
 for(const row of candidates){let executionId:string|null=null;try{const listing=await prisma.listing.findUnique({where:{id:row.listingId},include:{store:true}});if(!listing||listing.listingStatus!=="active"||listing.title!==row.currentTitle)throw new Error("Persisted active title changed after selection");const{accessToken}=await getValidAccessToken(listing.store),live=await getItem(accessToken,row.ebayItemId);if(String(live.SellingStatus?.ListingStatus??"").toLowerCase()!=="active"||live.Title!==row.currentTitle)throw new Error("Live active title changed after selection");const unrelatedBefore=unrelatedProviderState(live),execution=await createGovernedTitleExecution(row.listingId,OPERATOR_ID);executionId=execution.id;if(String((execution.proposedState as Record<string,unknown>).title)!==row.proposedTitle)throw new Error("Governed proposal changed after selection");const completed=await executeGovernedAction(execution.id,OPERATOR_ID,ebayWriteProvider,{writesEnabled:true}),verified=await getItem(accessToken,row.ebayItemId),events=await prisma.ebayActionExecutionEvent.findMany({where:{executionId},orderBy:{sequence:"asc"}});results.push({itemId:row.ebayItemId,executionId,decisionId:execution.decisionId,before:row.currentTitle,after:verified.Title,qualityBefore:row.qualityBefore.total,qualityAfter:row.qualityAfter?.total,qualityImprovement:row.qualityImprovement,status:completed.status,providerVerifiedAt:completed.providerVerifiedAt,unrelatedStateUnchanged:stable(unrelatedBefore)===stable(unrelatedProviderState(verified)),providerWarnings:events.filter(event=>event.type==="provider_accepted").map(event=>event.snapshot)});}catch(error){results.push({itemId:row.ebayItemId,executionId,status:"failed",error:error instanceof Error?error.message:"Unknown failure"});if(executionId&&await prisma.ebayActionExecutionEvent.count({where:{executionId,type:"unintended_change_detected"}})>0)break;}}
 const refreshed=await loadTitleInspection();console.log(JSON.stringify({selected:candidates.length,attempted:results.length,results,remainingActionable:refreshed.recommendations.filter(passesProvenTitleExecutionPolicy).length},null,2));}
main().finally(()=>prisma.$disconnect()).catch(error=>{console.error(error instanceof Error?error.message:error);process.exitCode=1;});
