import nextEnv from "@next/env";const{loadEnvConfig}=nextEnv;loadEnvConfig(process.cwd(),true);
import {prisma} from "../lib/prisma.ts";
import {callTradingApi,getValidAccessToken} from "../lib/ebay.ts";
import {getBrowseItemByLegacyId,getEbayApplicationAccessToken} from "../lib/ebay-browse.ts";
const IDS=["358541944249","358541944298"] as const;
const POLICY={payment:"248164941010",returns:"248164940010",shipping:"248164775010"};
const esc=(v:string)=>v.replaceAll("&","&amp;").replaceAll("<","&lt;").replaceAll(">","&gt;").replaceAll('"',"&quot;").replaceAll("'","&apos;");
async function main(){const store=await prisma.store.findFirstOrThrow({where:{isActive:true,connectionStatus:"connected"}}),[{accessToken},browseToken]=await Promise.all([getValidAccessToken(store),getEbayApplicationAccessToken()]),results=[];
 for(const id of IDS){try{const item=await getBrowseItemByLegacyId(browseToken,id),qty=Number(item.estimatedAvailabilities?.[0]?.estimatedAvailableQuantity),price=Number(item.price?.value),pictures=[item.image?.imageUrl,...(item.additionalImages??[]).map(x=>x.imageUrl)].filter((x):x is string=>Boolean(x)),aspects=(item.localizedAspects??[]).flatMap(x=>x.name&&x.value?[{name:x.name,value:x.value}]:[]),split=aspects.map(x=>({name:x.name,values:x.value.length>65?x.value.split(/,\s*/).filter(Boolean):[x.value]}));if(!item.categoryId||!item.conditionId||!qty||!price||pictures.length<2)throw new Error("Incomplete Browse reconstruction");if(split.some(x=>x.values.some(v=>v.length>65)))throw new Error("A logical value remains over 65 characters after lossless comma splitting");const description=`${item.title}. You will receive the item shown in the listing photos.`,condition=item.conditionId==="4000"?`<ConditionDescriptors><ConditionDescriptor><Name>40001</Name><Value>400010</Value></ConditionDescriptor></ConditionDescriptors>`:"";const body=`<VerifyAddFixedPriceItemRequest xmlns="urn:ebay:apis:eBLBaseComponents"><Item><SKU>VERIFY-MULTI-${id}</SKU><Title>${esc(item.title)}</Title><Description>${esc(description)}</Description><PrimaryCategory><CategoryID>${esc(item.categoryId)}</CategoryID></PrimaryCategory><StartPrice currencyID="USD">${price.toFixed(2)}</StartPrice><Quantity>${qty}</Quantity><ConditionID>${esc(item.conditionId)}</ConditionID>${condition}<Country>US</Country><Currency>USD</Currency><DispatchTimeMax>2</DispatchTimeMax><ListingDuration>GTC</ListingDuration><ListingType>FixedPriceItem</ListingType><Location>Waxahachie, Texas</Location><PostalCode>75167</PostalCode><PictureDetails>${pictures.map(x=>`<PictureURL>${esc(x)}</PictureURL>`).join("")}</PictureDetails><ItemSpecifics>${split.map(x=>`<NameValueList><Name>${esc(x.name)}</Name>${x.values.map(v=>`<Value>${esc(v)}</Value>`).join("")}</NameValueList>`).join("")}</ItemSpecifics><SellerProfiles><SellerPaymentProfile><PaymentProfileID>${POLICY.payment}</PaymentProfileID></SellerPaymentProfile><SellerReturnProfile><ReturnProfileID>${POLICY.returns}</ReturnProfileID></SellerReturnProfile><SellerShippingProfile><ShippingProfileID>${POLICY.shipping}</ShippingProfileID></SellerShippingProfile></SellerProfiles><Site>US</Site></Item></VerifyAddFixedPriceItemRequest>`;const response=await callTradingApi({callName:"VerifyAddFixedPriceItem",siteId:0,accessToken,xmlBody:body});results.push({sourceItemId:id,status:"VERIFIED",splitAspects:split.filter((x,i)=>aspects[i].value.length>65),ack:response.Ack,warnings:response.Errors??[]});}catch(error){results.push({sourceItemId:id,status:"FAILED",error:error instanceof Error?error.message:String(error)});}}
 console.log(JSON.stringify({writesPerformed:0,results},null,2));await prisma.$disconnect();}
main().catch(async e=>{console.error(e);await prisma.$disconnect();process.exitCode=1;});
