import Link from "next/link";
import { prisma } from "@/lib/prisma";
import { loadInventoryHealth } from "@/lib/inventory-health-data";
import { buildActionBrief } from "@/lib/action-presentation";
import { loadPricingEvidencePlan } from "@/lib/pricing-evidence-plan-data";
import {loadSellActionCenter} from "@/lib/sell-action-center";
import SellActionCenterReview from "@/components/SellActionCenterReview";

export const dynamic="force-dynamic";
const usd=(value:number)=>new Intl.NumberFormat("en-US",{style:"currency",currency:"USD",maximumFractionDigits:0}).format(value);
const pct=(value:number)=>`${value.toFixed(1)}%`;
const actionLabel=(value:string)=>value.replaceAll("_"," ");
const ACTION_ORDER=["HEALTHY_LEAVE_ALONE","OPTIMIZE_TITLE","LOWER_PRICE","RAISE_PRICE","END_SELL_SIMILAR","END_DONT_RELIST","ENDED_BIN_CLEANUP","OFFER_OPPORTUNITY","MORE_EVIDENCE","LEARNING_UNKNOWN"] as const;
const actionCategory=(value:string)=>value==="LEAVE_ALONE"?"HEALTHY_LEAVE_ALONE":value==="EXIT_REVIEW"?"END_DONT_RELIST":value==="OFFER_CONVERSION"?"OFFER_OPPORTUNITY":value==="LEARNING"?"LEARNING_UNKNOWN":value;
const categoryLabel=(value:string)=>({HEALTHY_LEAVE_ALONE:"Healthy / Leave Alone",END_DONT_RELIST:"End / Don't Relist",OFFER_OPPORTUNITY:"Offer Opportunity",LEARNING_UNKNOWN:"Learning / Unknown",END_SELL_SIMILAR:"End & Sell Similar",ENDED_BIN_CLEANUP:"Ended BIN Cleanup",OPTIMIZE_TITLE:"Optimize Title",LOWER_PRICE:"Lower Price",RAISE_PRICE:"Raise Price",MORE_EVIDENCE:"More Evidence"}[value]??actionLabel(value));

export default async function InventoryActionCenter({searchParams}:{searchParams?:{execution?:string}}){
  const endedCleanupWhere={listingStatus:"ended",listingFormat:{contains:"Fixed",mode:"insensitive" as const},relistedToEbayItemId:null,endTime:{lte:new Date(Date.now()-30*86_400_000)},ebayActionExecutions:{none:{action:"ENDED_BIN_CLEANUP",status:"verified"}}};
  const [actionCenter,data,recovered,unavailable,pending,latestJob,execution,endedCleanup,endedCleanupSummary,recentExecutions,pricingPlan]=await Promise.all([
    loadSellActionCenter(),
    loadInventoryHealth(),
    prisma.listing.count({where:{listingStatus:"active",authoritativeSource:"ebay-trading-get-item"}}),
    prisma.listing.count({where:{listingStatus:"active",authoritativeSource:"ebay-trading-get-item-unavailable"}}),
    prisma.listing.count({where:{listingStatus:"active",authoritativeObservedAt:null}}),
    prisma.syncJob.findFirst({where:{type:"active_evidence_recovery"},orderBy:{createdAt:"desc"},select:{status:true,progress:true,failureCount:true,updatedAt:true}}),
    searchParams?.execution?prisma.ebayActionExecution.findUnique({where:{id:searchParams.execution},include:{events:{orderBy:{sequence:"asc"}}}}):null,
    prisma.listing.findMany({where:endedCleanupWhere,orderBy:{endTime:"asc"},take:20,select:{id:true,title:true,ebayItemId:true,currentPrice:true,endTime:true}}),
    prisma.listing.aggregate({where:endedCleanupWhere,_count:{id:true},_sum:{currentPrice:true}}),
    prisma.ebayActionExecution.findMany({orderBy:{createdAt:"desc"},take:10,select:{id:true,action:true,status:true,oldEbayItemId:true,newEbayItemId:true,createdAt:true,listing:{select:{title:true}}}}),
    loadPricingEvidencePlan(),
  ]);
  const categories=new Map<string,{count:number;exposure:number;ready:number;review:number;moreEvidence:number}>();
  const evidenceGaps=new Map<string,{count:number;automatic:number;blocked:Set<string>}>();
  for(const row of data.rows){const action=row.doctrine.interventionSelected,key=actionCategory(action);const group=categories.get(key)??{count:0,exposure:0,ready:0,review:0,moreEvidence:0};group.count++;group.exposure+=row.listedExposure;const isReady=(action==="LOWER_PRICE"||action==="RAISE_PRICE")&&row.suggestedPrice!=null&&row.compConfidence!=null||action==="OPTIMIZE_TITLE"&&row.doctrine.proposedTitle!=null||action==="END_SELL_SIMILAR"&&row.doctrine.diagnosticFunnelStage==="refresh";if(isReady)group.ready++;else if(action==="MORE_EVIDENCE"||action==="LEARNING")group.moreEvidence++;else group.review++;categories.set(key,group);}
  for(const row of data.rows.filter(row=>row.doctrine.interventionSelected==="MORE_EVIDENCE")){for(const gap of row.doctrine.evidenceGaps){const summary=evidenceGaps.get(gap.code)??{count:0,automatic:0,blocked:new Set<string>()};summary.count++;if(gap.automatic)summary.automatic++;for(const item of gap.blocks)summary.blocked.add(item);evidenceGaps.set(gap.code,summary);}}
  const evidencePareto=Array.from(evidenceGaps,([code,value])=>({code,...value})).sort((a,b)=>b.count-a.count);
  categories.set("ENDED_BIN_CLEANUP",{count:endedCleanupSummary._count.id,exposure:Number(endedCleanupSummary._sum.currentPrice??0),ready:endedCleanupSummary._count.id,review:0,moreEvidence:0});
  const pareto=ACTION_ORDER.map(action=>({action,...(categories.get(action)??{count:0,exposure:0,ready:0,review:0,moreEvidence:0})}));const assessable=data.rows.filter(row=>!['MORE_EVIDENCE','LEARNING'].includes(row.doctrine.interventionSelected));const leaveAlone=assessable.filter(row=>row.doctrine.interventionSelected==="LEAVE_ALONE").length;const inventoryHealth=assessable.length?leaveAlone/assessable.length*100:0;
  const listingIssues=new Map<string,{count:number;exposure:number;example:string}>();const addIssue=(issue:string,row:(typeof data.rows)[number])=>{const item=listingIssues.get(issue)??{count:0,exposure:0,example:row.title};item.count++;item.exposure+=row.listedExposure;listingIssues.set(issue,item);};
  for(const row of data.rows){for(const defect of row.doctrine.verifiedTitleDefects)addIssue(`Missing verified ${defect.slice(0,defect.indexOf(":"))} in title`,row);if(row.doctrine.evidenceGaps.some(g=>g.code==="SAFE_TITLE_PROPOSAL_UNAVAILABLE"))addIssue("Verified title improvement exceeds safe title limit",row);if(row.doctrine.evidenceGaps.some(g=>g.code==="CARD_IDENTITY_INCOMPLETE"))addIssue("Card identity incomplete",row);if(row.doctrine.evidenceGaps.some(g=>g.code==="CATEGORY_UNKNOWN"))addIssue("Category unavailable",row);if(row.doctrine.evidenceGaps.some(g=>g.code==="LISTING_TYPE_UNKNOWN"))addIssue("Listing format unavailable",row);if((row.watchers??0)>=3&&row.units90===0)addIssue("Watcher intent without sale",row);if((row.ageDays??0)>=90&&row.units90===0&&(row.viewsForDecision??0)<5)addIssue("Stale with weak discovery",row);}
  const listingIssuePareto=Array.from(listingIssues,([issue,value])=>({issue,...value})).sort((a,b)=>b.count-a.count||b.exposure-a.exposure).slice(0,12);
  const readyAll=data.rows.filter(row=>((row.doctrine.interventionSelected==="LOWER_PRICE"||row.doctrine.interventionSelected==="RAISE_PRICE")&&row.suggestedPrice!=null&&row.compConfidence!=null)||(row.doctrine.interventionSelected==="OPTIMIZE_TITLE"&&row.doctrine.proposedTitle)||(row.doctrine.interventionSelected==="END_SELL_SIMILAR"&&row.doctrine.diagnosticFunnelStage==="refresh"));const readyRows=readyAll.slice(0,20);
  const controlledPilot=readyAll.filter(row=>(row.doctrine.interventionSelected==="LOWER_PRICE"||row.doctrine.interventionSelected==="RAISE_PRICE")&&(row.compConfidence??0)>=90).sort((a,b)=>(b.compConfidence??0)-(a.compConfidence??0))[0]??null;
  return <main className="page sell-action-center"><section className="health-hero"><div><div className="eyebrow">Sell · owned inventory</div><h1>Action Center</h1><p className="health-intro">One prioritized queue combining buyer intent, sales velocity, title, refresh, and listing-quality evidence. Existing engines remain authoritative; Action Center only resolves what the operator should review first.</p></div><div className="health-score"><strong>{actionCenter.rows.filter(row=>row.status!=="COMPLETED").length}</strong><span> actions</span><small>Profitable sales velocity queue</small></div></section>
    <section className="metric-grid"><Metric label="High-confidence actions" value={actionCenter.highConfidence.toLocaleString()} detail="Governed and approval-ready"/><Metric label="Needs review" value={actionCenter.needsReview.toLocaleString()} detail="Operator judgment required"/><Metric label="Blocked by evidence" value={actionCenter.blocked.toLocaleString()} detail="Shown, never silently hidden"/><Metric label="Recently completed" value={actionCenter.recentlyCompleted.toLocaleString()} detail="Provider-verified in 30 days"/></section>
    <SellActionCenterReview rows={actionCenter.rows}/>
    <section className="panel health-section"><div className="eyebrow">Aggregation health</div><h2>Sources and conflict resolution</h2><p>{actionCenter.conflicts.toLocaleString()} listings produced overlapping recommendations. Action Center keeps one primary action and preserves the rest under lower-ranked recommendations: buyer intent → sales-velocity opportunity → confidence → execution safety → freshness.</p><div className="compact-rows">{actionCenter.probes.map((probe,index)=><div key={`${probe.provider}-${index}`}><strong>{probe.provider}</strong><span>{probe.status}</span><span>{probe.message}</span><span>{new Date(probe.observedAt).toLocaleString()}</span></div>)}</div></section>
    <section className="metric-grid"><Metric label="Assessable inventory" value={assessable.length.toLocaleString()} detail={`${data.rows.length-assessable.length} remain learning or evidence-blocked`}/><Metric label="No action recommended" value={leaveAlone.toLocaleString()} detail={`${pct(inventoryHealth)} of assessable inventory`}/><Metric label="Inventory Performance Score" value={`${Math.round(data.portfolio.listingWeightedHealth)} / 100`} detail="Secondary legacy performance measure"/><Metric label="Ready actions" value={(readyAll.length+endedCleanupSummary._count.id).toLocaleString()} detail="Exact proposal and doctrine support"/></section>
    <section className="panel health-section"><div className="eyebrow">Evidence recovery</div><h2>Authoritative listing research</h2><div className="metric-grid"><Metric label="Total blocked" value={data.rows.filter(row=>row.doctrine.interventionSelected==="MORE_EVIDENCE").length.toLocaleString()} detail="Current doctrine result"/><Metric label="Recovered" value={recovered.toLocaleString()} detail="Authoritative GetItem cached"/><Metric label="Pending" value={pending.toLocaleString()} detail="Bounded worker queue"/><Metric label="Permanent / unavailable" value={unavailable.toLocaleString()} detail="Provider-declared unavailable"/><Metric label="Actionable after recovery" value={readyAll.length.toLocaleString()} detail="Exact governed proposal ready"/><Metric label="Still More Evidence" value={data.rows.filter(row=>row.doctrine.interventionSelected==="MORE_EVIDENCE").length.toLocaleString()} detail={latestJob?`Worker ${latestJob.status}; ${latestJob.progress} recovered by job`:`Worker awaiting first scheduled run`}/></div></section>
    <section className="panel health-section"><div className="eyebrow">Evidence blocker Pareto</div><h2>What research unlocks the most decisions?</h2><p>Counts overlap because one listing may need several facts. Automatic means Legends can recover the evidence through an already-authorized read-only source; it does not mean an action is approved.</p><div className="pareto-table"><div className="pareto-row pareto-head"><span>Missing evidence</span><span>Affected listings</span><span>Automatic</span><span>Decisions blocked</span></div>{evidencePareto.map(row=><div className="pareto-row" key={row.code}><strong>{actionLabel(row.code)}</strong><span>{row.count.toLocaleString()}</span><span>{row.automatic.toLocaleString()}</span><span>{Array.from(row.blocked).join(", ")}</span></div>)}</div></section>
    <section className="panel health-section"><div className="eyebrow">Pricing evidence acquisition dry-run</div><h2>Highest-value research first</h2><div className="metric-grid"><Metric label="Pricing gaps classified" value={pricingPlan.dryRun.totalCandidates.toLocaleString()} detail="Supported price actions excluded"/><Metric label="Internal sales indexed" value={pricingPlan.linkedHistoricalSales.toLocaleString()} detail="Authoritative linked history"/><Metric label="Existing/free evidence" value={pricingPlan.dryRun.existingEvidenceReused.toLocaleString()} detail="Internal, cached, or authorized eBay evidence first"/><Metric label="External eligible" value={pricingPlan.dryRun.externalEligible.toLocaleString()} detail="Not automatically researched"/><Metric label="Configured request cap" value={pricingPlan.dryRun.configuredRequestCap.toLocaleString()} detail="Hard external-request budget"/><Metric label="Estimated requests now" value={pricingPlan.dryRun.estimatedProviderRequests.toLocaleString()} detail="Requests and dollars tracked separately"/></div><div className="pareto-table"><div className="pareto-row pareto-head"><span>Priority listing</span><span>Cohort</span><span>Score</span><span>Expected source</span></div>{pricingPlan.dryRun.priorityPreview.slice(0,10).map(row=><div className="pareto-row" key={row.listingId}><strong>{row.title}</strong><span>{actionLabel(row.cohort)}</span><span>{row.score}</span><span>{actionLabel(row.expectedSource)}</span></div>)}</div><p className="badge badge-warning">Dry-run only. The zero request cap prevents every paid-provider call and stops the worker cleanly.</p></section>
    <section className="panel health-section"><div className="eyebrow">Mutually exclusive Action Pareto</div><h2>What should happen first?</h2><div className="pareto-table"><div className="pareto-row pareto-head"><span>First action</span><span>Listings / share</span><span>Listed exposure</span><span>Ready / Review / Evidence</span></div>{pareto.map(row=><div className="pareto-row" key={row.action}><strong>{categoryLabel(row.action)}</strong><span>{row.count.toLocaleString()} · {pct(row.count/data.rows.length*100)}</span><span>{usd(row.exposure)}</span><span>{row.ready} / {row.review} / {row.moreEvidence}</span></div>)}</div></section>
    <section className="panel health-section"><div className="eyebrow">Listing issue Pareto</div><h2>Repeatable cleanup patterns</h2><p>Issues may overlap. Each pattern comes from authoritative listing evidence or observed funnel behavior; only the doctrine above assigns the mutually exclusive first action.</p><div className="pareto-table"><div className="pareto-row pareto-head"><span>Repeated issue</span><span>Listings</span><span>Listed exposure</span><span>Representative example</span></div>{listingIssuePareto.map(row=><div className="pareto-row" key={row.issue}><strong>{row.issue}</strong><span>{row.count.toLocaleString()}</span><span>{usd(row.exposure)}</span><span>{row.example}</span></div>)}</div></section>
    {execution?<section className="panel health-section"><div className="eyebrow">Governed execution</div><h2>{actionLabel(execution.action)} · {execution.status}</h2><p>Old ItemID {execution.oldEbayItemId}{execution.newEbayItemId?` → New ItemID ${execution.newEbayItemId}`:""}</p><div className="action-columns"><div><b>Before</b><pre>{JSON.stringify(execution.beforeState,null,2)}</pre></div><div><b>Approved after</b><pre>{JSON.stringify(execution.proposedState,null,2)}</pre></div></div><details open><summary>Immutable execution events</summary><ol>{execution.events.map(event=><li key={event.id}>{event.type} · {event.createdAt.toLocaleString()}</li>)}</ol></details>{execution.status!=="verified"?((execution.action==="SEND_OFFER"?process.env.EBAY_SELLER_OFFER_WRITES_ENABLED==="explicitly-approved-canary":execution.action==="ENDED_BIN_CLEANUP"||process.env.EBAY_PRODUCTION_WRITES_ENABLED==="explicitly-approved")?<form method="post" action={`/api/inventory-action-executions/${execution.id}`}><button className="btn-primary">{execution.action==="ENDED_BIN_CLEANUP"?"COMPLETE INTERNAL CLEANUP":execution.action==="SEND_OFFER"?"SEND EXACT APPROVED OFFER":"EXECUTE APPROVED CHANGE"}</button></form>:<p className="badge badge-warning">Execution locked: {execution.action==="SEND_OFFER"?"seller-offer canary submission requires separate approval":"production provider writes require a separate controlled approval"}.</p>):null}</section>:null}
    <section className="panel health-section"><div className="eyebrow">Ready to approve</div><h2>Exact evidence-backed changes</h2>{readyRows.length?<div className="inventory-action-grid">{readyRows.map(row=>{const brief=buildActionBrief(row);return <article className="inventory-action" key={row.id}><div className="action-top"><span className="pill">{actionLabel(row.doctrine.interventionSelected)}</span><span className="pill">Action confidence {row.doctrine.actionConfidence.score}</span></div><h3>{row.title}</h3><p><strong>Exact change:</strong> {brief.recommendation}</p><p><strong>Why first:</strong> {row.doctrine.whyThisActionOutranksAlternatives}</p><details><summary>Evidence and alternatives</summary><ul>{brief.evidence.map(item=><li key={item}>{item}</li>)}</ul><ul>{row.doctrine.alternativesRejectedOrDeferred.map(item=><li key={item}>{item}</li>)}</ul></details><form method="post" action={`/api/inventory-actions/${row.id}/approve`}><button className="btn-primary">APPROVE EXACT PROPOSAL</button></form></article>})}</div>:<div className="empty-state">No additional actions are execution-ready yet. Evidence thresholds remain unchanged.</div>}</section>
    <section className="panel health-section"><div className="eyebrow">Controlled production-write preflight</div><h2>First single-listing pilot is prepared, not activated</h2>{controlledPilot?(()=>{const brief=buildActionBrief(controlledPilot);return <div className="inventory-action"><div className="action-top"><span className="pill">READ-ONLY PREPARATION</span><span className="pill">Action confidence {controlledPilot.doctrine.actionConfidence.score}</span><span className="pill">Comp confidence {controlledPilot.compConfidence}</span></div><h3>{controlledPilot.title}</h3><div className="action-columns"><div><b>Current state</b><pre>{JSON.stringify({itemId:controlledPilot.ebayItemId,title:controlledPilot.title,price:controlledPilot.currentPrice},null,2)}</pre></div><div><b>Proposed state</b><pre>{JSON.stringify({itemId:controlledPilot.ebayItemId,title:controlledPilot.title,price:controlledPilot.suggestedPrice},null,2)}</pre></div></div><p><strong>Doctrine rationale:</strong> {controlledPilot.doctrine.whyThisActionOutranksAlternatives}</p><p><strong>Evidence:</strong></p><ul>{brief.evidence.map(item=><li key={item}>{item}</li>)}</ul><p><strong>Expected API operation:</strong> eBay Trading API ReviseFixedPriceItem changing StartPrice only, with the immutable execution idempotency key as MessageID.</p><ol><li><strong>Approval:</strong> Josh authenticates and approves this exact ItemID and Current → Proposed price.</li><li><strong>Server revalidation:</strong> rebuild doctrine, require the same doctrine version/action/target, then read eBay and require unchanged live title and price.</li><li><strong>Provider verification:</strong> read the ItemID back and require the returned price to equal the approved target within half a cent.</li><li><strong>Failure behavior:</strong> record a failed immutable event, keep the listing history, and never retry as a different proposal. A changed proposal requires new approval.</li><li><strong>Restoration:</strong> if provider verification shows an operational problem after a successful revision, create a new governed proposal restoring {usd(controlledPilot.currentPrice)}; require fresh authenticated approval and verify the restored price from eBay.</li></ol><p className="badge badge-warning">Not activated. Production writes remain disabled; no approval or execution record was created.</p></div>})():<p>No price action currently meets the conservative pilot threshold. Legends will not manufacture one.</p>}</section>
    {endedCleanup.length?<section className="panel health-section"><div className="eyebrow">Ended BIN cleanup</div><h2>Internal archive-ready listings</h2><p>These fixed-price listings have been ended for at least 30 days and have no recorded replacement. Approval only marks the cleanup reviewed inside Legends; it never deletes marketplace or historical records.</p><div className="inventory-action-grid">{endedCleanup.map(row=><article className="inventory-action" key={row.id}><h3>{row.title}</h3><p><strong>Exact change:</strong> cleanup disposition Not reviewed → Reviewed and archived. Listing status and ItemID remain unchanged.</p><p>Ended {row.endTime?.toLocaleDateString()} · {usd(Number(row.currentPrice))} historical listed price.</p><form method="post" action={`/api/inventory-actions/${row.id}/approve`}><button className="btn-primary">APPROVE INTERNAL CLEANUP</button></form></article>)}</div></section>:null}
    <section className="panel health-section"><div className="eyebrow">Execution ledger</div><h2>Recent governed actions</h2>{recentExecutions.length?<div className="compact-rows">{recentExecutions.map(item=><Link key={item.id} href={`/inventory-actions?execution=${item.id}`}><strong>{actionLabel(item.action)} · {item.status}</strong><span>{item.listing.title}</span><span>{item.oldEbayItemId}{item.newEbayItemId?` → ${item.newEbayItemId}`:""}</span><span>{item.createdAt.toLocaleString()}</span></Link>)}</div>:<p>No governed action has been approved or executed yet.</p>}</section>
    <p><Link href="/review-session">Open diagnostic Review Session →</Link></p>
  </main>;
}
function Metric({label,value,detail}:{label:string;value:string;detail:string}){return <div className="metric"><div className="metric-label">{label}</div><div className="metric-value">{value}</div><div className="metric-detail">{detail}</div></div>}
