import Link from "next/link";
import CostBasisEditor from "@/components/CostBasisEditor";
import { prisma } from "@/lib/prisma";

export const dynamic = "force-dynamic";
const DAY=86_400_000;
const money=(value:number)=>new Intl.NumberFormat("en-US",{style:"currency",currency:"USD"}).format(value);

export default async function CostBasisPriorityPage(){
  const now=new Date();const since30=new Date(now.getTime()-30*DAY);
  const [active,totalWithCost,candidates]=await Promise.all([
    prisma.listing.count({where:{listingStatus:"active"}}),
    prisma.listing.count({where:{listingStatus:"active",costBasis:{isNot:null}}}),
    prisma.listing.findMany({where:{listingStatus:"active",costBasis:null},orderBy:[{currentPrice:"desc"},{watchers:"desc"}],take:300,select:{id:true,title:true,currentPrice:true,quantity:true,views:true,watchers:true,startTime:true,recommendations:{where:{status:"pending",type:{in:["raise-price","lower-price"]},confidence:{gte:60}},take:1,select:{type:true,confidence:true,suggestedPrice:true}},saleEvents:{where:{provider:"ebay-fulfillment",status:{not:"cancelled"}},orderBy:{soldAt:"desc"},take:30,select:{price:true,quantity:true,soldAt:true}}}}),
  ]);
  const ranked=candidates.map(row=>{const recent=row.saleEvents.filter(sale=>sale.soldAt>=since30);const salesDollars=row.saleEvents.reduce((sum,sale)=>sum+Number(sale.price)*sale.quantity,0);const units=row.saleEvents.reduce((sum,sale)=>sum+sale.quantity,0);const rec=row.recommendations[0];const age=row.startTime?Math.max(0,Math.floor((now.getTime()-row.startTime.getTime())/DAY)):0;const score=Math.min(100,Math.min(35,Number(row.currentPrice)/5)+Math.min(25,salesDollars/20)+Math.min(15,units*3)+Math.min(10,row.watchers*2)+(rec?15:0)+(recent.length?5:0));const factors=[`${money(Number(row.currentPrice)*row.quantity)} listed exposure`,...(salesDollars?[`${money(salesDollars)} linked sales · ${units} units`]:[]),...(rec?[`${rec.type.replace("-"," ")} · confidence ${rec.confidence}`]:[]),...(row.watchers?[`${row.watchers} watchers`]:[]),...(age?[`${age} days listed`]:[])];return{...row,score,salesDollars,units,rec,factors};}).sort((a,b)=>b.score-a.score||Number(b.currentPrice)-Number(a.currentPrice)).slice(0,75);
  const pct=active?totalWithCost*100/active:0;
  return <main className="page"><div className="eyebrow">Profitability readiness</div><h1>Cost Basis Priority Queue</h1><p>Enter costs where they unlock the most decision value first. Rankings use listed exposure, authoritative sales, pricing evidence, velocity, and watcher interest—never invented costs.</p><div className="metric-grid" style={{marginBottom:20}}><div className="metric"><div className="metric-label">Cost coverage</div><div className="metric-value" style={{color:"var(--warning)"}}>{pct.toFixed(1)}%</div><div className="metric-detail">{totalWithCost.toLocaleString()} / {active.toLocaleString()} active listings</div></div><div className="metric"><div className="metric-label">Needs input</div><div className="metric-value">{(active-totalWithCost).toLocaleString()}</div><div className="metric-detail">Business data not yet available—not a system failure</div></div><div className="metric"><div className="metric-label">Bulk workflow</div><div className="metric-value" style={{fontSize:18}}><Link href="/cost-basis/import">Import CSV →</Link></div><div className="metric-detail">Preview matching and conflicts before apply</div></div></div><section className="panel"><div className="eyebrow">Highest decision value</div><h2>Start with these listings</h2><div className="action-list">{ranked.map((row,index)=><article className="action-card" key={row.id} style={{borderLeft:`3px solid ${row.rec?"var(--gold)":"var(--info)"}`}}><div><div className="action-score">{Math.round(row.score)}</div><div className="action-category">priority</div></div><div><div className="action-category">#{index+1} · {money(Number(row.currentPrice))} each · qty {row.quantity}</div><strong>{row.title}</strong><div className="metric-detail">{row.factors.join(" · ")}</div></div><CostBasisEditor listingId={row.id} initial={{unitAcquisitionCost:null,unitGradingCost:null,unitSuppliesCost:null,unitOutboundPostageCost:null,unitOtherCost:null,notes:null}}/></article>)}</div></section></main>;
}
