import Link from "next/link";
import SalesVelocityReview from "@/components/SalesVelocityReview";
import { loadSalesVelocity } from "@/lib/sales-velocity";

export const dynamic = "force-dynamic";
export default async function SalesVelocityPage() {
  const data = await loadSalesVelocity();
  return <main className="page sales-velocity-page"><header className="health-hero"><div><div className="eyebrow">Seller Opportunities · owned inventory</div><h1>Sales Velocity</h1><p className="health-intro">Diagnose exposure, engagement, and conversion before changing economics. Maximize profitable inventory velocity—not sales at any cost.</p><p><Link href="/seller-opportunities">← External auction acquisition</Link> · <Link href="/seller-opportunities/sales-velocity/weekend-sprint">Weekend Traffic Sprint →</Link></p></div><div className="health-score"><strong>{data.rows.length}</strong><span> active</span><small>Read-only recommendations</small></div></header><section className="metric-grid"><Metric label="Complete evidence" value={data.completeEvidenceCount}/><Metric label="Send offer" value={data.counts["SEND OFFER"]}/><Metric label="Increase ads" value={data.counts["INCREASE ADS"]}/><Metric label="Listing review" value={data.counts["TITLE / LISTING REVIEW"]}/><Metric label="Reprice" value={data.counts.REPRICE}/><Metric label="Protect margin" value={data.counts["HOLD / PROTECT MARGIN"]}/><Metric label="Manual review" value={data.counts["MANUAL REVIEW"]}/></section><section className="panel velocity-watcher-audit"><strong>Trading watcher evidence:</strong> {data.watcherAudit.authoritative} authoritative · {data.watcherAudit.stale} stale · {data.watcherAudit.missing} missing/unverifiable. Persisted zeros without GetItem provenance are not treated as authoritative.</section><section className="panel velocity-probes"><div className="eyebrow">Read-only eBay evidence probes</div><h2>Provider status</h2><div>{data.probes.map((probe, index) => <span key={`${probe.provider}-${index}`} className={`card-${probe.status === "succeeded" ? "success" : probe.status === "failed" ? "danger" : "warning"}`}><b>{probe.provider}</b><small>{probe.message}</small></span>)}</div></section><SalesVelocityReview rows={data.rows}/></main>;
}
function Metric({ label, value }: { label: string; value: number }) { return <div className="metric"><div className="metric-label">{label}</div><div className="metric-value">{value}</div></div>; }
